.travis.yml
forge.config.js

Derived from https://github.com/electron-userland/electron-forge/blob/befdf65bc77573c83687440c6d07773eac46037d/tmpl/_travis.yml
I set up travis and added a GITHUB_TOKEN env var with repo scope.

add Travis config

---

forge.config.js
package-lock.json
package.json
src/main.ts

feat: add updater

---

static/css/main.css

The buttons had a weird "focus" color that looked bad. This fixes that.

Fix color for active button

---

forge.config.js
package-lock.json
package.json
src/main.ts
src/menu.ts
src/renderer/app.tsx
static/css/main.css
static/index.html

This PR adds two features:
• A default app menu
• Editors are now resizable

Default menu, resizable editors

---

package-lock.json
package.json
src/renderer/app.tsx
src/renderer/components/commands.tsx
src/renderer/components/header.tsx
src/renderer/components/token-dialog.tsx
static/css/main.css
yarn-error.log

Adds token validation and load / publish buttons (the load / publish UI needs work 😆)

feat: token validation and basic publish/load gist logic

---

.gitattributes
CODE_OF_CONDUCT.md
SECURITY.md

Two small docs to keep this repo sane.

Docs: Code of conduct, security 

---

src/main.ts
src/windows.ts
static/index.html
tools/tsc.js

Nothing fancy just yet, I just want the app to start :wink:

Allow app to start on Windows

---

package-lock.json
package.json

Turns out, Blueprint is amazing but has CSS that brings Chrome to its knees. Let's cut it out (for now).

Remove Blueprint from package.json

---

src/main/menu.ts

This allows to zoom in, out and reset.

Add zooming related actions to the view menu

---

src/utils/editor-layout.ts

fixes https://github.com/electron/fiddle/issues/33

Avoid lodash#throttle and just use timeouts

---

README.md
src/main/ipc.ts
src/main/menu.ts
src/main/windows.ts
tests/main/menu-spec.ts
tests/main/windows-spec.ts

Simple but meaningful change: You can now open multiple windows.

feat: Multi window support

---

src/ambient.d.ts
src/renderer/app.tsx
src/renderer/components/address-bar.tsx
src/renderer/components/editor.tsx
src/renderer/file-manager.ts
src/renderer/state.ts
tests/mocks/app.ts

You might already guess what this PR does: It'll ask you if you really want to quit Fiddle if the current state is unsaved, or if you really want to overwrite it with a template.

feat: Handle saved/unsaved state

---

src/main/windows.ts
tests/main/windows-spec.ts

Don't navigate, don't open new windows.

fix: Some sane security basics

---

src/renderer/file-manager.ts
static/templates/ipc/index.html
tests/renderer/file-manager-spec.ts

It's unclear to me why I added this call in the first place. Showing the item on save makes little sense 😅 
Closes #69

fix: Do not use "showItemInFolder" on save

---

README.md

Hi,
The link was broken, now it's good. I hope it helps.
Cheers,
G.

🔧 📝 Broken link

---

src/content/main.ts

This PR aims to solve the issue #60 . By replacing **loadFile** method with the **loadURL** method, based on the PR electron/electron#11565 😄 Please let me know if this works :)

fix: Support Electron <1.8.x

---

tools/contributors.js

I added my github username to the contributor list 😄

chore: Add myself to the contributor list

---

src/less/mosaic.less

fix: Correct padding error

---

package-lock.json
package.json

Fixed via Electron Forge v6.0.0-beta.28 (https://github.com/electron-userland/electron-forge/pull/567)
Closes #96.

fix: don't hang on window close when run via npm start

---

package-lock.json
package.json
src/renderer/components/token-dialog.tsx
tests/renderer/components/__snapshots__/token-dialog-spec.tsx.snap
tools/contributors.js

List of changes:
- Added key property for buttons in token dialog
- Updated Electron to 3.0.4 and TypeScript to 3.1.2
- Added myself to contributors page.

feat: Add key property for buttons, update electron and typescript

---

package-lock.json
package.json

This bumps the version number in preparation for the 0.4.0 release.

chore: Update version number

---

package-lock.json
package.json

feat: Update to Electron 3.0.11

---

package-lock.json
package.json

Now that all the fixes are in, let's move straight to 0.4.1 😬

chore: Bump version number

---

src/main/first-run.ts
src/main/main.ts
src/utils/check-first-run.ts
tests/main/files-spec.ts
tests/main/first-run-spec.ts
tests/main/main-spec.ts
tests/mocks/electron.ts
tests/utils/check-first-run-spec.ts
tests/utils/highlight-text-spec.ts
tests/utils/octokit-spec.ts
tests/utils/sorted-electron-map-spec.ts

This PR _also_ adds some tests. I've only found minor issues with the `first-run` code, all other logical changes are only there to support easier testing and documentation.

test: More test, more minor refactoring

---

package-lock.json
package.json

Simply bump the version number to 0.4.2.

chore: Bump version to 0.4.2

---

src/main/menu.ts

Enables to run a fiddle just with the keyboard.

feat: Allow to run a fiddle via F5

---

src/content/main.ts

Fixes https://github.com/electron/fiddle/issues/157

feat: support upcoming Electron 5.0 with nodeIntegration disabled by default

---

package-lock.json
package.json

feat: Update to Electron 4

---

src/renderer/templates.ts
tests/renderer/templates-spec.ts

This doesn't fix the actual bug in #76, but it might just help us figure out why we fail to load the template for some users.

fix: Add some detailed templates logging

---

package-lock.json
package.json

This PR updates Electron to v4.0.5.

build: Update to Electron 4.0.5

---

src/renderer/components/editors.tsx
tests/renderer/components/__snapshots__/editors-spec.tsx.snap
tests/renderer/components/commands-address-bar-spec.tsx
tests/renderer/components/editors-spec.tsx

Yes, 100% unit test coverage doesn't mean Fiddle is fully tested. Then again, I can't deal with us being at 99.8% 👯‍♂️

test: Ensure full coverage

---

static/show-me/clipboard/main.js
static/show-me/crashreporter/main.js
static/show-me/desktopcapturer/main.js
static/show-me/ipc/main.js
static/show-me/notification/main.js
static/show-me/remote/main.js
static/show-me/screen/main.js
static/show-me/shell/main.js
static/show-me/webframe/main.js
tools/contributors.js

**Issue:**  Uncaught ReferenceError: require is not defined  
**Files Affected:** All the Show Me example file  which uses './renderer.js'  
**Solution:** Can be solved by adding the webPreferences in main.js file.
`   webPreferences: {
nodeIntegration: true
}`

Fix: Require not defined bug

---

src/renderer/app.tsx
src/renderer/binary.ts
src/renderer/touch-bar-manager.ts
src/utils/nice-greeting.ts
src/utils/random.ts
tests/mocks/electron.ts
tests/renderer/app-spec.tsx
tests/renderer/touch-bar-manager-spec.ts
tests/utils/random-spec.ts

This PR adds touch bar support. I know, it's a bit late, but I was stuck on a plane and thought greeting people might be a cute thing to do. It has full test coverage, too.
Video: https://slack-files.com/T394SAQKC-FK7SMBRE1-2ebbde0c0f

feat: Touchbar

---

src/renderer/components/dialog-token.tsx

Fixed:
1. Please provide a valid GitHub Personal Access Token
2. Can't perform a React state update on an unmounted component.

Fix: submit token

---

src/renderer/binary.ts
tests/renderer/binary-spec.ts

Closes #217.
Attempts to remove the correct folder 4 times, as does the binary remover does. Only executes after the binary is successfully removed. Refactored the re-run logic a bit so it could be reused between the two functions.
cc @miniak

fix: clean up typedefs when removing binaries

---

src/renderer/components/settings-execution.tsx
src/renderer/components/settings-general-appearance.tsx
src/renderer/components/settings.tsx
tests/renderer/components/__snapshots__/settings-execution-spec.tsx.snap
tests/renderer/components/__snapshots__/settings-spec.tsx.snap
tests/renderer/components/settings-general-appearance-spec.tsx
tests/renderer/components/settings-spec.tsx

UX fixes:
1) Allows user to close the settings panel on `Escape` with a `keyup` listener that attaches when the component is mounted and detaches when the component is unmounted.
2) When creating a new theme in the Appearance Settings, the newly generated theme will instantly appear in the menu's dropdown.
Small typo fixes:
1) Fixes typo ("Exection" -> "Execution")
2) Fixes name of the Settings component in the `describe()` function of the spec.

feat: settings UX improvements

---

package-lock.json
package.json

This PR updates Electron to v7.1.3.

chore: Update Electron to 7.1.3

---

tools/contributors.js

Adds me as a contributor 🙇‍♂️. Teamwork makes the dream work

chore: Add issacgerges as a contributor

---

package-lock.json
package.json
src/main/main.ts
src/renderer/app.tsx
tests/mocks/electron.ts

We have sentry, may as well use it to collect crash reports

chore: add sentry for crash / js error reporting

---

.travis.yml

We need to upgrade our Linux image so that we create proper `rpm` packages.

build: Use Ubuntu 18.04 in Travis CI

---

CONTRIBUTING.md
README.md

Hello! I updated the README with a Get Started section to document the steps needed to run Fiddle locally.

docs: add Contributing section to readme and descriptive text for running Fiddle from source in CONTRIBUTING.md

---

src/renderer/components/commands-bisect.tsx
src/renderer/components/dialog-bisect.tsx
tests/renderer/components/dialog-bisect-spec.tsx

fix: correct sense of bisect buttons

---

package-lock.json
package.json

chore: 0.15.1

---

src/renderer/components/commands-publish-button.tsx

Fixes #412 
GIF 🙌
/cc @codebytere

feat: allow to publish if user would to do it

---

src/main/menu.ts
tests/main/menu-spec.ts

fix: proper toggling for devtools

---

src/renderer/touch-bar-manager.ts

Removes an unused class property.

chore: remove unused code from TouchBar manager

---

src/renderer/transforms/forge.ts
tests/transforms/forge-spec.ts

chore: update forge in the packaged app

---

package-lock.json
package.json

:electron: :electron: :electron: :electron: :electron: :electron: :electron: :electron:
:electron: :electron: :electron: :electron: :electron: :electron: :electron: :electron: :electron:

build: upgrade to Electron 9

---

src/renderer/components/settings-execution.tsx
src/renderer/npm.ts
src/renderer/runner.ts
src/renderer/state.ts
src/utils/exec.ts
tests/renderer/components/__snapshots__/settings-execution-spec.tsx.snap
tests/renderer/npm-spec.ts
tests/renderer/runner-spec.tsx

This PR adds the setting that gives the ability to change the default package manager from npm to Yarn and back.

feat: add ability to select package between npm and yarn

---

src/renderer/components/commands-publish-button.tsx

Fixes a potential edge case whereby if updating failed the state would not properly reset and so the Update/Publish button text would incorrectly read 'Updating'.
Also updates `wouldPublish` to `shouldPublish` to clarify intent.
cc @HashimotoYT @erickzhao

fix: move updating state out of try/catch

---

src/interfaces.ts
src/renderer/components/commands-action-button.tsx
src/renderer/components/commands-publish-button.tsx
src/renderer/components/commands.tsx
tests/renderer/components/__snapshots__/commands-spec.tsx.snap
tests/renderer/components/commands-publish-button-spec.tsx
tests/renderer/components/commands-spec.tsx

This PR adds the ability to delete gists that one has created previously.
New UI:

feat: add ability to delete gists

---

src/interfaces.ts
src/renderer/components/commands-bisect.tsx
src/renderer/state.ts
tests/renderer/components/commands-bisect-spec.tsx

feat: show a link to the comparison range on bisect complete

---

package-lock.json
package.json

chore: bump update-electron-app to 2.0.1

---

.github/workflows/build.yaml
package.json

Hotfix for https://electronhq.slack.com/archives/CB389B7MH/p1603438660031100
Created from 20c8f3461e6f4aa0e914c6c8f57464878e81e870

chore: release v0.17.2

---

src/interfaces.ts
src/ipc-events.ts
src/main/main.ts
src/main/menu.ts
src/renderer/components/settings-general-block-accelerators.tsx
src/renderer/components/settings-general.tsx
src/renderer/state.ts
tests/main/main-spec.ts
tests/main/menu-spec.ts
tests/renderer/components/__snapshots__/settings-general-spec.tsx.snap
tests/renderer/components/settings-general-block-accelerators.tsx
tests/renderer/components/settings-general-spec.tsx
tests/renderer/state-spec.ts

This is my attempt to solve making `CmdOrCtrl+S` and `CmdOrCtrl+Shift+S` toggleable.
closes issue #406

feat: make save hotkey toggleable

---

src/renderer/components/commands-action-button.tsx
tests/renderer/components/commands-publish-button-spec.tsx

Fixes #518 
This PR adds a cancel to the gist publish flow

feat: adds the ability to cancel publishing a gist

---

src/renderer/app.tsx
src/renderer/components/settings-general-appearance.tsx
src/renderer/state.ts
tests/mocks/app.ts
tests/mocks/state.ts
tests/renderer/app-spec.tsx
tests/renderer/components/__snapshots__/settings-general-appearance-spec.tsx.snap
tests/renderer/state-spec.ts

Supersedes #470, but doesn't require any use of the main process!

feat: system-synced dark mode (renderer-only)

---

.eslintrc.js
src/main/menu.ts
src/renderer/components/commands-runner.tsx
src/renderer/components/dialog-add-theme.tsx
src/renderer/components/editors-toolbar-button.tsx
src/renderer/components/settings-general-block-accelerators.tsx
src/renderer/constants.ts
tests/main/menu-spec.ts
tests/renderer/content-spec.ts
tests/utils/exec-spec.ts
tests/utils/focused-editor-spec.ts

Fixes the eslint config so it will actually run prettier now. All other changes outside of the config were automatic formatting fixes by eslint/prettier.

style: fix linting for formatting

---

src/renderer/components/commands-bisect.tsx
src/renderer/components/commands-version-chooser.tsx
src/renderer/components/dialog-bisect.tsx
src/renderer/runner.ts
src/renderer/state.ts
tests/renderer/components/__snapshots__/commands-version-chooser-spec.tsx.snap
tests/renderer/components/__snapshots__/dialog-bisect-spec.tsx.snap
tests/renderer/components/dialog-bisect-spec.tsx

Add an 'auto' button to the bisect dialog to invoke the autobisect feature.

feat: autobisect gui

---

src/main/windows.ts
tests/main/windows-spec.ts
tests/mocks/electron-fiddle.ts
tests/mocks/electron.ts

chore: disable remote module

---

src/renderer/components/output.tsx

Closes https://github.com/electron/fiddle/issues/649.

fix: onbeforeunload triggered for link click

---

src/renderer/binary.ts
src/renderer/state.ts
tests/renderer/binary-spec.ts
tests/renderer/state-spec.ts

Right now, whenever we create/update/delete a version, all the proxies in the `appState.versions` array are `toJS`'ed back into normal JS objects, thrown into a temporary container where the update happens, and then re-converted back into proxies again in a rebuilt `appState.versions` object.
This was necessary when the code was written because mobx 4 did not have support for reacting to properties being added/removed from observed objects. However this feature was [added in mobx 5](https://github.com/mobxjs/mobx/blob/e17c47833d1812eee6d77914be890aa41e4b7908/CHANGELOG.md#500) so this should "just work" without our code needing to rebuild the object.
Building the `versions` object once and then updating it instead of rebuilding it has some nice side-effects in other parts of the code. For …

refactor: only build `appState.versions` once

---

src/renderer/components/dialog-add-theme.tsx
tests/renderer/components/__snapshots__/dialog-add-theme-spec.tsx.snap
tests/renderer/components/dialog-add-theme-spec.tsx

This PR improves test coverage for `AddThemeDialog`, which was sorely lacking.

test: add test coverage for AddThemeDialog

---

src/renderer/runner.ts

Closes https://github.com/electron/fiddle/issues/660.
After:

fix: endless spin loop on module install failure

---

src/renderer/components/commands-action-button.tsx

Close https://github.com/electron/fiddle/issues/681

fix: gistFilesList() for customMosaics

---

src/less/components/settings.less
src/renderer/components/settings-execution.tsx
tests/renderer/components/__snapshots__/settings-execution-spec.tsx.snap
tests/renderer/components/settings-execution-spec.tsx

Refs https://github.com/electron/fiddle/pull/675#pullrequestreview-648760711.
This reworks the execution settings UI for execution flags and environment variables to something a bit more user-friendly.

feat: better execution settings UI

---

CONTRIBUTING.md

This PR adds clearer release instructions, as well as updating
minor details elsewhere in the document.

docs: better CONTRIBUTING docs

---

src/renderer/state.ts
tests/renderer/runner-spec.tsx

Refs https://github.com/electron/fiddle/pull/676
Closes https://github.com/electron/fiddle/issues/686.

fix: flushOutput not bound to 'this'

---

src/renderer/content.ts

As in title, just comment changes

chore: update master e/e to main

---

src/main/command-line.ts
src/main/protocol.ts

Closes https://github.com/electron/fiddle/issues/718.

fix: loading fiddle protocol from cli

---

src/renderer/components/version-select.tsx
tests/renderer/components/__snapshots__/version-select-spec.tsx.snap
tests/renderer/components/version-select-spec.tsx

Closes https://github.com/electron/fiddle/issues/726.
Something to note here is that it does slow down rendering perf a bit - i'd love yall to poke at it a bit and see if it's something you'd be bothered by.

feat: improve version filtration logic

---

src/main/command-line.ts
tests/main/command-line-spec.ts

`--full` is shorthand for `--betas --nighlies --obsolete`
A very short PR for a change!

feat: add --full command-line option

---

package.json

A little oopsie.
https://github.com/electron/fiddle/compare/v0.25.1...master

chore: v0.25.2

---

src/renderer/runner.ts

A small refactor. Separates the env-building code out from `Runner.execute()` into a new function `Runner.buildChildEnv()` so that both functions are more narrowly-focused

refactor: extract-method Runner.buildChildEnv

---

tests/renderer/app-spec.tsx

Tests only. No functional changes.
Part of a series of small refactors to reduce copy-paste that's built up over time in tests/.
This PR is for app-spec.

test: reduce copy-paste in app-spec

---

tests/renderer/runner-spec.tsx

Tests only. No functional changes.
Part of a series of small refactors to reduce copy-paste that's built up over time in tests/.
This PR is for runner-spec.

test: reduce copy-paste in runner-spec

---

tests/renderer/components/editor-spec.tsx

Tests only. No functional changes.
Part of a series of small refactors to reduce copy-paste that's built up over time in tests/.
This PR is for editor-spec.

test: reduce copy-paste in editor-spec

---

yarn.lock

Running the `yarn install` command on the current `trunk` gives me a bunch of lockfile updates. Seems like a follow-up to #813.

build(deps): yarn.lock update

---

static/show-me/ipc/index.html
static/show-me/ipc/main.js
static/show-me/ipc/preload.js
static/show-me/ipc/renderer.js

Also adds an example of invoke/handle.
Fixes #832.

fix(show-me/ipc): refactor to use current Electron security defaults

---

src/less/components/output.less

Refs https://github.com/electron/fiddle/pull/717.
After refactor:
Pre-refactor and post this PR:

fix: console css styles

---

static/electron-quick-start/index.html

Syncs [this change](https://github.com/electron/electron-quick-start/pull/492) from electron-quick-start.

chore: sync quick start index.html with external repo

---

src/less/components/settings.less
src/renderer/components/settings-electron.tsx
tests/renderer/components/__snapshots__/settings-electron-spec.tsx.snap

Closes https://github.com/electron/fiddle/issues/824.

fix: disable current version in version settings

---

package.json
yarn.lock

Was checking Sentry this morning and this came up.

build(deps): update Sentry SDK version

---

src/less/components/editors.less
src/main/devtools.ts
src/renderer/components/dialog-add-version.tsx
src/renderer/editor-mosaic.ts
src/utils/get-username.ts
src/utils/gist.ts
src/utils/highlight-text.tsx
tests/renderer/state-spec.ts

Fixes various typos in comments and strings, there should be no functional changes.

chore: fix typos

---

src/renderer/components/dialog-add-version.tsx

Fixes #778.
cc @ckerr, @erickzhao

fix: set version correctly when switching to a local version

---

yarn.lock

ref #913
Does the same thing without a selective dependency resolution

chore: improve macOS 12 support

---

src/renderer/runner.ts

Several of the docstrings in this file had gone stale, so updating them to be accurate.

chore: update docstrings in src/renderer/runner.ts

---

src/renderer/components/dialog-generic.tsx
tests/renderer/components/__snapshots__/dialog-generic-spec.tsx.snap
tests/renderer/components/dialog-generic-spec.tsx

Add listeners for enter submission

feat(dialog): improve user experience of input boxes

---

src/main/ipc.ts
src/renderer/app.tsx
src/renderer/binary.ts
src/renderer/components/editors.tsx
src/renderer/components/settings-electron.tsx
src/renderer/components/settings-execution.tsx
src/renderer/components/settings-general-appearance.tsx
src/renderer/components/settings-general-block-accelerators.tsx
src/renderer/components/settings-general-console.tsx
src/renderer/components/settings.tsx
src/renderer/components/tour.tsx
src/renderer/components/version-select.tsx
src/renderer/file-manager.ts
src/renderer/remote-loader.ts
src/renderer/state.ts
src/renderer/themes.ts
src/renderer/versions.ts
src/utils/get-package.ts
src/utils/gist.ts
src/utils/highlight-text.tsx
src/utils/octokit.ts
src/utils/position-for-rect.ts
src/utils/read-fiddle.ts
src/utils/sort-versions.ts

Did a pass over the whole codebase to update docstrings. Could use a close review, I went a bit cross-eyed by the end and might have made a mistake or two.

chore: update docstrings

---

src/renderer/components/settings-general-package-author.tsx
src/renderer/components/settings-general.tsx
src/renderer/state.ts
src/utils/get-package.ts
tests/mocks/state.ts
tests/renderer/components/__snapshots__/settings-general-package-author-spec.tsx.snap
tests/renderer/components/__snapshots__/settings-general-spec.tsx.snap
tests/renderer/components/settings-general-package-author-spec.tsx
tests/renderer/components/settings-general-spec.tsx
tests/utils/get-package-spec.ts
tools/contributors.js

close: #896
Preview Image:
Preview Gist URL:
https://gist.github.com/BlackHole1/e7f428532b78e59096ac73f617b29bab#file-package-json-L8
cc: @erickzhao

feat: support package.json author field

---

package.json

Another attempt, with more features now.

chore: v0.27.3 release

---

package.json
yarn.lock

Tested locally on Windows 10, everything looked fine, didn't notice anything broken. Tests pass.
@erickzhao, anything specific I should do to test this?

chore: update to Electron 15.3.7

---

README.md

link from: https://github.com/electron/electron/pull/31991

docs(readme): update Discord invite link

---

src/renderer/components/commands.tsx
tests/mocks/state.ts
tests/renderer/components/commands-spec.tsx

Related PR: https://github.com/electron/fiddle/pull/992

test: improve commands component test

---

.github/workflows/build.yaml

See: https://github.com/electron/fiddle/runs/5438013000?check_suite_focus=true#step:6:19

chore(ci): add yarn install retry logic

---

src/less/components/sidebar.less
src/renderer/components/editor.tsx
src/renderer/components/editors.tsx
src/renderer/components/sidebar-file-tree.tsx
src/renderer/editor-mosaic.ts
tests/renderer/components/__snapshots__/commands-spec.tsx.snap
tests/renderer/components/__snapshots__/sidebar-file-tree-spec.tsx.snap
tests/renderer/components/editor-spec.tsx
tests/renderer/components/editors-spec.tsx
tests/renderer/components/sidebar-file-tree-spec.tsx
tools/contributors.js

Closes https://github.com/electron/fiddle/issues/949

feat: Click the sidebar to activate the current file

---

src/renderer/components/commands.tsx

see: https://github.com/electron/fiddle/pull/1003 -> https://github.com/electron/fiddle/runs/5640270207?check_suite_focus=true#step:6:75
ref: https://github.com/electron/fiddle/pull/1012

fix: test failed on macOS system

---

.github/workflows/build.yaml

This PR dependency on https://github.com/electron/fiddle/pull/992 / #995 / https://github.com/electron/fiddle/pull/1004
Let's wait until they are merged first.

test: add Windows and macOS runner to test

---

package.json

chore: release v0.28.1

---

tools/contributors.js

feat: show all contributors with >= 2 contributions filtering out bots

---

src/renderer/components/commands.tsx
tests/renderer/components/__snapshots__/commands-spec.tsx.snap
tests/renderer/components/commands-spec.tsx

See:
1. https://github.com/electron/fiddle/pull/1019#discussion_r835103261
2. https://github.com/electron/fiddle/pull/1019#discussion_r835122725

refactor: improve different systems test snapshots

---

src/less/components/dialogs.less

fix: ensure preferences screen appears above versions filter

---

src/renderer/versions.ts

fix: not list available electron releases versions

---

tools/check-links.js

chore: exclude shields.io from lint check

---

src/less/main.less

Fixes #1084
See that issue for motivation and details.
cc @carolstran

fix: restore focus indicators

---

src/renderer/components/dialog-bisect.tsx
tests/renderer/components/__snapshots__/dialog-bisect-spec.tsx.snap
tests/renderer/components/dialog-bisect-spec.tsx

fix: join bisect page crash when electron version total < 11

---

package.json

chore: bump v0.29.2

---

package.json

Reverts commit edfcf3db557aa305d9fa372a64ce6d364f43adfc.

revert: bump v0.29.2 (#1135)

---

package.json

chore: release v0.29.2

---

src/renderer/components/version-select.tsx

fixed: https://github.com/electron/fiddle/issues/1145

fix: tooltip display incorrect in version-select

---

.lessrc

See: https://github.com/electron/fiddle/blob/b32884b4a4fd622ab138831b7a299e96459fce6d/tools/webpack/webpack.renderer.config.js#L35-L38

chore: remove .lessrc file

---

src/renderer/components/version-select.tsx

fixed: #1154
FixedSizeList subcomponents must be identical components.

fix: scrolling down in version-select dropdown

---

src/utils/electron-name.ts
src/utils/exec.ts
src/utils/get-name.ts
src/utils/get-username.ts
src/utils/gist.ts
src/utils/normalize-version.ts
src/utils/position-for-rect.ts
tests/utils/exec-spec.ts
tests/utils/gist-spec.ts

Improve readability and maintainability of code

refactor: improve utils code

---

src/renderer/components/commands-version-chooser.tsx

Closes https://github.com/electron/fiddle/issues/1161.

fix: prevent version switching while running

---

package.json

chore: release v0.31.0

---

src/renderer/runner.ts

Refs https://github.com/electron/fiddle/pull/1134.
Appropriately handle failure to spawn the runner.

fix: catch FiddleRunner spawn error

---

src/renderer/state.ts

As discussed within - https://github.com/electron/fiddle/pull/1134#discussion_r948317683
This should no longer come under the "TODO" task :)

refactor: remove stale comment

---

src/renderer/components/settings-electron.tsx
tests/renderer/components/__snapshots__/settings-electron-spec.tsx.snap

feat: Add filter section for "not-downloaded" button

---

src/renderer/file-manager.ts

Close: https://github.com/electron/fiddle/issues/1212

refactor: add prefix for tmp folder name

---

src/renderer/components/commands-action-button.tsx
tests/renderer/components/commands-publish-button-spec.tsx

fix: don't clear editor is edited state if Gist publish fails

---

.github/semantic.yml

ci: remove unused GitHub app config file

---

package.json

This PR requires admin merge due to stalling macOS build jobs.

chore: release v0.32.1

---

src/renderer/components/commands.tsx
tests/renderer/components/commands-spec.tsx

Closes https://github.com/electron/fiddle/issues/1246.

fix: overzealous window maximize on double-click

---

src/renderer/remote-loader.ts
tests/renderer/remote-loader-spec.ts

Closes https://github.com/electron/fiddle/issues/1173.

fix: loading an invalid version from gist `package.json`

---

src/ambient-modules.d.ts

chore: remove unused ambient-modules.d.ts

---

.github/workflows/build.yaml
yarn.lock

Dogfood the latest Forge, and drop the workaround we put into place on CI.

build: update to Forge 6.0.5

---

.github/CODEOWNERS

chore: add @codebytere as CODEOWNER

---

src/renderer/app.tsx
tests/renderer/app-spec.tsx

#1292 and #1295 collided, so cleaning that up.

chore: fix build after PR collision

---

src/renderer/components/dialog-add-version.tsx
src/renderer/state.ts
src/renderer/versions.ts
src/utils/disable-download.ts

chore: tidy up some types

---

src/renderer/components/settings-general-appearance.tsx

chore: fix code comment

---

package.json
yarn.lock

No functional changes, but need to pick up some of the new features for future refactoring so doing that now for smaller future diffs.

build(deps): update @electron/fiddle-core

---

package.json

chore: release v0.32.3

---

package.json
yarn.lock

Picks up fixes in `@electron/fiddle-core` which will fix some Sentry errors.

fix: upgrade to @electron/fiddle-core@1.2.2

---

tests/main/main-spec.ts
tests/main/menu-spec.ts
tests/main/themes-spec.ts
tests/renderer/components/__snapshots__/dialog-generic-spec.tsx.snap
tests/renderer/components/dialog-generic-spec.tsx
tests/renderer/components/dialog-token-spec.tsx
tests/renderer/components/dialogs-spec.tsx
tests/renderer/versions-spec.ts
tests/utils/check-first-run-spec.ts

test: cleanup duplicate name tests

---

tests/main/first-run-spec.ts
tests/main/main-spec.ts
tests/utils/exec-spec.ts

test: use overridePlatform util

---

package.json

chore: release v0.32.6

---

package.json

chore: release v0.32.7

---

package.json

Hot fix release for loading gists.

chore: release v0.32.8

---

package.json

Another hot fix, since #1371 seems to be affecting a lot of users.

chore: release v0.32.9

---

src/main/themes.ts
src/main/windows.ts
src/renderer/components/dialog-add-theme.tsx
src/renderer/components/dialog-add-version.tsx
src/renderer/state.ts
src/renderer/utils/editor-utils.ts

Just some clean up, most of these build cleanly with no other changes.

chore: clean up use of any typings

---

package.json

chore: release v0.33.0

---

src/preload/preload.ts

fix: check show me template in menu

---

forge.config.ts

Need to switch over by Nov 1, 2023.

build: use notarytool

---

tsconfig.json

build: add rtl-spec/ to tsconfig.json

---

src/main/dialogs.ts
src/main/ipc.ts
src/main/main.ts
src/main/protocol.ts
src/main/windows.ts
tests/main/files-spec.ts
tests/main/ipc-spec.ts
tests/main/main-spec.ts
tests/main/protocol-spec.ts
tests/main/windows-spec.ts

fix: don't open window before main process is ready

---

package.json

chore: release v0.34.0

---

jest.config.ts

Follow-up to #1432 because I missed [this comment](https://github.com/electron/fiddle/pull/1432#issuecomment-1665090931) 😅

test: convert the Jest configuration to Typescript

---

package.json
yarn.lock

build(deps): update Forge to 6.3.0

---

package.json
yarn.lock

build(deps): upgrade @sentry/electron to 4.10.0

---

package.json
yarn.lock

build(deps): update Forge to 6.4.1

---

src/ambient.d.ts
src/ipc-events.ts
src/main/files.ts
src/main/npm.ts
src/preload/preload.ts
src/renderer/runner.ts
tests/mocks/electron-fiddle.ts
tests/renderer/runner-spec.tsx

refactor: move usage of node:path to main process

---

package.json

chore: release v0.34.1

---

package.json

chore: release v0.34.2

---

package.json

chore: release v0.34.3

---

static/show-me/shell/index.html
static/show-me/shell/main.js
static/show-me/shell/preload.js

Closes https://github.com/electron/fiddle/issues/1490.
Handles sandbox change in v20

fix: show-me shell example

---

static/electron-quick-start/main.js

Refs https://github.com/electron/electron-quick-start/pull/853.

chore: sync electron-quick-start content with upstream

---

.circleci/config.yml

This slipped in as part of #1498 but I don't think we want it here.

ci: remove branch filter

---

package.json

chore: release v0.35.0

---

package.json

chore: release v0.35.1

---

package.json
yarn.lock

build(deps): update Forge to 7.2.0

---

static/show-me/ipc/main.js
static/show-me/screen/main.js

chore: fix typos in show me examples

---

forge.config.ts

Refs https://github.com/electron/packager/pull/1597

build: remove notaryTool usage

---

package.json

chore: release v0.36.0

---

static/show-me/tray/main.js

Changed import from 'electron.main' to 'electron/main'.

fix(show-me/tray): correct import

---

package.json
yarn.lock

build(deps): update Forge to 7.3.1

---

package.json

chore: release v0.36.1

---

yarn.lock

build: bump electron-winstaller

---

package.json
yarn.lock

chore: update to Electron 30.0.1

---

package.json

Nothing too interesting to release here, just want to keep on the latest Electron stable.

chore: release v0.36.3

---

package.json
yarn.lock

`valid-url` was removed in #717 but `@types/valid-url` was missed.

build: remove unused @types/valid-url

---

.husky/pre-commit
package.json
yarn.lock

build: update husky and lint-staged

---

package.json
yarn.lock

Keeping up with the Electrons. :electron:

chore: update to Electron 31.1.0

---

src/main/dialogs.ts
src/main/files.ts
src/main/menu.ts
tests/main/dialogs-spec.ts
tests/main/files-spec.ts
tests/main/menu-spec.ts

fix: set parent window for open/save dialogs

---

package.json

Bump to Electron 31 and a minor fix or two.

chore: release v0.36.4

---

package.json
yarn.lock

Dogfooding the latest and greatest.

build(dev-deps): update to Forge 7.6.0

---

package.json

Bump to Electron 33 and some fixes for themes.

chore: release v0.36.5

---

yarn.lock

build(dev-deps): update express to partially clear audit

---

package.json

A few fixes which would be good to get out.

chore: release v0.36.6

---

package.json
yarn.lock

Follow-up to #1709 to pick up a fix to ensure the scripts actually run. 😓

build(dev-deps): update @electron/lint-roller to 3.1.1

---

package.json
src/main/main.ts
yarn.lock

Now that Devtron is being revived, let's use it here. 🙂

chore: add Devtron in development mode

---

forge.config.ts
package.json
yarn.lock

We're going to do a new Fiddle release and use the opportunity to validate this E2E.

build: use the node22 branch of @electron/windows-sign

---

package.json

chore: release 0.37.0

---

package.json

Third time's the charm. :shipit:

chore: release 0.37.2
