electron/fiddle

- src/renderer/app.tsx
- src/renderer/components/output.tsx
- src/renderer/components/version-chooser.tsx
- src/renderer/fetch-types.ts
As you switch versions in the dropdown, we'll magically ✨update the editor with TypeScript definition files for the chosen version of Electron.
That means that the editor will auto-complete Electron-related code <3
> Add TypeScript definitions for Electron

- src/renderer/app.tsx
- src/renderer/components/commands.tsx
- src/renderer/components/header.tsx
- src/renderer/components/output.tsx
- src/renderer/components/token-dialog.tsx
- static/css/main.css
This PR adds an auth button to the right of the terminal, which opens a very ugly dialog with a link to `https://github.com/settings/tokens/new?scopes=gist&description=Fiddle%20Gist%20Token` and an input field. The input field can't be typed into, but when it receives focus we'll automatically paste the token using the `clipboard` module.
> Rough draft: Accept a GitHub Gist token

- src/renderer/components/settings-credits.tsx
- tools/fetch-contributors.js
After discussion with the team it was decided that the copy should be changed - and that the credits screen should only display those who want to be publicly recognized.
> Whitelist for credits view, new copy

- src/renderer/binary.ts
- src/renderer/state.ts
Currently on first run (or running after deleting `~/Application Support/electron-fiddle`) the first electron version download is never reflected in the app.
At the moment `new BinaryManager` is responsible for downloading the first version of electron, which happens in a way `AppState` isn't aware of. A second call to `downloadVersion`, initiated by `AppState` does happen, but at the moment it resolves early as "already being downloaded". By removing the `new BinaryManager` side-effect, everything works as expected.
> Fix first electron version install

- src/interfaces.ts
- src/renderer/file-manager.ts
This PR adds a `FileTransform` type, allowing us to make it a bit easier to apply all kinds of transforms to a Fiddle - for instance saving as a `electron-forge` or an `electron-builder` project 🎉
> feat: File transforms

- src/utils/exec.ts
`exec` always returns a string, there's no need to call `toString()`.
> fix: exec `toString` test issue

- src/main/menu.ts
"Save as Forge Project" dialog title was incorrect.
"Save as" dialog title had `[Object BrowserWindow]` appended to it.
> fix: save as dialog titles

- src/main/context-menu.ts
- src/renderer/components/settings.tsx
- src/renderer/components/tour-welcome.tsx
- src/renderer/state.ts
- tests/main/context-menu-spec.ts
Little catch-all PR that fixes three distinct bugs:
- A typo in the welcome tour found by @malept 
- Broken settings toggle, also found by @malept 
- The context menu showing monaco elements when it shouldn't
> fix: Settings toggle, context menu init, and a typo

- README.md
- src/renderer/components/appveyor.yml
This PR enables tests on AppVeyor, ensuring that we cover all three operating systems with our unit tests. It also adds testing badges to the README.
> test: Add AppVeyor, Readme badges

- src/renderer/components/runner.tsx
- src/renderer/file-manager.ts
- tests/mocks/app.ts
- tests/mocks/file-manager.ts
- tests/renderer/file-manager-spec.ts
- tools/contributors.js
This PR does two things:
• When we can't run a fiddle because the current Electron version hasn't been downloaded yet, we call that out in the console.
• If contributors.json can't be fetched during development, we're cool with that.
> feat: Support being offline better

- src/utils/position-for-rect.ts
- tests/renderer/components/tour-spec.tsx
- tests/utils/position-for-rect-spec.ts
The automatic dialog positioning would take the macOS-only header into account, which broke the position on Windows and Linux. This fixes that (and tests the fix).
> fix: Dialog position on Linux and Windows

- src/renderer/components/runner.tsx
- src/renderer/transforms/forge.ts
- tests/renderer/components/runner-spec.tsx
- tests/transforms/forge-spec.ts
Installing `latest` has unwelcome side effects (mostly, that we're installing older versions). Let's go with the `beta` for now, it does enough for us here.
> fix: Install beta.22 of Fiddle

- src/utils/exec.ts
Previously, we only used `fix-path` on macOS, but we should really use it on Unix in general.
Closes #68
> fix: Path on Linux, too

- src/less/mosaic.less
Refs #61 
After analyzing the details & suggestions in #61 & inspecting the `.mosaic-window-body` element's styles, this PR attempts to simply adjust the styles to resolve the observation in #61.
* add padding top allowance to support a visible tooltip on any variable on code line 1
* adjust font-size to 12px; local test seems to look okay.
Happy to update to any suggested styles to make the UI look nice. 🙏 for your review in advance.
> fix: Adjust .mosaic-window-body styles

- src/content/main-1-x-x.ts
- src/renderer/app.tsx
- src/renderer/components/editor.tsx
- src/renderer/components/editors.tsx
- src/renderer/content.ts
- src/renderer/state.ts
- src/utils/get-package.ts
- tests/renderer/content-spec.ts
⚠️ This PR isn't as good as I'd like it to be, but it'll be good enough for now.
This PR enables a more flexible quick start. If you switch to a `v1.x` version, we'll use `loadURL`. If you switch to an Electron version that supports `loadFile`, we'll use `loadFile`. That change doesn't happen if you changed your main script so that we don't touch a user's code.
> feat: Make quick start flexible

- tools/contributors.js
Per #78 , reviewer is kind enough to invite to add to self to the contributor list. Therefore, this PR simply adds my GitHub handle to the list. It's an honor. Will look out for issues to try to help out. 🙏
> refactor: add contributor pre a previous PR

- src/less/mosaic.less
Refs #61 
I tested the current build more and found some style nuance.
I dug a little more to attempt to improve the tooltip styles further. The PR is able to:
* shorter the top padding space to make the draggable toolbar not as consuming as much height
* in viewport with narrow width, tested two use cases of right clicking and hovering to see tooltip.
> fix: Update mosaic less to improve tooltip styles

- src/renderer/content.ts
- tests/renderer/content-spec.ts
Some operations _can_ run before the Monaco editor has fully loaded. This guards against an error in `isContentUnchanged()`.
> fix: Prevent error in isContentUnchanged

- README.md
The main page's
**"Download Electron Fiddle for macOS, Windows, and Linux"**
link still points to 0.1.
I was showing Fiddle to an Electron user today and we were both confused for a bit why we couldn't find 0.2 :smiley:
> fix: don't pin download link to 0.1 tag

- src/content/main.ts
`path` and `url` are no longer used here since `index.html` is loaded via `loadFile`. 
This PR thus removes them.
/cc @felixrieseberg
> chore: remove unused requires in main

- src/renderer/components/tour-welcome.tsx
- tests/renderer/components/__snapshots__/tour-welcome-spec.tsx.snap
- tests/utils/sorted-electron-map-spec.ts
In general I like it when buttons are labeled with what's going to happen when I click on them
> fix: friendlier button text for intro tour

- forge.config.js
Now that #118 is merged, there's a stable URL for the new icon that `electron-winstaller` can use.
> chore: update windows installer icon

- src/less/components/commands.less
- src/renderer/components/commands-publish-button.tsx
- src/renderer/state.ts
- tests/renderer/components/__snapshots__/commands-publish-button-spec.tsx.snap
- tests/renderer/components/commands-publish-button-spec.tsx
This feature is best explained with an image:
Closes https://github.com/electron/fiddle/issues/99
> feat: Publish fiddles as public/private

- forge.config.js
Per https://github.com/electron/fiddle/pull/120#discussion_r242381413 _(view without whitespace changes to see a better diff)_
If Sam ends up doing https://github.com/electron/fiddle/pull/120#discussion_r242381665 we can change when we upgrade Forge.
> chore: automatically add arch to squirrel installer filename

- src/interfaces.ts
- src/renderer/app.tsx
- src/renderer/components/commands-address-bar.tsx
- src/renderer/components/dialog-warning.tsx
- src/renderer/components/dialogs.tsx
- src/renderer/components/editors.tsx
- src/renderer/file-manager.ts
- src/renderer/state.ts
- tests/renderer/components/__snapshots__/dialogs-spec.tsx.snap
- tests/renderer/components/commands-address-bar-spec.tsx
- tests/renderer/components/dialogs-spec.tsx
- tests/renderer/file-manager-spec.ts
The dialog that warns users before getting rid of an unsaved dialog isn't the best part of Fiddle. This PR makes things a bit more clear – and the dialog a bit nicer.
This also fixes a small issue with our `beforeunload` handling, which didn't quite work before.
> fix: Confusing "Fiddle unsaved" dialog

- appveyor.yml
Walking further down the path of enabling a Fiddle release from a phone, if need be: This PR enables AppVeyor to create signed builds.
> ci: Allow AppVeyor to codesign

- appveyor.yml
- forge.config.js
The way we were looking for a certificate file wasn't quite correct. This fixes that.
> ci: Properly find Windows codesign certificate

- src/renderer/binary.ts
- src/renderer/components/commands-runner.tsx
- src/renderer/state.ts
- src/renderer/versions.ts
- tests/renderer/components/__snapshots__/commands-runner-spec.tsx.snap
- tests/renderer/components/commands-runner-spec.tsx
This PR fixed #147. There were three different issues:
1) If the current version state is unknown, we didn't display any run button. We now display a loading indicator.
2) We selected Electron 0.1 by default (instead of the latest known version)
3) A previous failed unzip operation in the binary manager would silently fail with `EEXIST`
> fix: Ensure correct version selection & display

- src/less/components/output.less
- src/renderer/components/chrome-mac.tsx
- tests/mocks/electron.ts
- tests/renderer/components/__snapshots__/chrome-mac-spec.tsx.snap
- tests/renderer/components/chrome-mac-spec.tsx
* Implements the native double-click behavior on our custom title bar
* Fixes the animation of the console opening / closing
> feat: support double click action on custom mac window title

- package-lock.json
- package.json
Forge v6 beta 32 has an updated Electron Packager and `electron-installer-*` modules. Offhand, there are two things that are relevant to Fiddle:
* Linux packages no longer include a dependency on `GConf` (dropped in Electron 3)
* macOS notarize support
> chore: update Electron Forge to 6.0.0-beta.32

- src/renderer/components/commands-address-bar.tsx
Fixes #167 - we previously didn't commit the address bar value to the app's state until a `<form>` submit.
> fix: Correctly load Fiddle without form submit

- src/renderer/components/commands-version-chooser.tsx
- src/renderer/components/settings-electron.tsx
- src/renderer/state.ts
- tests/renderer/components/__snapshots__/commands-version-chooser-spec.tsx.snap
- tests/renderer/components/__snapshots__/settings-electron-spec.tsx.snap
- tests/renderer/components/commands-version-chooser-spec.tsx
- tests/renderer/components/settings-electron-spec.tsx
This implements #158. In short, it allows users to specify whether or not to display versions that have been downloaded, are downloading, or haven't been downloaded yet.
> feat: Display only Electron versions with a certain state

- tools/contributors.js
- tools/run-bin.js
- tools/tsc.js
Turns out, CI doesn’t correctly fetch contributors if the GitHub API is rate-limited. As you can guess, that’s always the case for Travis.
This has `contributors.js` use environment variables to fetch contributors if they are available.
> fix: Allow contributors.js to use GitHub credentials

- src/less/root.less
- src/renderer/components/settings-execution.tsx
- src/renderer/runner.ts
- src/renderer/state.ts
- tests/renderer/components/__snapshots__/settings-execution-spec.tsx.snap
- tests/renderer/components/settings-execution-spec.tsx
- tests/renderer/runner-spec.tsx
Adds an option that sets `ELECTRON_ENABLE_LOGGING` to help when debugging local electron builds
> feat: add an execution toggle to enable advanced electron logging

- src/renderer/transforms/forge.ts
- tests/transforms/forge-spec.ts
> fix: use the latest version of Forge v6 for Fiddle Forge actions

- src/ipc-events.ts
- src/main/ipc.ts
- src/main/protocol.ts
- src/renderer/app.tsx
- src/renderer/components/commands-address-bar.tsx
- tests/main/files-spec.ts
- tests/main/ipc-spec.ts
- tests/main/protocol-spec.ts
This adds support for actually handling the protocol launch requests we receive on the `electron-fiddle://` protocol.
E.g. 
* electron-fiddle://gist/c89aa0037c3da114d44aa3a2d1a0fc24
* electron-fiddle://gist/MarshallOfSound/c89aa0037c3da114d44aa3a2d1a0fc24
In the future I intend to add support for:
* electron-fiddle://electron/master/docs/fiddles/app-ready
In order to load a "fiddle" from the Electron docs.
> feat: add wiring for protocol launching gists

- src/main/main.ts
- src/utils/set-about-panel.ts
- tests/main/main-spec.ts
Resolves https://github.com/electron/fiddle/issues/188.
Adds more information to the About panel on macOS and Linux, including the Electron version being used. @felixrieseberg I wasn't sure what you'd like to put for copyright, so i put `Electron Authors` for now but if there's something else you'd prefer I can use that instead!
new panel on macOS:
> feat: add more information to about panel

- src/utils/set-about-panel.ts
Turns out, `setAboutPanelOptions` doesn't work on Windows, so we're crashing there 🙈 
fixes #210
> fix: Don't attempt to set about panel on Windows

- tests/setup.js
Some of our tests accidentally trigger a version change, thus triggering the automatic download of whatever Electron version was selected.
Sure, we could go in and with hours of work find how exactly that happens, but we can also just mock away `electron-download` 😛
> test: Mock electron-download

- static/show-me/touchbar/main.js
Fixes the touch bar Show Me example; the one in play now no longer works in > v5 as a result of a change in the Touch Bar constructor. This thus changes that to use a constructor that works for all supported versions.
cc @MarshallOfSound @felixrieseberg
> fix: correct touch bar constructor in example

- tools/contributors.js
A PR from non-maintainers would always fail the Travis CI build, since the build is untrusted and the request for contributors would automatically reach the rate limit (Travis CI is always at the rate limit).
This ensures that only trusted builds actually throw.
cc @codebytere @DeerMichel
> build: Don't throw if missing contributors in PR

- src/renderer/components/tour-welcome.tsx
Adds spaces to the tour experience where they were missing.
_another option would be to add `{' '}` directly if desired; this could be done in place of the spaces added or on the line above as needed._
issue that this resolves:
> adds missing spaces

- static/show-me/browserwindow/index.html
Little fix so that the button in the `BrowserWindow` show-me does what the code seemed like it was supposed to do. Upon clicking the `Close this window` button, the window will close! ✨
> fix: correct button code for BrowserWindow show-me

- forge.config.js
We released 0.9 as a pre-release, meaning that the auto-update didn't actually go out. This'll fix that 🙈
> build: Don't mark releases as prereleases

- src/main/protocol.ts
Adds support for dev mode for the Protocol Launch feature. Allows you to add the protocol URL as an arg to your `npm start command`.
Example:
```
npm start -- electron-fiddle://electron/fiddle-in-docs/docs/fiddles/single-instance
```
> feat: add dev mode support for protocol

- src/renderer/components/commands-address-bar.tsx
This PR adds a more verbose warning message when trying to load a fiddle while computer is offline.
> chore: add offline notice when loading fiddles

- src/less/components/output.less
- src/renderer/app.tsx
- src/renderer/components/header.tsx
- src/renderer/components/output-editors-wrapper.tsx
- src/renderer/components/output.tsx
- tests/mocks/state.ts
- tests/renderer/app-spec.tsx
- tests/renderer/components/__snapshots__/header-spec.tsx.snap
- tests/renderer/components/__snapshots__/output-spec.tsx.snap
- tests/renderer/components/output-spec.tsx
- tests/renderer/state-spec.ts
- tools/contributors.js
Closes #215.
Adds a `react-mosaic-component` wrapper around the `Editors` and the `Output` components so that you can drag and resize.
Due to this resizing fix, the functionality of the console show/hide button had to be refactored as well. Note that pressing show/hide now does not have an animation. Moreover, showing the hidden console will always revert to its default size.
cc @felixrieseberg @codebytere @DeerMichel
> feat: console resizing

- src/renderer/components/dialog-confirm.tsx
- src/renderer/components/dialog-warning.tsx
- src/renderer/remote-loader.ts
- src/renderer/state.ts
- tests/renderer/components/commands-address-bar-spec.tsx
- tests/renderer/components/dialog-warning-spec.tsx
- tests/renderer/remote-loader-spec.ts
- tests/renderer/state-spec.ts
Tiny nit where we were calling a bunch of variables `toogle` rather than `toggle` in the code. Will make toggles easier to search for 👀
> chore: `toogle` -> `toggle`

- src/renderer/components/editor.tsx
- src/renderer/components/editors.tsx
- tests/renderer/components/editor-spec.tsx
Fixes a typo so that we can search through the code easier. :)
cc @felixrieseberg @malept
> chore: 'monoaco' -> 'monaco'

- src/renderer/components/editor.tsx
- tests/renderer/components/editor-spec.tsx
Fixes #161.
Previously, when instantiating the Monaco Editor's language model, we did not set any explicit parameters. It just determined them based on the initial values of the editor contents and the language.
My guess is that since `renderer.js` didn't have any 2-indented code, it defaulted to 4-tab.
https://github.com/electron/fiddle/blob/7d19ad91a66c6f40daf0a1277b3c9cfcbb71fe80/src/renderer/components/editor.tsx#L122-L124
This PR just sets it to 2 spaces.
> fix: enforce 2-space indents in all editors

- src/renderer/app.tsx
- tests/renderer/app-spec.tsx
Fixes #180.
Previously, the code would avoid overwriting the editor file with `editor.setValue()` if `values[name]` was falsy. However, since `Boolean('')` evaluates to false, empty strings would not be set.
This solves an edge case with Saved Fiddles with missing files or Show Me's that didn't require all 3 files.
> fix: load empty files upon opening a fiddle

- src/less/mosaic-vendor.less
Currently, some styling leads to the Monaco editor's IntelliSense being hidden if it would overflow the window.
Screenshot:
I pinpointed the root cause of the problem to `.mosaic-preview` in our own `src/less/mosaic-vendor.less` file, which sets `overflow: hidden`.
Looking at the original vendor styling ([link](https://github.com/nomcopter/react-mosaic/blob/master/styles/mosaic.less)), it seems like they're not setting any `overflow` anywhere, so it seems to be on our end.
Since this vendor `.less` file was originally added in PR #14 to improve FPS, I wanted to test if removing the rule would cause a regression in the scrolling FPS:
1. [Screen capture with `overflow: hidden`](https://youtu.be/3rh7_CAjEfY)
2. [Screen capture without](https://youtu.be/wdrRkNfyU6k)
There doesn't seem to be …
> fix: adjust styling to avoid hiding IntelliSense popups

- src/renderer/fetch-types.ts
- src/renderer/state.ts
- tests/renderer/app-spec.tsx
- tests/renderer/binary-spec.ts
- tests/renderer/components/settings-spec.tsx
- tests/renderer/fetch-types-spec.ts
This PR adds IntelliSense for local versions of Electron by loading and watching the `electron.d.ts` file generated by the local build. By using `fs.watch`, the definitions will be renewed whenever they are updated locally.
Since the TypeScript definitions are generated from documentation, changes to the IntelliSense will only be reflected upon modifying the documentation locally and rebuilding.
> feat: intellisense for local builds

- src/renderer/components/output-editors-wrapper.tsx
- src/renderer/components/output.tsx
- tests/renderer/components/output-spec.tsx
This PR fixes small issues with the new resizable console.
1) The button doesn't correctly reflect whether or not the console is visible. That's fixed.
2) The button "forgets" the previous size.
3) The console is visible, even if it's not supposed to be visible (it's just small).
4) We don't display the first line (I think that's an older bug)
> fix: Console button / display issues

- src/interfaces.ts
- src/renderer/app.tsx
- src/renderer/binary.ts
- src/renderer/components/commands-publish-button.tsx
- src/renderer/components/editors.tsx
- src/renderer/content.ts
- src/renderer/file-manager.ts
- src/renderer/remote-loader.ts
- src/renderer/runner.ts
- src/renderer/state.ts
- tests/mocks/app.ts
- tests/mocks/file-manager.ts
- tests/renderer/app-spec.tsx
- tests/renderer/components/commands-publish-button-spec.tsx
- tests/renderer/components/editors-spec.tsx
- tests/renderer/content-spec.ts
- tests/renderer/file-manager-spec.ts
- tests/renderer/remote-loader-spec.ts
- tests/renderer/state-spec.ts
Fixes #251 by refactoring the prompt logic.
Previously, ancillary state variables for a Fiddle (`gistId`, `filePath`, `templateName`) were being reset even if a user cancelled the loading via a prompt.
_Note: The LoC setting these variables simply could have been moved such that they were blocked by a prompt cancellation. However, I noticed that I had to do this many times in the code, so it seemed like a code smell._
* Renamed functions to make purpose clearer:
* `app.setValues() -> app.setEditorValues()`
* `app.getValues() -> app.getEditorValues()`
* Added a new `replaceFiddle()` function:
* **Purpose:** to have a DRY abstraction for replacing the existing Fiddle with a new one.
* **Motivation:** Previously, local Fiddles, show-mes, Gists, and Fiddle Protocols each had their own loading …
> fix: ensure state consistency when loading an external Fiddle

- src/interfaces.ts
- src/renderer/app.tsx
- src/renderer/components/editors.tsx
- src/renderer/file-manager.ts
- src/renderer/remote-loader.ts
- src/renderer/templates.ts
- src/shared-constants.ts
- src/utils/editor-layout.ts
- tests/renderer/app-spec.tsx
- tests/renderer/components/__snapshots__/commands-editors-spec.tsx.snap
- tests/renderer/components/__snapshots__/editors-spec.tsx.snap
- tests/renderer/file-manager-spec.ts
- tests/renderer/npm-spec.ts
- tests/renderer/remote-loader-spec.ts
- tests/renderer/runner-spec.tsx
- tests/renderer/templates-spec.ts
- tests/utils/editors-mosaic-arrangement-spec.ts
- tests/utils/get-package-spec.ts
This PR enables support for a `preload.js` file. The panel isn't open by default, but if you click on the `Editors` button, you can enable it. 
To make things smoother, I've also added one more change:  If a file is empty, we don't write it to disk or upload to gist. Accordingly, if a gist doesn't contain a file, we assume that it's empty.
> feat: Enable support for a `preload.js`

- src/renderer/components/tour-welcome.tsx
- tests/renderer/components/__snapshots__/tour-welcome-spec.tsx.snap
The fiddle tour had missing spaces in the modal for main window and HTML window. Also, the snapshots are updated to make sure this passes the tests. Fixes #235.
> fix: Inserted whitespace in tour

- src/renderer/npm.ts
This PR updates the 'require' regex to match the whole line for a module require:
Before:
`const y = require('yargs')` returns:
* `match[0]` = `require('yargs')`
* `match[1]` = `yargs`
After:
`const y = require('yargs')` returns:
* `match[0]` = `const y = require('yargs')`
* `match[1]` = `yargs`
This allows us to add an extra conditional to the loop to ensure that if a given module is commented out:
```js
// const y = require('yargs')
```
that this logic won't install it anyway.
cc @felixrieseberg
> fix: don't install commented-out requires

- static/show-me/dialog/main.js
Fixes the dialog example - `showOpenDialog` now returns a Promise in supported versions so we should likely be using that. The previous example would not properly load the chosen file. 
cc @felixrieseberg
> fix: update dialog example for promisification

- src/main/main.ts
- tests/mocks/electron.ts
Removes the deprecated `app.setName()` API (https://electronjs.org/docs/api/app#appsetnamename).
Instead overwrites app name by setting `app.name` property.
> refactor: update deprecated app.setName API

- package-lock.json
- src/main/devtools.ts
- tests/main/devtools-spec.ts
- tests/utils/devmode-spec.ts
Closes #276 
isDevMode is of function type but used as boolean.
Fix devtools-spec.ts for not calling isDevMode
> fix: ensure dev tools only open in dev mode

- src/less/components/commands.less
This code was introduced in #257 and seems to have broken popovers and dropdowns. I don't believe it's actually required, I ran some bisect operations without it and things worked fine.
> fix: Incorrect dropdowns

- src/renderer/components/settings-execution.tsx
- src/renderer/runner.ts
- src/renderer/state.ts
- tests/renderer/components/__snapshots__/settings-execution-spec.tsx.snap
- tests/renderer/components/settings-execution-spec.tsx
This PR allows users to add custom [cli flags](https://electronjs.org/docs/api/chrome-command-line-switches) supported by Electron to settings, where they will be passed to Fiddle execution. This would enable helpful functionality like garbage collection exposure on the global object, so that users could e.g. call `gc()` within their Fiddles.
New UI:
> feat: allow users to specify cli flags

- jest.json
Be more specific for the `ts-jest` transform, to avoid errors [like these](https://travis-ci.org/electron/fiddle/jobs/624313335#L623):
> `ts-jest[jest-transformer]` (WARN) Got a unknown file type to compile (file: `fiddle/static/releases.json`). To fix this, in your Jest config change the `transform` key which value is `ts-jest` so that it does not match this kind of files anymore.
> test: avoid transforming JSON files

- src/renderer/app.tsx
- src/renderer/components/commands-publish-button.tsx
- src/renderer/components/tour-welcome.tsx
- tests/mocks/app.ts
- tests/renderer/components/__snapshots__/tour-welcome-spec.tsx.snap
- tests/renderer/components/commands-publish-button-spec.tsx
- tests/renderer/file-manager-spec.ts
Addresses #284.
This does not address loading preload scripts - they load, but only if the preload pane is loaded at least once beforehand.
Also updates some docs/help text that don't take into account the new preload editor pane.
> feat: publish preload scripts to GitHub gists

- src/renderer/app.tsx
- src/renderer/components/editor.tsx
- src/renderer/constants.ts
- src/renderer/state.ts
- src/utils/editor-backup.ts
- tests/renderer/app-spec.tsx
- tests/renderer/components/editor-spec.tsx
When loading a Fiddle that contains a `preload` file, we didn't correctly load that content unless the user has previously opened the preload editor. The underlying cause was that we didn't create an initial text model for that editor, so we didn't have a place to store that value.
Closes #284
> fix: Create initial backup for preload editor

- static/show-me/autoupdater/main.js
Removes a confusing extra event listener to `update-available` from the `autoUpdater` example
> chore: fix autoUpdater example to remove spurious event. Fixes #283

- src/renderer/npm.ts
- tests/renderer/npm-spec.ts
Fixes #231
This PR adds `original-fs` to this list of ignored modules (as it's exposed by electron).
> fix: Add original-fs to ignored modules

- src/renderer/remote-loader.ts
- tests/renderer/remote-loader-spec.ts
Fixes #262.
Make example warning more descriptive by adding path, remove repeated text. 
* We may want to preflight the gist so we can tell the user the author name, at the moment we just say 'gist'
* The string replace to pretty up the example name is a bit weak, but the code is currently written to allow us to point to directories outside the fiddle directory. If we want to ban this all together I'm happy to catch it on the protocol handler side, only sending the pretty name to the app, which reconstructs the path later.
* Words are hard.
> fix: Make example warning more descriptive

- static/show-me/ipc/renderer.js
The event listener in `ipcRenderer.on()` is an arrow function with the parameters `event` and `...args`.
In this show-me, we were supposed to print `"pong"`, but ended up printing `[event, "pong"]` because we were using the rest parameter `...args` at the wrong level.
> fix: print correct output in ipcRenderer show-me

- src/content/main.ts
`BrowserWindow` objects keep themselves referenced at least as long as the window isn't closed, so there's no need to hold a reference to the main window.
> feat: stop holding a reference to mainWindow

- src/content/main-1-x-x.ts
- static/show-me/clipboard/main.js
- static/show-me/cookies/main.js
- static/show-me/crashreporter/main.js
- static/show-me/debugger/main.js
- static/show-me/desktopcapturer/main.js
- static/show-me/dialog/main.js
- static/show-me/ipc/main.js
- static/show-me/menu/main.js
- static/show-me/notification/main.js
- static/show-me/remote/main.js
- static/show-me/screen/main.js
- static/show-me/shell/main.js
- static/show-me/touchbar/main.js
- static/show-me/webcontents/main.js
- static/show-me/webframe/main.js
Follow-up to #312 (and https://github.com/electron/electron/pull/21957), updates all the examples in the Fiddle repo I could find.
CC: @nornagon
> refactor(show-me): avoid using a global mainWindow variable

- src/less/components/editors.less
- src/renderer/components/editor.tsx
- src/renderer/components/editors.tsx
- tests/renderer/components/__snapshots__/editors-spec.tsx.snap
- tests/renderer/components/editor-spec.tsx
Fixes #289 
Leverages the CSS `z-index` property and Monaco's `onDidFocusEditorText()` event handler to make the latest focused Editor pane higher in stack order than the others.
The Less selectors are a bit complicated because I couldn't add the `focused` class directly on each `<MosaicWindow/>`. This is due to the `<Mosaic/>` element not calling `renderTile()` unless the child `<MosaicWindow/>` elements were re-arranged.
> fix: prevent other editors from clipping tooltips

- src/less/components/version-select.less
- src/less/root.less
- src/renderer/components/commands-bisect.tsx
- src/renderer/components/commands-version-chooser.tsx
- src/renderer/components/dialog-bisect.tsx
- src/renderer/components/settings-electron.tsx
- src/renderer/components/version-select.tsx
- src/renderer/remote-loader.ts
- src/renderer/state.ts
- tests/renderer/components/__snapshots__/commands-version-chooser-spec.tsx.snap
- tests/renderer/components/__snapshots__/dialog-bisect-spec.tsx.snap
- tests/renderer/components/__snapshots__/version-select-spec.tsx.snap
- tests/renderer/components/commands-version-chooser-spec.tsx
- tests/renderer/components/dialog-bisect-spec.tsx
- tests/renderer/components/settings-electron-spec.tsx
- tests/renderer/components/version-select-spec.tsx
- tests/renderer/remote-loader-spec.ts
- tests/renderer/state-spec.ts
This PR improves the existing bisect helper by turning our "Electron Version Select" into a generic component that can be consumed by both the command bar as well as the bisect helper. I have a feeling that we'll need more of these in the future.
It also ensures that the bisect helper will show the same versions as the command bar as configured in the preferences.
(This PR _seems_ to add more lines than it deletes, but that's just snapshots. The code is _actually_ smaller)
> fix: Reorganize the bisect helper

- src/renderer/components/dialog-bisect.tsx
- src/renderer/components/version-select.tsx
- tests/renderer/components/__snapshots__/dialog-bisect-spec.tsx.snap
- tests/renderer/components/dialog-bisect-spec.tsx
@erickzhao suggested, correctly, that the reorganization of code in #324 resulted in a bisect helper that wasn't _quite_ as helpful as it was before. I'm hoping that these suggestions go a bit above and beyond, making the result even more helpful than we had before - to make up for how I made it worse :wink:
Two things here: First, I added some actual help text. Secondly, the dropdowns now let you only select versions that make sense, ensuring that you never end up in a situation where you can't start the bisect. I left our sanity checks in there though, even if you should never be able to select versions that result in inability to start the bisect.
Help, by default mostly minimized:
Then extended:
Disabled versions:
> feat: Add some help to the bisect

- src/main/menu.ts
I hit <kbd>⌘+R</kbd> once and realized that the Reload function has very wonky behaviour. Also, not much use. This PR removes the menu item.
* When reloading from a clean save state, the editors revert to the default fiddle (regardless if you have a saved gist or locally saved fiddle open).
* When reloading from an unclean save state, you get a "quit" prompt, and Fiddle closes if you accept.
> fix: remove broken "Reload" menu item

- src/content/html.ts
- src/interfaces.ts
- src/renderer/app.tsx
- src/renderer/components/commands-publish-button.tsx
- src/renderer/components/editor.tsx
- src/renderer/components/editors.tsx
- src/renderer/constants.ts
- src/renderer/file-manager.ts
- src/renderer/remote-loader.ts
- src/renderer/templates.ts
- src/shared-constants.ts
- tests/mocks/app.ts
- tests/renderer/app-spec.tsx
- tests/renderer/components/__snapshots__/commands-editors-spec.tsx.snap
- tests/renderer/components/__snapshots__/editors-spec.tsx.snap
- tests/renderer/components/commands-publish-button-spec.tsx
- tests/renderer/components/editor-spec.tsx
- tests/renderer/file-manager-spec.ts
- tests/renderer/npm-spec.ts
- tests/renderer/remote-loader-spec.ts
- tests/renderer/runner-spec.tsx
- tests/renderer/templates-spec.ts
- tests/utils/get-package-spec.ts
Closes #298 
This PR builds upon the work done in #254, #292, and #293, mirroring what we did to support `preload.js` to incorporate a `styles.css` file.
(This also means that any future bugs found with `preload` probably apply to `css` as well 😂)
This feature will be helpful for app developers looking to use Fiddle as a playground for app ideas beyond merely testing API functionality.
> feat: add CSS support

- package.json
- src/main/ipc.ts
- src/main/main.ts
- src/main/protocol.ts
- src/renderer/app.tsx
- src/renderer/components/commands-publish-button.tsx
- src/renderer/components/editors.tsx
- src/renderer/file-manager.ts
- src/renderer/ipc.ts
- src/renderer/runner.ts
- src/renderer/state.ts
- src/sentry.ts
- tests/main/context-menu-spec.ts
- tests/main/devtools-spec.ts
- tests/main/dialogs-spec.ts
- tests/main/files-spec.ts
- tests/main/first-run-spec.ts
- tests/main/ipc-spec.ts
- tests/main/main-spec.ts
- tests/main/menu-spec.ts
- tests/main/protocol-spec.ts
- tests/main/squirrel-spec.ts
- tests/main/update-spec.ts
- tests/main/windows-spec.ts
- tests/mocks/electron.ts
- tests/setup.js
This PR improves the speed and memory consumption of our tests considerably. It does by doing the following things:
- Main process tests are now run without setting up a whole `jsdom` environment
- We're now tearing down all listeners, even for components that never get unmounted in "real life". A good example here are the listeners on the `App` component.
- We're no longer initializing Sentry during tests.
> chore: Unregister various listeners

- .travis.yml
Just some CI config cleanup. `sudo:` is no longer a thing, and the caching for npm is more clever these days. Related Forge template update: https://github.com/electron-userland/electron-forge/pull/1539
> build: cache/install node deps per Travis docs, remove deprecated option

- .github/workflows/electron-releases.yml
Follow-up from https://github.com/electron/fiddle/pull/330#discussion_r385443905, have Electron Bot (via GitHub Actions) automate adding new Electron releases to the JSON file.
Example run: https://github.com/malept/fiddle/runs/480768703?check_suite_focus=true (although on push instead of cron)
Example commit: https://github.com/electron/fiddle/commit/2ceadbbd7c125519f28a5c7f5f57d5aa8b1d1d4d
> build: auto-update the Electron Releases JSON file every day

- .github/actions/create_releases_pr.js
- .github/workflows/electron-releases.yml
- package-lock.json
- package.json
- tests/fixtures/releases-metadata.json
- tests/renderer/touch-bar-manager-spec.ts
- tests/renderer/versions-spec.ts
- tools/fetch-releases.js
Turns out that we can't use GitHub Actions to automatically push release metadata changes to master due to branch protection. However, @erickzhao made a great suggestion to have the action create PRs instead.
* Move expected version count & latest Electron version to its own fixture file
* Automatically update expected version count & latest Electron version when updating the JSON file
* Throw an error if a rejection occurs when the fetch releases script is run
* Reduce the update frequency to once a week, now that we're creating pull requests
I've been testing on my fork, here's an example PR (base changed because it's using a test branch as the base): https://github.com/malept/fiddle/pull/6
It shouldn't create a new branch or new PR if one already exists.
This might conflict with #339.
> build: create a PR for releases.json updates instead of trying to push to master

- .gitignore
- jest.json
- package.json
Add a command to generate a json report for a given test run. I'm working on consuming these in a reportable way, so this helps me out with that venture a bit.
cc @erickzhao @felixrieseberg
> chore: add test report generation helper

- src/interfaces.ts
- src/renderer/components/dialog-add-version.tsx
- src/renderer/state.ts
- src/renderer/versions.ts
- tests/mocks/npm-response-nightlies.json
- tests/mocks/unpkg-mock.json
- tests/renderer/versions-spec.ts
- tests/utils/array-to-stringmap-spec.ts
Fixes #332.
This pull request swaps out fetching (partially undoing what was done in #126). Instead, we fetch Electron releases from [`https://unpkg.com/electron-releases/lite.json`](https://unpkg.com/electron-releases/lite.json), which _should_ be more accurate. 
It also cuts off all versions under `0.24.0`, since `electron-download` cannot handle the old binaries that were called `atom-shell`. _N.B. There are still more versions available now._
The NPM registry had bogus releases on both the nightly channel (an odd `v0.0.0`), as well as on the regular one (relics from the old project that once held the `electron` name on NPM).
> refactor: grab release list from unpkg

- src/renderer/components/editor.tsx
- src/renderer/constants.ts
- tests/renderer/components/editor-spec.tsx
Fixes #338. 
In `constants.tsx`, we set the default hidden editor backup values to be `{}`.
https://github.com/electron/fiddle/blob/3709d122a6bcd75730f7322a61eb9dbee616284b/src/renderer/constants.ts#L23-L27
This initial value was problematic with our existing business logic for editor backups, which would not set the editor backup properly for `{}` due to a missing branch in the conditional flow:
https://github.com/electron/fiddle/blob/96bd2e36dd95880bff73430bb4281780277585b6/src/renderer/components/editor.tsx#L148-L165
We can see that the `setContent()` function is a no-op if the backup exists, but it has no model or value. To change that, the easiest way is the solve the problem at the root and delete the `{}` values.
Ancillary changes:
* Removed stray logging statement
* Reorganized …
> fix: ensure hidden panels work on first load

- jest.json
- package.json
Follow up to https://github.com/electron/fiddle/pull/340#pullrequestreview-371336100.
I accidentally forgot to cherry-pick over the `--bail=false` update from `jest.json` but you can also just specify it at the cli level so this does that. Also uses more idiomatic `|| true` instead of `|| exit 0`
cc @erickzhao @ckerr
> chore: fix test:report bailing

- src/renderer/components/commands-editors.tsx
- src/renderer/components/editors.tsx
- tests/renderer/components/__snapshots__/commands-editors-spec.tsx.snap
- tests/renderer/components/__snapshots__/editors-spec.tsx.snap
- tests/renderer/components/commands-editors-spec.tsx
- tests/renderer/components/editors-spec.tsx
Fixes #335 by ensuring that the last open editor cannot be closed.
This means two things happen when only one editor is open:
1) The toolbar controls on the top right of the panel (expand, close) are hidden.
2) You cannot close the last editor through the `commands-editor` component.
This work is done by checking `appState.mosaicArrangement`, which goes from an object to a single `EditorId` string when only one window is open.
> fix: ensure you have at least one editor open

- src/renderer/binary.ts
- src/renderer/state.ts
- src/renderer/versions.ts
- tests/mocks/binary.ts
- tests/renderer/binary-spec.ts
- tests/renderer/state-spec.ts
- tests/renderer/versions-spec.ts
Fixes #321.
When updating version lists, we would previously remove all of the states from the previous versions. However, we would only reinstate the `Downloaded` versions and not the `Downloading` ones.
This PR checks the `BinaryManager` state to see which versions were currently downloading, and marks them as such.
> fix: preserve 'downloading' version state post-refresh

- src/renderer/components/settings-electron.tsx
- src/renderer/state.ts
- src/renderer/versions.ts
- tests/renderer/components/__snapshots__/settings-electron-spec.tsx.snap
- tests/renderer/versions-spec.ts
Fixes #336 indirectly.
Makes sensible restrictions for which Release Channels and Version States we can filter out, mostly so that the version selector never ends up empty and the current version you have selected cannot disappear from the selector.
* Release Channels: Cannot disable the release channel of the version that you currently have selected.
* Version States: Cannot disable "Ready" versions. It doesn't make sense to not be able to select all of the versions that you have downloaded.
> feat: more sensible version filtering

- src/renderer/app.tsx
- src/renderer/components/editors.tsx
- src/renderer/file-manager.ts
- src/renderer/state.ts
- tests/renderer/app-spec.tsx
- tests/renderer/state-spec.ts
Fixes #337.
Previously, we would attempt to load all of our unsaved handlers after a 1500ms timeout, since we didn't know when exactly the editors would mount.
https://github.com/electron/fiddle/blob/8e4238275c881e5ff09aedb48fbf029ae37c4bdf/src/renderer/app.tsx#L180-L184
No longer now.
* `this.setupUnsavedOnChangeListener()` has been refactored out to fit into the `autorun()` that handles the `appState.isUnsaved` state, so every time we mark something as not unsaved (i.e. _is saved_), we set up these handlers already. No more manual calls to do so!
* We now use async/await to ensure that `monaco` is loaded before we initially set up the `isUnsaved` state so that the handlers won't error out.
Caveat: This does make loading the Fiddle editors visibly slower. Is it a worthy tradeoff?
> fix: load unsave handlers only after editors mount

- src/renderer/components/commands-bisect.tsx
- tests/renderer/components/__snapshots__/commands-bisect-spec.tsx.snap
- tests/renderer/components/commands-bisect-spec.tsx
Fixes #319.
This does two things to improve the Bisect experience, based on my own usage of the feature:
* Upon selecting "Good" or "Bad", we kill the current Fiddle app.
* The "Good" and "Bad" buttons are disabled while the current Electron version is downloading.
> feat: improved bisect commands UX

- forge.config.js
This PR ensures that we only notarize during `npm run make` and only if we're on a Travis tag.
> build: Only notarize during make

- package-lock.json
This PR updates the bundled version of `@electron/get` to 1.10.0 in order to incorporate this new functionality: https://github.com/electron/get/pull/155 which allows for overriding the downloaded version of Electron with a custom one via environment variable.
Alternately, we might consider not committing the package lock, to prevent this problem; i'm open to either option!
cc @erickzhao @felixrieseberg
> chore: update @electron/get version

- src/renderer/components/editors.tsx
Fixes #383 
According to React State and Lifecycle docs, the only place where you can assign `this.state = {}` it's `constructor`. Ref [doc](https://reactjs.org/docs/state-and-lifecycle.html#do-not-modify-state-directly). Here we try to assign inside the `comonentDidMount` 🙈.
> fix: don't modify state directly

- src/renderer/state.ts
If the file doesn't exists just don't try to watch them.
Fixes #378
> fix: ignore error when unable to watch typedefs

- src/main/windows.ts
- src/renderer/state.ts
How Electron docs say for [`closed` event](https://www.electronjs.org/docs/api/browser-window#event-closed) after this event is fired we should remove the `browserWindow` and never use them. Previously we still can use these `browserWindow` if the window doesn't more exist. This PR makes `browserWindow` null after they removed.
Fixes #379 
/cc @erickzhao
> fix: set the window to null after destroying

- src/renderer/components/dialog-token.tsx
- tests/renderer/components/dialog-token-spec.tsx
Currently when GitHub authentication failed we give the user error and ability to exit, but with that, we also save the invalid token to the state, and that token is used for any authenticated things like publishing Gist.
This PR reset token to `null` when the authentication is not completed correctly.
> fix: reset github token when authentication failed

- src/main/menu.ts
He does all the work for us.
Fixes #394
> fix: use `role: quit` for render exit button in menu

- src/renderer/components/commands-publish-button.tsx
- tests/renderer/components/__snapshots__/commands-publish-button-spec.tsx.snap
- tests/renderer/components/commands-publish-button-spec.tsx
This PR adds the ability to update the existing Gist instead of publishing the new one. Also added toasts notifications when the gist published or updated.
GIFS 😃😃
Fixes #290
> feat: add ability to update gist instead of publishing

- src/renderer/components/settings-execution.tsx
- tests/renderer/components/__snapshots__/settings-execution-spec.tsx.snap
When editing execution parameters, there's a link to Electron's documentation for command line switches. However, it looks like that documentation page has moved recently (https://github.com/electron/electron/pull/20335).
Old link: https://www.electronjs.org/docs/api/chrome-command-line-switches
New link: https://www.electronjs.org/docs/api/command-line-switches
> fix: Update documentation link for user-provided flags

- src/main/menu.ts
- static/show-me/app/main.js
- tests/main/menu-spec.ts
As `app.getName` is deprecated, this PR replaces it with the `app.name` property.
> refactor: replace app.getName() with app.name

- src/renderer/components/editor.tsx
I'm not sure what effect this had on the app, but this adds an `await` where there should have been one, and removes another that shouldn't have been there.
> fix: proper async/await usage in editor.tsx

- src/renderer/app.tsx
- src/renderer/components/commands-publish-button.tsx
- src/renderer/constants.ts
- src/renderer/state.ts
- src/utils/editor-model.ts
- src/utils/editor-mounted.ts
- src/utils/editor-value.ts
- src/utils/editor-viewstate.ts
- tests/renderer/app-spec.tsx
- tests/renderer/state-spec.ts
- tests/utils/editor-model-spec.ts
- tests/utils/editor-mounted-spec.ts
- tests/utils/editor-value-spec.ts
- tests/utils/editor-viewstate-spec.ts
Fixes #387
Fixes #400
We didn't account for hidden editors when considering our interactions with publishing Gists. This presented itself in two ways:
1) Remote content (including Gists) would only load if the editor was loaded at some point. This is because we checked each editor for its corresponding remote content.
2) Published Gists would be missing content if an editor was hidden.
1) When loading remote content, we now first open all editors that have non-placeholder content. This ensures that the content can load into the editors, and provides an all-around better experience since all the content from the Gist will be loaded on-screen.
2) When hiding an editor, we now delete it from the `editors` mapping before creating its backup in `appState.closedPanels`. We also now check the …
> fix: make hidden editors interact properly with remote content

- src/content/main.ts
I fixed the comment above the auto-quit prevention for macOS.
Before it suggested the code quits the app, now it says the code prevents the app from quitting.
**Note**: This same pull request was on [Electron \#24003](https://github.com/electron/electron/pull/24003). I added it here too for consistency.
> docs: fix explanation of darwin auto-quit prevention

- src/renderer/runner.ts
Add extra logging for notification debugging when advanced logging is enabled in Execution Preferences.
cc @felixrieseberg @erickzhao
> feat: log notification info in adv logging

- forge.config.js
- static/entitlements.plist
Fiddle was blowing up spectacularly when i tried to test 
```
const { systemPreferences } = require('electron')
const microphone = systemPreferences.askForMediaAccess("microphone")
```
and a journey into the Console app informed me:
```
This app has crashed because it has a hardened runtime and attempted to access privacy-sensitive data without an entitlement indicating its intent to access this data.  The app must have the 'com.apple.security.device.audio-input' entitlement.
```
and so this adds relevant entitlements to fiddle to fix said crash.
cc @felixrieseberg @erickzhao
> fix: audio/video entitlements crash

- src/renderer/app.tsx
- src/renderer/components/commands-address-bar.tsx
- src/renderer/components/commands-publish-button.tsx
- src/renderer/file-manager.ts
- src/renderer/state.ts
- src/utils/gist.ts
- tests/utils/gist-spec.ts
Fixes #396 
This PR clears the `localPath` variable in the App State whenever a `gistId` is saved, and vice-versa. Although I do still think that the user experience here still has a lot of room for improvement, this change makes it slightly clearer because you only have one source of truth with each save/publish.
Caveat: if you save a Fiddle that was previously published as a Gist, the Gist ID disappears in the publish bar.
> fix: clearer document titles

- src/ipc-events.ts
- src/main/menu.ts
- src/renderer/components/editors.tsx
- tests/main/menu-spec.ts
- tests/renderer/components/editors-spec.tsx
Fixes #434 by overriding the default MenuItem role and programmatically selecting the entire contents of the currently focused editor.
> fix: add functioning Select All menu item

- package-lock.json
- package.json
Closes #441
Updates to `^1.0.2`
> build(deps): upgrade electron-default-menu to 1.0.2

- static/show-me/browserwindow/main.js
The `transparent` configuration on Windows OS requires the window to also be frameless. Updating the show-me to handle win32. 
The show-me now also demonstrates the `frame` configuration. 
This behavior is documented at the entry for `transparent` at the [BrowserWindow API doc](https://www.electronjs.org/docs/api/browser-window#new-browserwindowoptions).
> fix: transparent BrowserWindow show-me on Windows

- src/renderer/state.ts
Two small fixes that TypeScript was complaining about. Shouldn't have any change on how things work.
> refactor: remove unnecessary code in renderer/state.ts

- package-lock.json
- package.json
Ref #454 
That version of `electron-devtools-installer` what's we use doesn't support Electron 9. It's doesn't fix the problem but give the more generic problem 😀.
> build: update electron-devtools-installer to latest version

- src/sentry.ts
This PR makes it so that Sentry doesn't activate on developer builds. Of course, one technically _could_ revert this change in their local repo and `npm start` anyways, but it should cut down Sentry alerts from people testing changes locally.
> chore: only enable Sentry in production

- src/renderer/components/commands-action-button.tsx
- tests/renderer/components/__snapshots__/commands-publish-button-spec.tsx.snap
Closes https://github.com/electron/fiddle/issues/486.
Adds unique icons for each of the publish, update, and delete actions. Will need rebase on https://github.com/electron/fiddle/pull/488 once it's merged.
> feat: add unique icons for gist actions

- src/main/menu.ts
- tests/mocks/electron.ts
Closes https://github.com/electron/fiddle/issues/479.
Also sends the action to the first responder so that this also works in the version picker and gist text field.
cc @nornagon @erickzhao @HashimotoYT
> fix: selectAll should work in text fields

- src/renderer/components/commands-action-button.tsx
- tests/renderer/components/__snapshots__/commands-publish-button-spec.tsx.snap
Closes https://github.com/electron/fiddle/issues/487.
Fixes an issue where if multiple gists are published on top of one another, the delete state is not properly updated. To clean this up a bit, i've also pulled out the various gist actions into their own functions. Also fixed several pre-existing issues with publishing state being persisted at the same time as updating state.
To test, I:
1. Published Fiddle 1 ✅ 
2. Edited and updated Fiddle 1 ✅
3. Published Fiddle 2 ✅ 
4. Deleted Fiddle 1 ✅ 
5. Updated Fiddle 2 ✅ 
6. Loaded and deleted Fiddle 2 ✅ 
Which i _believe_ should cover all state transitions.
cc @HashimotoYT
> fix: gist action state management

- src/utils/sorted-electron-map.ts
- tests/utils/sorted-electron-map-spec.ts
Closes https://github.com/electron/fiddle/issues/482.
The issue opened by @nornagon exposed a greater issue, which was that we weren't previously sorting prerelease tags at all in our logic. This meant that for a given major version the stable tags would correctly show at the top, but they would be followed by nightly tags instead of beta tagged version, which is incorrect since beta are strictly newer than nightlies. 
Semver does not handle this on its own: https://www.npmjs.com/package/semver#prerelease-tags
As such this PR seeks to address that by adding extra logic to `sortedElectronMap` to ensure prerelease tags sort properly as well as a test to ensure that's the case. Also tested with @nornagon's repro.
<details>
<summary>Before</summary>
</details>
<details> …
> fix: version prerelease sorting

- src/interfaces.ts
- src/renderer/components/commands-action-button.tsx
- src/renderer/components/commands-address-bar.tsx
- src/renderer/state.ts
- tests/renderer/components/__snapshots__/commands-address-bar-spec.tsx.snap
- tests/renderer/components/__snapshots__/commands-publish-button-spec.tsx.snap
- tests/renderer/components/commands-address-bar-spec.tsx
- tests/renderer/components/commands-publish-button-spec.tsx
Fiddle can't perform more than one action at a given time, so it makes more sense to place all potential actions in one state variable.
We also had some state variables in the Mobx store and some not, and as we should disable the command bar during _any_ action it makes the most sense to place this overarching state variable in the Mobx store.
cc @felixrieseberg
> refactor: clean up gist action states

- src/interfaces.ts
- src/renderer/components/commands-action-button.tsx
- src/renderer/components/dialog-generic.tsx
- src/renderer/state.ts
- tests/renderer/components/commands-publish-button-spec.tsx
- tests/renderer/state-spec.ts
Closes https://github.com/electron/fiddle/issues/477.
This introduces a means to set a custom description for each Gist that's published to GitHub. This is useful when creating many gists since they're hard to differentiate with the same name.
> feat: allow setting gist description

- src/renderer/components/settings-general-appearance.tsx
- src/renderer/components/settings-general.tsx
- src/renderer/components/settings.tsx
- src/renderer/state.ts
- tests/renderer/components/__snapshots__/settings-general-appearance-spec.tsx.snap
- tests/renderer/components/__snapshots__/settings-general-spec.tsx.snap
- tests/renderer/components/__snapshots__/settings-spec.tsx.snap
- tests/renderer/components/settings-general-appearance-spec.tsx
- tests/renderer/components/settings-general-spec.tsx
- tests/renderer/components/settings-spec.tsx
Closes https://github.com/electron/fiddle/issues/322
I added a state listener for when someone opens the theme selector. I could not figure out a way to stop the events from propagating and closing the settings besides this solution. It might be better to make this more generic of `prevenSettingsClose` or something, but I am not sure.
I saw that this is a good first issue to test my OSS contributions on, I am mainly an Angular developer and have only dabbled a little in React so if there is a better way to make these changes, please let me know.
> fix: theme select popover closing settings when pressing escape

- src/renderer/npm.ts
- src/renderer/runner.ts
- tests/renderer/npm-spec.ts
- tests/renderer/runner-spec.tsx
Doing the same thing what's we do with `npm`. It's a super simple solution that's not represented in the UI but represents on the launch.
> chore: ensure yarn is installed before launching fiddle

- src/renderer/components/commands-action-button.tsx
Closes https://github.com/electron/fiddle/issues/501.
Ensures the privacy menu is always visible if we are in a publish state.
cc @erickzhao @vhashimotoo
> fix: show privacy menu when in publish state

- .github/workflows/electron-releases.yml
The weekly Electron releases.json PR action broke when we moved from npm to yarn (mostly because we no longer have a `package-lock.json`). This converts all calls to yarn, and also updates the commit username to match the email.
> ci: convert electron-releases action from npm to yarn

- src/renderer/npm.ts
- src/renderer/runner.ts
Refs https://github.com/electron/fiddle/commit/0bc8389c6c5ce43ca6eb58feaec77de7247d50af.
Fixes an issue where Node.js modules would never install and the UI would freeze because `getIsPackageManagerInstalled` would never resolve.
cc @felixrieseberg @erickzhao
> fix: installing modules with npm/yarn

- src/renderer/components/editors.tsx
Fixes #521 
This PR adjusts the order of the keys passed to `replaceFiddle`. Internally replace fiddle is using the order of `Object.keys()` to determine the mosaic (which for non-numeric keys will be insertion order). I'd be happy making this a bit more robust via specified `order` param or an object that includes mosiac position. This does fix the issue though.
> fix: re-order keys in replaceFiddle, fixing mosaic order

- src/less/components/output.less
- src/renderer/components/output.tsx
- tests/renderer/components/__snapshots__/output-spec.tsx.snap
Fixes #480 
This PR moves the console from `<p>` elements per row, to `<span>`s wrapped in `<div>` to avoid additional newlines when copy pasting. I modeled this very loosely around the structure used by the chrome inspector console.
> fix: re-work output dom to remove whitespace when copying

- src/renderer/components/commands-runner.tsx
- src/renderer/runner.ts
- src/renderer/state.ts
Depends on https://github.com/electron/fiddle/pull/526 - should be rebased/merged only after that PR is merged.
Adds a spinner animation for Node.js module installs so it doesn't just freeze on run and give the user no UI indication of what's happening beyond console output.
cc @erickzhao @felixrieseberg
> fix: spin while installing modules

- src/renderer/state.ts
- tests/renderer/state-spec.ts
Instead of shallow copying the `this.versions` object, we use the mobx `toJS` API to recursively deserialize the Observable objects inside `this.versions`.
Prior to this change, each version object  inside `this.versions` would remain a mobx observable, leading to a significant slowdown in operations when changing the version object state (this slowdown is linear with the amount of downloaded versions you have).
Since `updateDownloadedVersionState()` is run on app load and blocks the editors from loading, this change gives a significant decrease of the first meaningful paint time if you have many versions of Electron downloaded.
With ~40 versions downloaded (all of the 11 and 10 betas), I saw a decrease from 200ms to 30ms in the time spent on `updateDownloadedVersionState()`.
* Refactored …
> refactor: deserialize mobx when updating version list

- src/main/main.ts
- src/renderer/components/commands-action-button.tsx
- src/renderer/state.ts
- tests/main/main-spec.ts
- tests/renderer/state-spec.ts
This fixes two problems that I've noticed with the unsaved warning handler.
Commit 595af93 cleans up the logic for differentiating between quitting and closing Fiddle windows. Nests the "quit app" logic within the "close window" logic, reason being that there's no way to quit the app without already closing the window.
Incidentally, this fixes a bug where attempting to quit with an unsaved Fiddle, cancelling the quit, and quitting a second time led to the window closing but not the app (on macOS). I'm guessing this had to do with a problem between `window.close()` happening before we could tell the Main process to quit.
Commit 7e1edcd changes the app's `isUnsaved` state when publishing, updating, or deleting a Gist.
Publishing and updating now makes the state "saved".
Deleting makes the …
> fix: cleaner unsaved dialog logic

- tests/renderer/state-spec.ts
Seems like we were getting many `(node:2702) UnhandledPromiseRejectionWarning: TypeError: downloadingVersions is not iterable` errors when running `yarn test`, but these weren't picked up by Jest as test failures. I believe this snuck in PR #520.
See example: https://github.com/electron/fiddle/runs/1427245746?check_suite_focus=true
The root cause of this problem was that the Binary Manager's `getDownloadingVersions` and `getDownloadedVersions` were being used across the `state-spec.ts` file's `updateDownloadedVersionState` but weren't being mocked with each test.
For some reason, just added `mockReturnValue` in the initial mock doesn't work. Instead, I mock `updateDownloadedVersionState`and unmock it for the `updateDownloadedVersionState` tests.
> test: fix unhandled promise errors in state spec

- src/renderer/app.tsx
- tests/renderer/app-spec.tsx
Couple changes here. To see examples of expected behaviour, see added tests for `replaceFiddle()`.
Previously, we would only avoid showing mosaics that had "empty" values according to what we published to Gist:
https://github.com/electron/fiddle/blob/445e17361ce3dcf4a3334bb9948f383bbcf3b711/src/renderer/constants.ts#L35-L39
This was problematic for Show Me demos and local Fiddles, which would have actual empty strings instead. This is fixed with an additional guard against the length of the content string.
Following the work done in #525, I decided to nip this problem at the bud and load our mosaic in some exact order. The `replaceFiddle()` function now sorts the `Object.keys` result of the editorValues being passed in the exact order of Main, Renderer, HTML, Preload, CSS.
Added some …
> fix: improve Mosaic behaviour on Fiddle load

- src/renderer/components/commands-address-bar.tsx
- tests/renderer/components/__snapshots__/commands-address-bar-spec.tsx.snap
Once the user manipulates the <code>address bar</code> value and publishes the fiddle again , the gist url is no longer available .
<strong>Fix</strong> :
Added a <code>onBlur</code> event to <code>address bar</code> , which loads back the original gist url if the user looses focus out of the bar .
Fixes #427
Would love an review @erickzhao :)
> fix: repopulate URL bar on blur

- tools/contributors.js
Starts from that a GitHub stopped support for Basic auth, and ends by this is not the secure way now.
This seems has never to be used since not many provide the GITHUB_USERNAME as an environment variable.
> chore: don't use basic authentication for fetching contributors

- src/main/files.ts
- tests/main/files-spec.ts
- tests/main/menu-spec.ts
- tests/mocks/electron.ts
Fixes #551 by avoiding the offending API.
Swaps out `openDialog` for `openDialogSync` for saving local Fiddles.
Commits:
* cc84422 contains the code itself.
* c897f79 updates the tests so they pass.
* 212cd08 removes `<any>` types from `jest.Mock` in the tests.
> refactor: make save dialog synchronous

- src/renderer/components/commands-action-button.tsx
Similar to https://github.com/electron/fiddle/pull/329
Avoids `(node:12337) MaxListenersExceededWarning: Possible EventEmitter memory leak detected. 11 FS_SAVE_FIDDLE_GIST listeners added to [IpcRendererManager]. Use emitter.setMaxListeners() to increase limit` on tests.
> chore: clear action button listeners on constructor

- package.json
- yarn.lock
`chokidar` was added as a dev dependency in 97a37ab, but all direct references in the code were removed in a6e6fad.
> chore: remove chokidar dependency

- src/renderer/runner.ts
Refs https://github.com/electron/fiddle/issues/568.
The error was showing as `[object ErrorEvent]` and we want the user to see a more descriptive message. We should be pushing the message property of the [`ErrorEvent`](https://developer.mozilla.org/en-US/docs/Web/API/ErrorEvent) and not the object itself.
cc @felixrieseberg @erickzhao
> chore: display better error when packaging

- src/renderer/components/commands-address-bar.tsx
Closes https://github.com/electron/fiddle/issues/571.
Refs https://github.com/electron/fiddle/pull/531.
Fixes an issue where it was impossible to load a new gist via command bar when one was previously loaded. This was happening because the `onBlur` handler always pulled what it thought was the current gist from `appState`, which meant that if the gist a user was trying to load was not the same as the one in `appState`, it would be overwritten. This PR tries to fix that by asserting that the command bar is either empty or contains the last gist stored into `appState` before reloading the last stored Fiddle Gist.
Tested with the outlined steps in https://github.com/electron/fiddle/issues/571.
> fix: replacing an existing gist link

- src/main/menu.ts
Added small fix to clear the console once the user opens a new Fiddle.
<strong>ScreenShot :</strong>
Closes #573.
> fix: clear console when creating a new fiddle (#573)

- src/content/html.ts
- src/content/main.ts
- src/content/preload.ts
- src/content/renderer.ts
- src/renderer/components/editors-non-ideal-state.tsx
- src/renderer/components/editors.tsx
- src/renderer/constants.ts
- src/renderer/content.ts
- src/renderer/state.ts
- src/utils/editor-mounted.ts
- tests/mocks/editors.ts
- tests/renderer/state-spec.ts
- tests/utils/editor-mounted-spec.ts
- tests/utils/editors-mosaic-arrangement-spec.ts
Fixes #585.
Closes #377.
Update the default app to match [`electron-quick-start`](https://github.com/electron/electron-quick-start) because the previous default app no longer works out-of-the box in Electron 12.0.0. This change requires that `preload.js` is visible by default, so startup now shows a four-pane layout.
> chore: update default app to work w/Electron 12.0.0

- README.md
It looks like these two links are reversed.
> chore: fix README links

- src/ipc-events.ts
- src/main/main.ts
- src/renderer/components/chrome-mac.tsx
- tests/main/main-spec.ts
- tests/mocks/electron.ts
- tests/renderer/binary-spec.ts
- tests/renderer/components/chrome-mac-spec.tsx
- tests/utils.ts
- tests/utils/electron-name-spec.ts
Ref #418
Moves the click handler for the macOS titlebar into the main process.
> refactor: remove remote from `chrome-mac.tsx`

- src/renderer/runner.ts
- src/renderer/state.ts
Was previously erroring out upon passing undefined into `path.join()`.
Related to the appData -> appPaths improvements in https://github.com/electron/fiddle/pull/602
> fix: nullptr dereference in runner's cleanup function

- src/renderer/remote-loader.ts
- src/shared-constants.ts
- src/utils/read-fiddle.ts
- tests/renderer/remote-loader-spec.ts
remote-loader currently has an accidental switch fallthrough due to a missing `break;` statement [here](https://github.com/electron/fiddle/blob/255a81d7a7b827d9f290ef72f2924efc9d89ae86/src/renderer/remote-loader.ts#L126).
This PR removes the switch statement by promoting `FILENAME_KEYS` up from [read-fiddle.js](https://github.com/electron/fiddle/blob/255a81d7a7b827d9f290ef72f2924efc9d89ae86/src/utils/read-fiddle.ts#L14) into shared-constants.ts so that it can be used by remote-loader as well. By using this the switch statement can be avoided altogether.
Discovered while fixing up coverage leaks in the autobisect branch :smiley:
> fix: accidental switch fall-through in remote-loader

- src/renderer/binary.ts
- tests/renderer/binary-spec.ts
Right now there is an edge case where setupBinary() can resolve before a download is done: if called while a download for that version is already running, setupBinary() returns to avoid parallel downloads. Because of this return, the caller may find their RunnableVersion does not have the state that was expected.
This PR keeps track of pending downloads so that when a duplicate call occurs, all callers get a Promise that settles when the download does.
This is similar to how renderer/content [safeguards against parallel downloads](https://github.com/electron/fiddle/blob/858e4b1834832e0ea5ccf64825c2bd7d201a8a2b/src/renderer/content.ts#L57) of the same zipfile.
> fix: setupBinary() resolves when download completes

- src/renderer/components/editors.tsx
- src/utils/editor-mounted.ts
- src/utils/wait-for.ts
- tests/main/menu-spec.ts
- tests/renderer/components/editors-spec.tsx
- tests/renderer/components/settings-electron-spec.tsx
- tests/renderer/state-spec.ts
Some of the test / coverage changes in the autobisect branch are not directly related to autobisect, so I've extracted them out to their own branch here to reduce sprawl. This is a handful of small test refactors:
* Avoid some magic numbers / magic strings, using symbolic names or computed values instead. This is _not_ comprehensive; the changes are in places where the magic values are changing in the autobisect branch
* Fix a double-subscribe-to-IPC issue in editors.tsx
* Improve coverage in SELECT_ALL, FS_NEW_FIDDLE, and editors.setFocused()
* Add a new util `waitFor()` that is extract-method'ed from `waitForEditorsToMount()`
> refactor: minor test cleanups

- src/renderer/binary.ts
- src/renderer/components/dialog-add-version.tsx
- src/renderer/runner.ts
- tests/renderer/binary-spec.ts
- tests/renderer/components/dialog-add-version-spec.tsx
A minor refactor to `src/renderer/binary getIsDownloaded()`, which is async only because it uses fancy-import. However this isn't necessary in order for testing, so the code can be simplified a little by removing `async`.
> refactor: remove unnecessary 'async' from getIsDownloaded()

- src/utils/sorted-electron-map.ts
- tests/utils/sorted-electron-map-spec.ts
Refactor sortedElectronMap() to parse the versions strings less often.
Calls to `semver.valid()`, `semver.prerelease()`, `semver.coerce()`, and `semver.gt()` keep causing the version string to be  reparsed. This refactor calls `semver.parse()` once per RunnableVersion and uses that object for the compare function. For our current startup, this drops the number of times `semver.parse()` is called on startup from 50k times to 4k times.
> perf: faster sorting in sortedElectronMap()

- src/renderer/content.ts
A small change to some code I wrote last week that keeps showing up with a larger-than-necessary footprint in the coverage tests. To get the max item from a `semver.SemVer[]` we don't need to sort the array; we can walk the array with reduce().
Brings this line from O(n log n) to O(n).
> perf: faster isReleasedMajor()

- package.json
- src/interfaces.ts
- src/renderer/components/output.tsx
- src/renderer/runner.ts
- tests/mocks/electron-versions.ts
- tests/mocks/runner.ts
- tests/renderer/components/__snapshots__/commands-version-chooser-spec.tsx.snap
- tests/renderer/components/__snapshots__/settings-electron-spec.tsx.snap
- tests/renderer/runner-spec.tsx
- yarn.lock
Add `Runner.autobisect()` + full coverage testing.
Found a couple of edge cases, e.g. we want to make sure that the 'good' version is actually good and 'bad' version is actually bad -- the user might be wrong / the test doesn't work everywhere / etc. So we do now check that the 'good' version and 'bad' version didn't return the same RunResult.
Getting into the home stretch now; GUI + CLI are up next.
> feat: add Runner.autobisect()

- tests/mocks/electron.ts
- tests/renderer/content-spec.ts
A small refactor to the content-spec. I recently added a tmpdir for the content-spec to test live unzipping, but think I scoped the code wrong. The feature is only needed in content-spec, so that's where it should live instead of in the `tests/mocks/` helpers.
* In terms of sprawl, this is a good thing because the tmpdir scaffolding now has a narrower scope.
* Since our jest config calls resetMocks() between tests, it's preferable to KISS our mocks' default state.
> refactor: limit tmpdir scope to tests that need them

- src/renderer/components/version-select.tsx
- tests/renderer/components/version-select-spec.tsx
Right now there's a visual wart that during a download the icon goes from 'cloud' (unknown) -> 'cloud-download' (downloading) -> 'cloud' (unzipping) -> 'saved' (saved) and that second shortlived 'cloud' during unzip is a little confusing because for a moment it looks like the download has disappeared. 
This PR uses 'compressed' as the icon during unzip to avoid giving the user that mixed signal.
> feat: add an icon for Electron DLs being unzipped

- src/main/files.ts
- src/renderer/components/commands-action-button.tsx
- src/renderer/components/editors.tsx
- src/renderer/file-manager.ts
- src/renderer/remote-loader.ts
- src/utils/get-package.ts
This is a minor refactor to avoid hardcoding files and editor ids. Most cases can iterate through the `FILENAME_KEYS` object which lets the code avoid hardcoding files / editor is _and_ avoid making assumptions on what editors exist.
I started this cleanup while we were prototyping a new 'test.js' editor. It's less relevant since we discarded that idea, but it's still preferable to use symbolic names instead of magic strings.
No functional changes.
> refactor: avoid hardcoding filenames, editor ids

- src/renderer/app.tsx
- src/renderer/constants.ts
- src/shared-constants.ts
- tests/renderer/state-spec.ts
- tests/utils/editors-mosaic-arrangement-spec.ts
I thought Fiddle hacking might help with some insomnia, but apparently not :slightly_smiling_face: 
The bug: On startup, the editor windows are sorted one way. Then if you hit 'New Fiddle' the preload and html editors will swap places. The root cause is that constants.ts's DEFAULT_MOSAIC_ARRANGEMENT and the 'order' array in app.tsx's replaceFiddle() do not have the same order.  Looks like I [introduced](https://github.com/electron/fiddle/commit/19acc0b1279b7aedb4e51a939bc49609fa4cebe1#diff-6fd15f0cf5192de646d9ba7274a882bb6c33406232567e8949e06f372320629bL21) this regression a couple of weeks ago when adding preload to DEFAULT_MOSAIC_ARRANGEMENT for v12.0.0.
This PR builds DEFAULT_MOSAIC_ARRANGEMENT from the sorted array so they will always match.
*edit:*  There are no new uncovered LOC or …
> fix: inconsistent sorting of editor windows

- tests/renderer/task-runner-spec.tsx
It seems like #623 makes the tests fail because `IpcRendererManager` is no longer exported. This PR fixes that.
> fix: remove unexported member in task-runner-spec

- src/main/about-panel.ts
- src/main/menu.ts
As @malept reported in #631, we have code to set up the About panel but never use it. This PR adds a Help menuitem to do so.
The previous code  had separate handling for different platforms -- setupAboutPanel() was a no-op on Windows, and then filled in vairous AboutPanelOptions based on platform. Since this setup is cheap, this PR just sets everything unconditionally and leaves it to Electron to decide what to use.
Doing it this way seems more straightforward, but I'm wondering what that `if (process.platform === 'win32') return` was for. It was introduced in https://github.com/electron/fiddle/commit/14279283d648ea73a1853fc972c453a9b40ee725.
Fixes #631.
> feat: add About to Help menu

- src/renderer/state.ts
A super small PR that is just here to remove a couple of logic branches that weren't used in testing or in production.
> refactor: simplify resetView() + improve coverage

- src/renderer/binary.ts
- src/renderer/state.ts
- src/renderer/versions.ts
- tests/mocks/electron-versions.ts
- tests/renderer/binary-spec.ts
- tests/renderer/state-spec.ts
- tests/renderer/versions-spec.ts
This refactor replaces `getDownloadingVersions()` and `getDownloadedVersions()` with a new function, `getVersionState()` which is intended to be more flexible in that it can also determine any state a Version is in, rather than just downloading/downloaded. For example, is it being unzipped at the moment.
This is an interim step towards dual goals of (a) adding a new state of "downloaded but zipped" for https://github.com/electron/fiddle/issues/644 and (b) cleanup to `state.versions` s.t. we don't need to keep rebuilding all those mobx proxies all the time.
> refactor: add getVersionState()

- src/renderer/fetch-types.ts
- src/renderer/npm.ts
- src/renderer/transforms/forge.ts
- src/utils/get-package.ts
- tests/renderer/npm-spec.ts
- tests/utils/get-package-spec.ts
Closes https://github.com/electron/fiddle/issues/392.
Fixes packaging nightly builds. Also fixes fetching types for nightly builds.
Nightlies come from electron-nightly and not electron, so we need to change the name in package.json. We also need to force a new ABI number as none has been assigned for nightlies.
Tested on macOS.
> fix: installers for nightlies

- tests/mocks/electron-versions.ts
- tests/renderer/binary-spec.ts
No functional changes, not even a refactor.
Just adds coverage for a couple of pieces in `renderer/binary`!
> test: improve binary spec coverage

- src/renderer/components/output-editors-wrapper.tsx
- src/renderer/components/output.tsx
- tests/renderer/components/output-spec.tsx
This refactor PR replaces the `this.context.mosaicActions` function that we use to expand and hide the console.
In `react-mosaic`, information about the current layout is stored in a binary tree of `MosaicNode<T>` objects. An object might looks like this, where `first` and `second` are child nodes:
```js
{
direction: 'row', // or 'column'
first: 'panel1',
second: 'panel2',
splitPercentage: 50 // between 0 and 100
}
```
The most important value for this PR is `splitPercentage`, which defines the percentage of area that the first item occupies (in the case above, both panels occupy half of the available space).
The module's advanced API allows you to programmatically modify this tree through React Context (available in `this.context.mosaicActions`. We currently use …
> refactor: resize console with `replaceWith` API

- src/renderer/app.tsx
- src/renderer/fetch-types.ts
- src/renderer/state.ts
- tests/renderer/app-spec.tsx
- tests/renderer/state-spec.ts
No functional changes. This is another PR like https://github.com/electron/fiddle/pull/642 aimed at simplifying our tests by reducing side-effects / shared state / unintended code execution.
This time around, it's about avoiding the global calls that are made as a side-effect of importing `state.ts`:
* getElectronVersions()
* getDefaultVersion()
* the biggie, everything in AppState.constructor() due to the AppState that is unconditionally created
* appState.setVersion()
This PR removes these so that importing state.ts has no side-effects. In production, state is instantiated by the App in the same way it does runner, fileManager, loader, etc.
*edit:* PR contains no new uncovered code. Coveralls is upset about code removal. :1st_place_medal:
> refactor: avoid global calls in renderer/state

- src/interfaces.ts
- src/renderer/components/settings-electron.tsx
- src/renderer/state.ts
- src/renderer/versions.ts
- tests/renderer/components/__snapshots__/commands-version-chooser-spec.tsx.snap
- tests/renderer/components/__snapshots__/dialog-bisect-spec.tsx.snap
- tests/renderer/components/__snapshots__/settings-electron-spec.tsx.snap
- tests/renderer/components/commands-version-chooser-spec.tsx
- tests/renderer/components/dialog-bisect-spec.tsx
- tests/renderer/components/settings-electron-spec.tsx
- tests/renderer/components/version-select-spec.tsx
- tests/renderer/state-spec.ts
- tests/renderer/versions-spec.ts
This PR revamps the version filters in File > Preferences > Electron:
1. The `statesToShow` toggles exist because those toggles fit the implementation, e.g. there's not really a use case for saying, e.g. "I only want to see versions that aren't downloaded." ... and the "Ready" toggle is unclickable with a tooltip that reads "Always enabled." This PR replaces that row with one toggle: "Show non-downloaded versions?"
2. The 'unsupported' filter has been removed. Back in 2019(?) the project made an Electron release tagged 'unsupported' because of reasons. It was a one-off thing that hasn't been done in years and doesn't need to be in the UI.
3. A new 'obsolete' filter has been added. This filter toggles whether or not end-of-lifed versions of Electron should be shown. This is a useful …
> feat: new version filters in File > Preferences > Electron

- src/renderer/binary.ts
- tests/renderer/components/__snapshots__/settings-general-block-accelerators-spec.tsx.snap
- tests/renderer/components/settings-general-block-accelerators-spec.tsx
This test file wasn't running because it wasn't postfixed with `-spec`. This fixes that and also the tests within the spec, which weren't correct.
> test: fix misnamed BlockAcceleratorsSettings spec

- src/main/windows.ts
- src/renderer/npm.ts
- src/utils/decomment.ts
- tests/main/windows-spec.ts
- tests/renderer/npm-spec.ts
Closes https://github.com/electron/fiddle/issues/577.
Fixes intellisense not working as a function of setting `nodeIntegrationInWorker: true` in the `BrowserWindow` options.
Ideally i'd like to narrow down the true fix but this shifts calls to `decomment` to `findModule` where they're invoked directly instead of via Worker thread - I think for now it's more important to regain this functionality while we search for a nicer long-term solution.
> fix: intellisense not working

- src/renderer/components/commands-action-button.tsx
- tests/mocks/state.ts
- tests/renderer/components/__snapshots__/commands-publish-button-spec.tsx.snap
- tests/renderer/components/commands-publish-button-spec.tsx
no functional changes.
This is a refactor of `tests/renderer/components/commands-publish-button-spec.tsx` that fills in some of the edge cases, e.g. the description dialog and some error handling.
It reduces copy-paste code duplication by nesting 'describe' sections with beforeEach() functions, e.g. in `describe('publish mode'` there is a beforeEach() that creates a publish button ready to be tested.
> test: improve `commands-action-button.tsx` coverage

- src/renderer/runner.ts
- src/renderer/state.ts
- tests/mocks/state.ts
Closes https://github.com/electron/fiddle/issues/668.
Refs https://github.com/electron/fiddle/commit/5c98534cd89fc4cabbe4512ee9d758696b09882a.
This was previously dropping output if `parts.length` was 1. Now it doesn't.
> fix: console output being dropping on Windows

- src/utils/gist.ts
- tests/utils/gist-spec.ts
Sometimes i'll paste in a gist link with a space at the beginning, which triggers a 404 not found error. Make this functionality a little more fault-tolerant by ensuring the url gets trimmed.
> fix: ensure gist input value is trimmed

- src/main/command-line.ts
- tests/main/command-line-spec.ts
Ensure that we error out quickly if the command line is fed an unparseable gist.
> fix: exit with err if the CLI is given a bad gist

- src/interfaces.ts
- src/main/command-line.ts
- src/renderer/task-runner.ts
- tests/main/command-line-spec.ts
- tests/mocks/state.ts
- tests/renderer/components/__snapshots__/settings-electron-spec.tsx.snap
- tests/renderer/task-runner-spec.tsx
When bisecting from the command line, it's possible that the last known good version is an obsolete release. Thus, it's necessary to be able to re-enable obsolete releases from the command line.
> feat: allow obsolete versions to be toggled in cli

- src/main/command-line.ts
- tests/main/command-line-spec.ts
Add a command-line argument `--log-config` that will show the electron-fiddle version, platform, and argv. This info is something that will be nice-to-have in bugbot's logfiles.
> feat: add --log-config command-line option

- src/main/files.ts
- src/main/menu.ts
- src/main/protocol.ts
- tests/main/files-spec.ts
- tests/main/main-spec.ts
- tests/main/menu-spec.ts
- tests/mocks/electron.ts
fixes: #316
This adds functionality to open and clear recent documents- either through the 'file' menu or the app context menu.
> feat: add recentDocuments to fiddle

- src/main/protocol.ts
- src/renderer/components/dialog-add-theme.tsx
- tests/main/main-spec.ts
- tests/main/protocol-spec.ts
Turns out, we never handled protocol links on Windows. I KNOW. I can't quite believe it, either.
> fix: Handle protocol links on Windows

- src/renderer/components/output.tsx
- tests/renderer/components/__snapshots__/output-spec.tsx.snap
Closes https://github.com/electron/fiddle/issues/709.
```js
const lines = output
.slice(Math.max(output.length - 1000, 1))
.map(this.renderEntry);
```
excludes the first element, which we wouldn't want to do especially when clearing Fiddles as it would lead to single dropped lines. Correct that.
> fix: don't exclude first line on clear

- src/renderer/binary.ts
- src/renderer/remote-loader.ts
- src/renderer/state.ts
- tests/mocks/state.ts
- tests/renderer/remote-loader-spec.ts
Should ideally land after https://github.com/electron/fiddle/pull/719.
This PR makes it such that if a user tries to launch a fiddle via https://fiddle.electronjs.org/ and the package.json contains an Electron version the user doesn't have downloaded, Fiddle will ask if the user would like to download it before proceeding instead of just failing and exiting.
Tested by running 
```sh
yarn start electron-fiddle://electron/main/docs/fiddles/screen/fit-screen
```
> feat: try downloading version if missing

- src/renderer/components/commands-runner.tsx
- src/renderer/state.ts
Closes https://github.com/electron/fiddle/issues/723.
if a local build is now selected but it's missing, Fiddle will now show a warning dialog indicating that the version can't be selected and that the user should verify it.
> fix: show warning dialog for missing local versions

- src/renderer/state.ts
- src/renderer/task-runner.ts
- tests/mocks/state.ts
Partially fixes https://github.com/electron/fiddle/issues/721, although the main symptom of that bug persists even when the welcome dialog is hidden.
> fix: close popup windows before running batch cmds

- static/show-me/webcontents/index.html
- static/show-me/webcontents/main.js
Fixes #735
Quick fix for the webContents "Show Me" demo, which currently uses `webContents.print()`. The print method behavior changed in Electron v8.1.0, and a dialog box is no longer shown if there are no printers detected or set. 
While we're determining if this should be the default behavior or if it's a bug, this PR changes the webContents demo to use `webContents.loadURL` as the sample method, which will hopefully be more stable and less prone to breaking in the future.
_Quick lint note: It looks like the linter adds semi-colons to the demo code - do we want that style? If not, I can remove them and commit with --no-verify._
> fix: update webcontents demo with loadURL

- src/main/windows.ts
- tests/main/windows-spec.ts
Closes https://github.com/electron/fiddle/issues/737.
Fixes an issue where reloading the window could cause an error and crash.
> fix: GET_APP_PATHS handler undefined on reload

- src/renderer/editor-mosaic.ts
- tests/renderer/editor-mosaic-spec.ts
Closes https://github.com/electron/fiddle/issues/741.
> fix: clear unused editor contents on replace

- src/interfaces.ts
- src/renderer/app.tsx
- src/renderer/components/commands-action-button.tsx
- src/renderer/components/commands-bisect.tsx
- src/renderer/components/commands-editors.tsx
- src/renderer/components/dialog-add-theme.tsx
- src/renderer/components/dialog-generic.tsx
- src/renderer/remote-loader.ts
- src/renderer/state.ts
- tests/mocks/state.ts
- tests/renderer/app-spec.tsx
- tests/renderer/components/commands-bisect-spec.tsx
- tests/renderer/components/commands-editors-spec.tsx
- tests/renderer/components/commands-publish-button-spec.tsx
- tests/renderer/components/dialog-add-theme-spec.tsx
- tests/renderer/components/dialog-generic-spec.tsx
- tests/renderer/remote-loader-spec.ts
- tests/renderer/state-spec.ts
This PR adds four dialog helper functions that take only the params they need and which return Promises that resolve when the user closes the dialog:
- `AppState.showConfirmDialog: Promise<boolean>`
- `AppState.showErrorDialog: Promise<void>`
- `AppState.showInfoDialog: Promise<void>`
- `AppState.showInputDialog: Promise<string | undefined>`
These all wrap GenericDialog so there's no more messing around with `!!appState.isGenericDialogShowing`, setting `cancel: undefined` to hide the cancel button, or forgetting to clear the last input value.
> refactor: add AppState dialog helper functions

- src/renderer/components/output.tsx
- tests/renderer/components/output-spec.tsx
Just a small piece of dead code removal.
`CommandsProps.editorDidMount` exists because the code was cloned from the sibling `EditorProps` class; however, since `editorDidMount` is never using for outputs, it's dead code there and can be removed.
_edit:_ Coveralls is just angry because tested code is being removed. :stuck_out_tongue:
> refactor: remove unused output.editorDidMount

- src/renderer/components/dialog-add-version.tsx
- src/renderer/versions.ts
- tests/renderer/components/__snapshots__/dialog-add-version-spec.tsx.snap
- tests/renderer/components/dialog-add-version-spec.tsx
Co-authored-by: VerteDinde <vertedinde@electronjs.org>
Users can be confused when adding a local electron build using the same folder path as a previously added (but not removed) build.
current behaviour checks that the path has been added before and ignores it, without feedback to the user.
This fix aims to resolve any user confusion as to why their local electron build "did not upload"
> fix: add dialog box for when user adds duplicate local electron builds

- src/renderer/editor-mosaic.ts
Change EditorMosaic.layout to be an arrow function so that the proper `this` context is baked in.
Fixes #751.
This [resize handler in app.tsx](https://github.com/electron/fiddle/blob/master/src/renderer/app.tsx#L224) is where the bad call was coming from.
I tried a few ways to try to trigger the resize handler in jest to add a regression test here, but wasn't able to find the right recipe. :man_shrugging:
> fix: editorMosaic.layout() called w/ wrong context

- src/utils/read-fiddle.ts
- tests/utils/read-fiddle-spec.ts
- tsconfig.json
No feature changes.
This is a small refactor to try to reduce startup jank by making some previously-blocking calls yield.
*edit:*  read-fiddle.ts is still at 100% coverage and the LOC in src/ did not change. I don't know what Coveralls is complaining about. :thinking:
> refactor: remove Sync() calls from readFiddle()

- src/renderer/editor-mosaic.ts
Fixes #771 by making `EditorMosaic.resetLayout()` an arrow function so `this` should always be good.
> fix: cannot read property 'set' of undefined

- package.json
- yarn.lock
Startup time (as measured by reload) is faster than in 11.
For reasons I haven't tracked down yet, bumping to 13 causes the main window to flash white for a moment, so using 12 in this PR.
> chore: bump electron dep to 12.0.14

- src/renderer/editor-mosaic.ts
- tests/renderer/editor-mosaic-spec.ts
Fixes #768.
This fixes at least one cause of the `added Editor for unexpected file` errors showing up in Sentry. All the ones I see in Sentry look like this, so maybe it fixes them all.
- Fix a logic error in EditorMosaic.set() that accidentally remembered some unwanted files.
- Fix the test in editor-mosaic-spect.ts which did check for this, but didn't test under enough different conditions.
> fix: EditorMosaic safeguard against unwanted files

- src/renderer/versions.ts
This PR changes the number of supported releases from 3 to 4 to reflect the change in Electron's release cadence
> docs: update number of supported versions to reflect release cadence migration

- src/main/ipc.ts
- tests/mocks/electron.ts
Ensure there's only ever one GET_APP_PATHS handler at a time.
Fixes #765.
> fix: 'second handler for GET_APP_PATHS' err dialog

- src/renderer/versions.ts
- src/utils/sort-versions.ts
- tests/utils/sort-versions-spec.ts
Fix the version sorting algorithm so that the progression is nightly > alpha > beta > stable. This is important for bisection and useful in the drop-down version list too.
Fix filtering by including alphas in `ElectronReleaseChannel.beta`.
We want sorting / filtering to work, but adding a separate alpha release channel would be overkill IMO since alphas will be a one-time process for Electron 15.
> feat: support Electron 15 alpha releases

- src/renderer/components/commands-action-button.tsx
- tests/renderer/components/commands-publish-button-spec.tsx
Fixes #776 reported by both @nornagon and @miniak. The problem was that we were trying to submit empty files, which fails.
Add a regression test. The tests already checked for missing files; now also test for existing-but-empty files.
*edit:* no newly-untested LOC or logic branches. Coveralls' negative report is because the code size decreased by a few lines.
> fix: publishing gists with empty files to Github

- src/renderer/editor-mosaic.ts
- tests/renderer/editor-mosaic-spec.ts
Fixes #774 reported by @erickzhao.
When loading a new fiddle, if it has a filename that was in the previous fiddle too, EditorMosaic tries to recycle the MonacoEditor allocated to that file. Unfortunately, does this even if the new fiddle's file is going to be hidden. This corrupts the internal state.
In the repro case described in 744, the state was corrupted when _loading_ https://gist.github.com/e27800f409182981352b68a90690c4a6 because its preload & renderer files were hidden, causing the inconsistent internal state described above. The error that appears when loading another fiddle _after_ that gist is a symptom of that already-inconsistent state.
This PR fixes that bug and adds Yet Another Regression Test for this state too. :slightly_smiling_face:
> fix: editors sometimes disappear when loading new fiddle

- src/renderer/content.ts
- src/renderer/versions.ts
- tests/renderer/versions-spec.ts
- `getKnownVersions()` returns a `Version[]`
- `getElectronVersions()` returns a `RunnableVersion[]`
`RunnableVersion`s are more expensive to create because calculating the RunnableVersion.state property requires checking the disk to see if the version's exec file is present.
`isReleasedMajor()` and `getOldestSupportedVersion()` were using `getElectronVersions()` but don't need that state info. This PR changes them to call `getKnownVersions()` instead, which eliminates 2,057 calls to `fs.existsSync()`. during startup. :tada: 
Also, I think the old code used the wrong function because I was unclear on the meaning of `getKnownVersions()` -- local versions are also 'known' to Electron Fiddle. This PR renames it as `getReleasedVersions()` for clarity.
*Side thought:* if Versions were a …
> perf: prefer getKnownVersions() over getElectronVersions().

- src/renderer/versions.ts
- tests/renderer/versions-spec.ts
On first start, we have to pick which version of Electron to first use. This PR changes behavior to choose the latest stable release.
Sibling PR to https://github.com/electron/fiddle/pull/782 . They're related but can land separately.
> refactor: default to latest stable version

- src/renderer/components/version-select.tsx
- tests/renderer/components/version-select-spec.tsx
Closes https://github.com/electron/fiddle/issues/785.
The previous logic keyed off index only - assuming that queries passed would be numeric and as such we should be unilaterally choosing the first index of the (presumed) number.
However, when the user passes something like `nightly`, this would result in a poorer UX because it would make it so that versions like `9.0.0-nightly.12345678` would show up _before_  `14.0.0-nightly.12345678` since the index would be lesser for the first version.
This corrects that by adding in some logic for non-numeric queries.
> fix: sorting for non-numeric queries

- src/renderer/components/editors.tsx
Refs https://github.com/electron/fiddle/issues/770 - We can try to pin down the actual command issues later but this for now ameliorates the error.
> fix: handle invalid monaco editor command

- src/renderer/components/settings-electron.tsx
- src/renderer/content.ts
- src/renderer/state.ts
- src/renderer/versions.ts
- tests/mocks/versions-mock.json
- tests/renderer/components/settings-electron-spec.tsx
- tests/renderer/state-spec.ts
- tests/renderer/versions-spec.ts
- remove getUpdatedElectronVersions(); use fetchVersions() instead since it returns a Version[] instead of the more expensive RunnableVersion[]. Similar to #781.
- don't use semver.parse() if we only need the major version number.
renderer startup in master: 4193 `semver.SemVer` objects created, 2066 `fs.execSync()` calls in `getVersionState()`
renderer startup here: 1033 `semver.SemVer` objects created, 1016 `fs.execSync()` calls in `getVersionState()`
> perf: faster version tests.

- src/utils/get-version-range.ts
- tests/utils/get-version-range-spec.ts
Closes https://github.com/electron/fiddle/issues/790.
Updates our logic in `get-version-range` to augment `semver.compare`. The new logic takes into account Electron's prerelease tag hierarchy, whereby `nightly -> alpha -> beta`.
> fix: proper release sorting in get-version-range

- src/main/command-line.ts
- tests/main/command-line-spec.ts
Does what it says on the tin.
When running in batch mode -- e.g. launched on the command line to do an autotest or autobisect operation and then exit -- be more explicit about the exit code in the log so that anyone reading the session logs via BugBot can see it.
> feat: before exiting, log the exit code.

- src/renderer/components/settings-electron.tsx
- tests/renderer/components/settings-electron-spec.tsx
Fixes an issue where deleted local Electron versions would show up as non-downloaded versions in settings.
Before:
After:
> fix: handle missing local version binaries

- src/utils/get-version-range.ts
- src/utils/sort-versions.ts
- tests/utils/get-version-range-spec.ts
- tests/utils/sort-versions-spec.ts
Follow-up to https://github.com/electron/fiddle/pull/797#pullrequestreview-711926906 - merges and cleans up similar sorting logic in `src/utils/get-version-range.ts` and `src/utils/sort-versions.ts`
Notes:
* In looking at the logic in https://github.com/electron/fiddle/pull/786 i think it's semantically different enough to stay as-is for now 🤔
* Added an extra filter to the logic in `sortVersions` to remove versions that don't coerce to a valid semver version - there's no use case I see where we'd want to keep them around so imo it's better just to get rid of them.
* Tests updated accordingly
> refactor: merge version sorting logic

- src/main/context-menu.ts
This PR addresses: #770 
The "go to definition" and "peek definition" context menu functionalities seem to not have worked for a while. Running `editors.getSupportedActions` seems to produce a list that did not contain the actions previously mapped to these context menu items. These new action events should be more appropriate!
https://user-images.githubusercontent.com/33054982/127208466-b5840054-5e27-494f-bcd1-a65e3f06b362.mov
> chore: fix context menu goto and peek definition

- src/renderer/components/output.tsx
Looks like this is a tracer call to console.log() that was accidentally included in https://github.com/electron/fiddle/pull/796
> chore: remove accidentally-included console.log() call

- src/renderer/state.ts
Fixes #826.
When setVersion() gets an invalid or unusable version, walk through showVersionsToShow to find a version that will be usable. Use the first one that's found, or do nothing if no usable version can be found.
> fix: infinite loop in AppState.setVersion()

- tests/utils/get-package-spec.ts
Tests only. No functional changes.
Part of a series of small refactors to reduce copy-paste that's built up over time in tests/.
This PR is for get-package.
> test: reduce copy-paste in get-package

- src/renderer/components/dialog-add-version.tsx
Looking for feedback on this as well as code review -- this PR is better for _my_ workflow but I'd like another opinion not just on the code but on the idea, since other people may have other workflows.
One small annoyance is that Electron Fiddle names all my local builds something like `src/out/release` or `src/out/testing`. Since `src/out/` is literally in every local build, it's not the most useful fragment to identify a version. Usually I keep checkouts in something like `.../main/src/out/...` or `.../13/src/out/...` so that parent directory would be more helpful.
When given a path like `/home/username/electron/gn/main/src/out/testing`, instead of returning `src/out/testing`, this PR returns `gn/main - testing`.
So, like I say -- this is helpful _to me_, but I'd like a sanity check …
> feat: more descriptive local version names

- .github/workflows/build.yaml
Attempt at fixing #749. Not sure if it'll work, as we'll only see if the flake rate on macOS decreases through CI runs.
> build: increase yarn network timeout

- tools/check-links.js
Noticed this when I ran `yarn lint` (I run Node 12 by default for all of the Electron tooling development). It looks like `fs/promises` was added in Node 14?
Alternatively, we could just require the development of the repo to use Node >= 14.
> chore: allow check-links tool to run in Node 12

- .eslintrc.js
- package.json
- static/electron-quick-start/main.js
- static/show-me/ipc/main.js
- static/show-me/ipc/preload.js
- static/show-me/webcontents/main.js
The lint-staged pre-commit rules ran both ESLint and standard on JS files in `static/show-me`, with ESLint (+ prettier) always winning (and contradicting `yarn lint`). This PR makes ESLint ignore the `static/` folder and fixes up any files that were formatted with prettier due to lint-staged.
> chore: make sure static JS files use standard

- .github/dependabot.yml
- .github/workflows/build.yaml
- .github/workflows/electron-releases.yml
* Adds Dependabot config for GitHub Actions
* I deliberately didn't want to update JS dependencies here. If we want to do that we should tackle that in a separate PR (and also discuss whether those PRs should get auto-merged when tests pass)
*  Refactor the setup-node/cache config since setup-node now comes with caching built-into it
* Add yarn network timeout from #833 to the build step (it failed [here](https://github.com/electron/fiddle/runs/3326328222?check_suite_focus=true))
> ci: refactor GitHub Actions for caching / network timeouts

- src/renderer/state.ts
Fixes an issue where missing local versions wouldn't be removed from the UI because we branched on a conditional (version state being ready) that wouldn't apply to local versions (they'd be unknown).
> fix: removing a missing local version from UI

- .github/workflows/build.yaml
This is the [recommended](https://classic.yarnpkg.com/en/docs/cli/install/) way to run Yarn in CI, in order to catch pull requests like #813 that leave package.json and yarn.lock out of sync.
> ci: Run yarn with --frozen-lockfile

- forge.config.js
I was in the middle of fixing up the protocol handler guide in the Electron docs and I realized that Fiddle's URLs don't work on Linux. It turns out that you need to [add an `x-scheme-handler` to the `MimeType`](https://specifications.freedesktop.org/shared-mime-info-spec/0.21/ar01s02.html#idm45917071429120) in the Electron app's `.desktop` file (which is generated by the various `electron-installer-*` modules for Linux).
While I was in there I synced the common config for the Linux makers (the rpm was missing the icon).
I tested this on Ubuntu 18.04 by running:
```shell
yarn make --targets=@electron-forge/maker-deb
sudo apt install ./out/make/deb/x64/electron_fiddle_0.26.0_amd64.deb
```
...and then loading an Electron Fiddle URL.
> fix(linux): enable protocol handler for deb/rpm

- package.json
- src/main/windows.ts
- tests/main/windows-spec.ts
- yarn.lock
As a side effect, this PR hides the window by default (see #822). We already had a handler to `show()` the window when the `webContents` were ready, but it seems like the `show: false` by default was inverted in https://github.com/electron/fiddle/commit/a6e6fad4d901a16c7d76569c627137bb72ef7a11.
This sets it back to avoid the flash of white content described in the aforementioned issue.
> chore: upgrade to Electron 15

- src/renderer/app.tsx
- src/renderer/binary.ts
- src/renderer/components/commands-runner.tsx
- src/renderer/state.ts
- tests/mocks/state.ts
Adds the ability for Fiddle to show an offline status and cancel a download if it loses internet connection. Fixes an issue i've run into before where if the internet dies in the middle of a download, Fiddle goes into "Checking Status" and stays there forever.
> feat: handle offline status in version downloads

- src/renderer/components/sidebar-file-tree.tsx
Fixes an issue where if a user tried to make a new file with a disallowed file extension there would be a silent failure.
After this fix:
> fix: silent failure on file creation

- src/renderer/components/sidebar-file-tree.tsx
- src/renderer/remote-loader.ts
- tests/renderer/components/__snapshots__/sidebar-file-tree-spec.tsx.snap
In the new file tree layout, it's not always clear to a new user what each button does. This adds some tooltips after a brief delay to make clearer what the function of each button is.
> chore: add tooltips to file tree actions

- src/less/components/settings.less
The settings dialog uses `overflow: scroll`, which always renders scrollbars even when they're not needed (and sometimes, because the scrollbars do get rendered and they take up space, they cause scrolling to be needed). On operating systems that show scrollbars (e.g. not mac), this is what that looks like:
By switching to `overflow: auto`, we only render scrollbars when needed, making everything look a little nicer, only the elements that need scrollbars get them:
> style: switch from overflow: scroll to overflow: auto

- static/show-me/notification/index.html
- static/show-me/notification/main.js
- static/show-me/notification/preload.js
- Part of #725 
- The current 'Show Me' > Notification example does not work
- Updating to use `nodeIntegration: false` and `contextIsolation: true` similar to https://github.com/electron/fiddle/pull/837
> fix(show-me/notification): refactor to use current Electron security defaults

- static/show-me/screen/index.html
- static/show-me/screen/main.js
- static/show-me/screen/preload.js
- static/show-me/screen/renderer.js
- Part of https://github.com/electron/fiddle/issues/725
- The current 'Show Me' > Screen example does not work
- Used IPC to get `screen.getAllDisplays()` values from `main.js`values
- `screen` was showing as null in the `preload.js` page
- If there is a better way to achieve this? 
**Preview of code change working**
> fix(show-me/screen): refactor to use current Electron security defaults

- .github/workflows/build.yaml
- package.json
Note: this removes the unsupported Linux ia32 release binary.
> chore: release v0.27.0

- src/renderer/binary.ts
Fixes #909.
This fixes the current timeout behavior, which will cause a timeout for any request lasting over 10 seconds, even if it is an in-progress download which is simply a bit slow. Change bumps time outs to 15s, and breaks out [individual `got` timeout values](https://github.com/sindresorhus/got/blob/main/documentation/6-timeout.md) since `socket` is the timeout that makes the most sense to set (resets time out each time data is received), but once you break out one timeout you need to give the others values as well or they will have no timeout.
I tested these changes on macOS with the "Network Link Conditioner" so that I could try different network conditions. With these changes it could successfully download with the "3G" profile, and it could start downloading with the "Edge" and …
> fix: don't timeout a slow version download

- src/renderer/state.ts
- tests/renderer/state-spec.ts
The output was changed in https://github.com/nodejs/node/commit/f3e107aeef2f75cb3a705fd15260f65dd77e78d4 and was first released in v10.0.0, so every supported version of Electron uses the up-to-date version of the output.
> fix: update inspector output from Node

- src/renderer/state.ts
- tests/renderer/state-spec.ts
Fixes #699.
On Windows, `console.log("Hello World")` will send `Hello World\n` to `pushOutput`, so it was being buffered indefinitely, since it would never include `\r\n` which is when the buffer would be outputted.
This PR should handle both `\r\n` and `\n` line endings on Windows.
cc @felixrieseberg
> fix: show console.log output on Windows

- yarn.lock
running `yarn start` on master currently gives a bunch of warnings:
<details>
<summary>caniuse-lite is outdated. Please run: `npx browserslist@latest --update-db`</summary>
```
> ℹ Fetching contributors
⠸ Building main.tsx...Browserslist: caniuse-lite is outdated. Please run:
npx browserslist@latest --update-db
>
> Why you should do it regularly:
https://github.com/browserslist/browserslist#browsers-data-updating
⠴ Building ipc.ts...Browserslist: caniuse-lite is outdated. Please run:
npx browserslist@latest --update-db
>
> Why you should do it regularly:
https://github.com/browserslist/browserslist#browsers-data-updating
⠦ Building ipc.ts...Browserslist: caniuse-lite is outdated. Please run:
npx browserslist@latest --update-db
>
>Why you should do it regularly: …
```
> chore: run "npx browserslist@latest --update-db" to fix console warnings

- src/main/command-line.ts
- tests/main/command-line-spec.ts
Fixes #900 #902
Previously, `processCommandLine()` would throw if any unknown args were passed in via CLI. However, this approach broke existing functionality for users needing to pass flags into the Electron app (e.g. `--no-sandbox`).
With the existence of `fiddle-core`, I'm not sure how needed the CLI within the Fiddle app is, but this approach reduces the LOC needed in a fix.
> fix: don't exit fiddle if passing flags to binary

- src/renderer/app.tsx
- src/renderer/components/editors.tsx
- src/utils/get-package.ts
Closes https://github.com/electron/fiddle/issues/942.
Also cleans up some other cruft.
> fix: clear installed modules on new fiddle

- src/less/components/editors.less
fixed: https://github.com/electron/fiddle/issues/929
related PR: https://github.com/electron/fiddle/pull/294
Sropped working Reason:
> editor-id changed
```diff
- main
+ main.js
- renderer
+ renderer.js
- html
+ index.html
- preload
+ prelaod.js
```
> fix(monaco): tooltips clipping by other editors

- src/renderer/remote-loader.ts
- tests/renderer/remote-loader-spec.ts
Closes https://github.com/electron/fiddle/issues/962.
Fixes an issue whereby Fiddle assumes [dependencies are non-null](https://github.com/electron/fiddle/blob/a593bb6ef05af9915ac6cf6ab27128a4f3a6d908/src/renderer/remote-loader.ts#L117-L120) and errors in the case where there are no dependencies or there are only devDependencies.
> fix: loading gists with deps/devDeps

- src/renderer/remote-loader.ts
- tests/renderer/remote-loader-spec.ts
- tests/setup.js
Closes https://github.com/electron/fiddle/issues/968.
This PR enables users to preset the Electron version from package.json in a gist if they so choose.
Previously, if a user loaded https://gist.github.com/t57ser/ce254e6e2e828949809bf872ed4168b6 the version number that ran the fiddle would remain the same, even though the Fiddle Gist specifies `v17.0.0`. Loading this gist should take that version into account, and change the version to match what's in the `package.json`.
I plan to follow this up with https://github.com/electron/fiddle/issues/966.
> feat: set Electron version from gist

- .github/workflows/electron-releases.yml
#937 removed `tests/fixtures/releases-metadata.json` but didn't remove it from the weekly releases updater action, which caused the action to fail.
CC: @ckerr
> ci(electron-releases): remove obsolete file from script

- src/renderer/runner.ts
- tests/renderer/runner-spec.tsx
Closes https://github.com/electron/fiddle/issues/957.
Signals like SIGSEGV should be marked as a bisection failure. This corrects that issue.
> fix: signal exit should be a failure

- src/renderer/components/commands.tsx
See: https://github.com/electron/fiddle/pull/979#discussion_r820088062
If developer machine is `macOS`, will update `tests/renderer/components/__snapshots__/commands-spec.tsx.snap`. This will cause the tests in the CI to fail.
> refactor(test): improve commands snapshots

- tools/check-links.js
Making `check-links` more stable
See:
- https://github.com/electron/fiddle/runs/5445191754?check_suite_focus=true#step:5:13
- https://github.com/electron/fiddle/runs/5445670111?check_suite_focus=true#step:5:14
> chore(scripts): add fetch retry logic in check-links

- src/renderer/file-manager.ts
- src/utils/read-fiddle.ts
- tests/mocks/remote-loader.ts
- tests/renderer/file-manager-spec.ts
Closes https://github.com/electron/fiddle/issues/966.
Closes https://github.com/electron/fiddle/issues/965
Follow up to https://github.com/electron/fiddle/pull/967 - ensure that local fiddles loaded from disk also respect modules and the version of Electron optionally specified in `package.json`
> feat: local fiddles respect `package.json`

- src/less/components/commands.less
- src/renderer/components/commands.tsx
This PR Fixes #985. Here's a pic of how the toolbar looks after the changes that have been made.
> fix: restore commands padding on Windows/Linux

- src/main/protocol.ts
- tests/main/protocol-spec.ts
Fixes #1007.
Previously when loading fiddle and if a fiddle is already loaded then the window doesn't come to foreground. This behaviour is seen on windows. This PR fixes that issue.
**Quick Demo :**
https://user-images.githubusercontent.com/51379307/159056900-837972f6-0373-426a-977f-4dea867ffac1.mp4
I am new here and my solution may not be the best and efficient one,😅 So I request you to provide the valuable feedback to me.
**What I did**
I used the `BrowserWindow` API and called its show method whenever any potential protocol launch occurs.
> fix: focus the window when loading fiddle with protocol

- src/less/components/dialogs.less
Fiex #1024
PR #961 in order to use WCO on macOS then remove old style code, but there is still some old style was left behind
old style code: https://github.com/electron/fiddle/commit/befa3192f4f12a561e12c56c669e9dfea6caae00.
remove old style address: https://github.com/electron/fiddle/pull/961/files#diff-aa82273862a162ec96de7bbd7bbb5fbcbd412d5f577fc209fafcb7ad943dc2f9
> fix(style): Preference Page style is incorrect on macOS

- src/main/main.ts
Closes #1023 
NodeJs module.parent is deprecated and nodejs recommends module.children which does same thing as module.parent.
> chore: Remove old module.parent deprecation with require.main

- package.json
- yarn.lock
Follow up to #975. Tested locally on macOS Monterey (12.3.1)
> chore: update to Electron 15.5.2

- src/renderer/file-manager.ts
- src/utils/read-fiddle.ts
- tests/renderer/file-manager-spec.ts
Related PR: https://github.com/electron/fiddle/pull/969
The fix works fine locally.
---
This is because the `addFile` function receives the result of the `readFiddle` function. And `addFile` does not support handling `package.json` files
https://github.com/electron/fiddle/blob/b21e70001412666ff1ec6deaefef881271f50bff/src/renderer/editor-mosaic.ts#L116-L119
The order of the files is.
```
0: "index.html"
1: "main.js"
2: "package.json"
3: "preload.js"
4: "renderer.js"
```
Throw error when the file is `package.json`, `preload.js` and `renderer.js` will not be further processed by the addFile function
---
The `readFiddle` function is called in a number of places and we cannot be sure if it affects other functions.
So I've made this compatible here by adding a default parameter to `readFiddle`.
> fix: preload.js and renderer.js files gone on monaco

- package.json
- src/ambient-modules.d.ts
- src/utils/exec.ts
- tests/utils/exec-spec.ts
- yarn.lock
For some strange reason `await shellPath()` will no longer resolve on my macOS device. This fixes that.
> fix: use shell-env to fetch PATH

- src/less/components/commands.less
This is caused by https://github.com/electron/fiddle/pull/1019
Problem preview:
> fix: electron settings style incorrect

- .lessrc
- package.json
- src/less/blueprint.less
BlueprintJS has its own Less pre-processor colour variables (e.g. `@white`, `@red`, `@black`). https://blueprintjs.com/docs/#core/colors
We currently don't use any of them, so I don't think we've ever run into this error. However, trying to add any of these variables will lead to a Less error on main.
```json
{
message: 'variable @dark-gray1 is undefined',
stack: undefined,
name: 'Error',
type: 'Name',
filename: '/Users/erick.zhao/Developer/electron/fiddle/src/less/main.less',
index: 1100,
line: 79,
column: 9,
callLine: NaN,
callExtract: undefined,
extract: [
'  background: @background-1;',
'  color: @dark-gray1;',
'  font-size: 10px;'
],
fileName: '/Users/erick.zhao/Developer/electron/fiddle/src/less/root.less'
}
```
After experimenting a bit, I found that:
1. We have a `yarn less` …
> fix(styles): support blueprint variables

- src/utils/disable-download.ts
- tests/utils/disable-download-spec.ts
Windows arm64 builds of Electron were only added in [v6.0.8](https://github.com/electron/electron/releases/tag/v6.0.8) by [#20113](https://github.com/electron/electron/pull/20113) and [v7.0.0](https://github.com/electron/electron/releases/tag/v7.0.0) by [#20112](https://github.com/electron/electron/pull/20112)
Follow-up to #1019
> fix: disable downloads for Electron below 6.0.8 and 7.0.0 on Windows arm64

- src/renderer/components/settings.tsx
- tests/renderer/components/__snapshots__/settings-spec.tsx.snap
> refactor: improve setting close icon size

- package.json
- yarn.lock
Tested locally on macOS Monterey (12.3.1) and Windows 11.
> chore: update to Electron 17.4.1

- src/renderer/components/commands.tsx
- tests/mocks/state.ts
- tests/renderer/components/__snapshots__/commands-spec.tsx.snap
- tests/renderer/components/commands-spec.tsx
Reason: 
* I've received some feedback from users who say they never knew fiddle had a settings page.
> For the above reasons, it would be more user-friendly for us to add a button.
Preview image:
Review video:
https://user-images.githubusercontent.com/8198408/164957471-7e7cc7cd-b468-4628-ae16-8f64320ee1d4.mp4
> feat: add setting icon to commands UI

- src/renderer/components/commands.tsx
- tests/renderer/components/commands-spec.tsx
In the previous situation, trying to copy `gist URL` always resulted in accidentally changing the window size.
Before:
https://user-images.githubusercontent.com/8198408/165265529-4d2ba6c8-0315-4e08-9b7a-cacb3166ce90.mp4
After:
https://user-images.githubusercontent.com/8198408/165264808-78ec68ef-34cc-4e10-9bbf-fed2d25b2fa0.mp4
> refactor: improve gist input user experience

- tools/contributors.js
the default value is 30.
ref: https://docs.github.com/en/rest/projects/collaborators#list-project-collaborators
> fix: contributors display is incomplete

- src/main/protocol.ts
Described the changes in commit description as well!
Basically,
* The [`Tooltip`](https://blueprintjs.com/docs/#core/components/tooltip) and [`Popover`](https://blueprintjs.com/docs/#core/components/popover) components are no longer maintained in `@blueprintjs/core` package and are shifted to `@blueprintjs/popover2`.
* The same goes for `nodeUrl.parse` which throws an deprecation warning - https://nodejs.org/api/url.html#urlparseurlstring-parsequerystring-slashesdenotehost. Instead used the node `URL` API call for the same as suggested in docs.
Tested the changes using `yarn test`.
> refactor: remove deprecated functions calls.

- src/less/components/dialogs.less
- src/renderer/components/commands-version-chooser.tsx
Closes https://github.com/electron/fiddle/issues/1066.
Refs https://github.com/electron/fiddle/issues/1031.
We shouldn't be messing with the z-indexes - instead we should simply disable the version chooser if Settings panes are open.
> fix: close version chooser if settings open

- src/renderer/runner.ts
- src/renderer/state.ts
- tests/mocks/state.ts
- tests/renderer/runner-spec.tsx
Closes https://github.com/electron/fiddle/issues/1035.
Takes the same approach as if a user tried to switch to a nonexistent version.
> fix: fallback if current version doesn't exist

- .github/workflows/build.yaml
Due to an update bug involving multiple architectures and Windows, stop building arm64 builds for Windows to prevent wrong architecture updates.
> chore: stop building Windows on arm64

- src/main/devtools.ts
Closes https://github.com/electron/fiddle/issues/454
Refs https://github.com/MarshallOfSound/electron-devtools-installer/issues/143
After:
This might not be the best long-term fix but.....it solves the immediate issue and devtools show up again.
> fix: react devtools not loading

- src/renderer/state.ts
- tests/renderer/state-spec.ts
Closes https://github.com/electron/fiddle/issues/1065.
Removes extra cruft around title such that it only flags save state. The rest is, imo, not particularly necessary and results in buttons being cut off.
> chore: remove extraneous text from title

- src/renderer/state.ts
Fixes a potential infinite loop when the directory containing a local electron version was removed.
https://github.com/electron/fiddle/blob/d41d5f6319cebf5fcb79f092dbbed84ef404d48a/src/renderer/state.ts#L339 would call https://github.com/electron/fiddle/blob/d41d5f6319cebf5fcb79f092dbbed84ef404d48a/src/renderer/state.ts#L596 which would correctly indicate that the version was invalid. However, we would then call https://github.com/electron/fiddle/blob/d41d5f6319cebf5fcb79f092dbbed84ef404d48a/src/renderer/state.ts#L600 which was **incorrectly** returning true because it was testing for truthiness of an object instead of whether https://github.com/electron/fiddle/blob/d41d5f6319cebf5fcb79f092dbbed84ef404d48a/src/renderer/state.ts#L561 was returning an error or valid version. Correct this by …
> fix: infinite loop on missing local version

- .github/workflows/build.yaml
- .github/workflows/electron-releases.yml
Switch to the current Node LTS, newer packages don't support back to 12.x anymore.
This popped out of #1109.
> chore: use Node v16.x for GitHub actions

- src/utils/read-fiddle.ts
Subtle bug got introduced by #1119, due to shifting the version of `graceful-fs` from 4.2.6 to 4.2.10. That version of `graceful-fs` [doesn't play nice with Electron](https://github.com/isaacs/node-graceful-fs/issues/223). Rather than muck around with versions of `graceful-fs` (transitive dependency), just use a workaround for the issue until it is fixed in a later version of `graceful-fs`.
> fix: work around bug in readdir in graceful-fs

- src/renderer/content.ts
- src/renderer/templates.ts
- tests/setup.js
- tools/webpack/common/webpack.plugins.js
Conversations - https://electronhq.slack.com/archives/C03G7RWF6KH/p1658190886702879.
Basically, for some reason (to debug later) github action production release incorrectly computes `STATIC_DIR` global variable defined in webpack plugins.
> build(webpack): remove webpack definePlugin pointing to static folder

- tests/setup.js
- tsconfig.json
A minor commit which - 
* Removes unused `path` variable in setup.js (had to be removed in #1138)
* Deduplicates the `resolveJsonModule` in tsconfig (was introduced by #988 as well)
> refactor: remove dead code

- README.md
The screenshots in the README documentation have not been updated for a number of years and we should let new users know about our latest changes.
> docs: update readme screenshot

- package.json
- yarn.lock
Tested locally on macOS Monterey (12.5.1) and Windows 11.
> chore: update to Electron 18.3.9

- package.json
- yarn.lock
Tested locally on macOS Monterey (12.5.1) and Windows 11.
> chore: update to Electron 20.1.1

- src/renderer/components/commands-address-bar.tsx
- src/renderer/components/settings-execution.tsx
- tests/renderer/components/__snapshots__/settings-execution-spec.tsx.snap
issue: https://github.com/electron/fiddle/issues/1088
Form controls should have associated labels to [improve application accessibility](https://dequeuniversity.com/rules/axe/3.5/label). This PR adds aria-labels for form controls that currently do not have visible `label` attributes.
https://dequeuniversity.com/rules/axe/3.5/label
> style: add aria-labels for label-less forms

- src/renderer/components/commands-action-button.tsx
- src/renderer/components/settings-general-github.tsx
- src/renderer/constants.ts
- src/renderer/state.ts
- tests/mocks/state.ts
- tests/renderer/components/__snapshots__/commands-publish-button-spec.tsx.snap
- tests/renderer/components/__snapshots__/settings-general-github-spec.tsx.snap
- tests/renderer/components/commands-publish-button-spec.tsx
- tests/renderer/components/settings-general-github-spec.tsx
https://github.com/electron/fiddle/issues/1176
This PR adds a checkbox to the Github settings to allow users to select whether they want to publish their gist as a revision of the default Fiddle startup editor values. This is useful when users submit issues, with Fiddle gists as repro examples: this change will allow maintainers to quickly spot diffs easier.
✅  Added option in settings to include checkbox
✅    Added tests to expand coverage (wip)
✅  Validated on Mac, (needs to be tested on Windows and Linux)
> feat: add publishGistAsRevision()

- src/renderer/components/settings.tsx
- tests/renderer/components/settings-spec.tsx
Minor commit to fix #1070.
Edit: Not sure on how to mock the `contextMenu` behavior.
> fix: disable right click contextMenu in settings page

- src/less/components/sidebar.less
- src/renderer/components/sidebar-file-tree.tsx
- tests/renderer/components/__snapshots__/sidebar-file-tree-spec.tsx.snap
Fixes: https://github.com/electron/fiddle/issues/1187
Add ability to scroll "Editors" listing by just changing `hidden` to `auto` for simplicity (see details of other approach below which feels a bit much in terms of code changes but if the user experience s more desirable and there are betters ways to improve it, I'll be happy to contiinue investigating with any guidance)
**Preview of change**
* * *
**Preview of other approach**
- I feel the above better in terms of user experience with the top section being static and only scroll the list of files
- It involves CSS overrides including using `!important` as it is overring Blueprint's Collapse component behaviour https://github.com/palantir/blueprint/blob/a7479b73312afba568a41773060c5302ef4f13b5/packages/core/src/components/collapse/collap …
> fix: Allow scrolling in Editors Listing

- tests/renderer/electron-types-spec.ts
There's a CI flake in this test somewhere, I'm taking a stab at this being it.
Unfortunately some of the code under test can silently fail (will just `console.debug` a message) so if there are failures happening as a result of this await not happening, you wouldn't see it unless an `expect` fails.
> test: await electronTypes.setVersion() in afterEach

- src/renderer/components/commands-action-button.tsx
Typings for octo are accurate now.
> chore: remove 'as any' typing

- src/renderer/electron-types.ts
- tests/renderer/electron-types-spec.ts
Found the race condition that's been haunting the tests.
> fix: race condition when getting Node types

- src/renderer/electron-types.ts
This was throwing away the Electron typings when adding the Node ones. The previous typings are already disposed (via `clear()`) in `setVersion`, so these calls to `dispose` were redundant anyway.
Tests may flake until #1220 is merged.
> fix: don't unset Electron typings when setting Node typings

- src/renderer/components/commands-action-button.tsx
- tests/renderer/components/commands-publish-button-spec.tsx
Fixes the Gist publish process continuing even if the token fails to authenticate, causing this situation:
> fix: don't continue Gist publish if authing token fails

- CONTRIBUTING.md
- README.md
- SECURITY.md
Also removes the reference to "Node Security Project" since that was shut down years ago and the link is dead.
> docs: update links

- package.json
- yarn.lock
Tested locally on macOS Monterey (12.6.2) and Windows 11.
> chore: update to Electron 22.0.1

- .github/workflows/build.yaml
Not being maintained at the moment.
Reuses the existing `timheuer/base64-to-file` action so we have fewer external actions.
> ci: remove usage of 1arp/create-a-file-action

- src/less/main.less
- src/renderer/components/header.tsx
- src/renderer/components/output-editors-wrapper.tsx
Hello there,
Thought I'd try look into the issue (#1083) with tab focus misbehaving when the settings page is open.
I can confirm those tooltips come about because tabbing through the settings page eventually runs out of elements and goes on to tab through elements that are part of either the header or editor area.
The least invasive solution I could think of is to ensure the header and editor area elements are made invisible. `display: none` is a bit more destructive than `visibility: hidden`, because the former may interfere with components not rendering at all and potentially losing their state.
Now, I'm not awfully familiar with MobX, but I tried my best to work in some changes that do what I described above.
Happy to take feedback and revise (or add a test, which I couldn't work out …
> fix: tab focus for settings page

- static/show-me/clipboard/index.html
- static/show-me/clipboard/main.js
- static/show-me/clipboard/preload.js
- static/show-me/clipboard/renderer.js
Fixes #1239.
Electron v20.0.0 enabled renderer sandboxing by default and as a result clipboard can't be used in preload.js anymore.
> fix(show-me): use IPC for clipboard example

- src/renderer/components/settings-electron.tsx
- tests/renderer/components/__snapshots__/settings-electron-spec.tsx.snap
`buttonProps.loading` was just showing an indefinite spinner, let's show progress like on `VersionSelect`.
> feat: show version download progress in settings

- .github/workflows/build.yaml
- .github/workflows/electron-releases.yml
- .github/workflows/semantic.yml
Dependabot should be able to handle these and keep them up-to-date while also pinned (and also update the comment).
> ci: pin GH actions SHAs

- src/renderer/components/settings-electron.tsx
- src/renderer/state.ts
- src/renderer/versions.ts
Closes https://github.com/electron/fiddle/issues/1238.
`fiddle-core` was installing versions and activating them regardless of origin - when a version is downloaded from settings it should not be activated.
> fix: don't activate when downloading versions from settings

- src/renderer/components/commands-action-button.tsx
- src/renderer/components/dialog-token.tsx
- src/renderer/components/version-select.tsx
- tests/renderer/components/dialog-token-spec.tsx
- tests/setup.js
For the use cases in Fiddle, `navigator.clipboard` is a drop-in replacement, so switch to it and stop using the `electron` module in the renderer.
> refactor: use navigator.clipboard in renderer

- src/renderer/components/settings-electron.tsx
- tests/renderer/components/settings-electron-spec.tsx
Giving this a more intuitive name, the current one is confusing.
> refactor: rename handleDownloadClick

- src/renderer/components/dialog-token.tsx
- src/renderer/components/settings-credits.tsx
- tests/renderer/components/dialog-token-spec.tsx
- tests/renderer/components/settings-credits-spec.tsx
- tests/setup.js
All `window.open` calls are already denied and opened by `shell.openExternal` by default via `setWindowOpenHandler`, so `shell.openExternal` doesn't need to be used in the renderer.
https://github.com/electron/fiddle/blob/ff0de26376f9f0e17e8e0873ac89282b72933e06/src/main/windows.ts#L89-L92
> refactor: don't use shell.openExternal in renderer

- src/renderer/app.tsx
Looks like any usage of this went dead, I don't see any way it can currently affect anything.
> refactor: don't add platform as class name on app container

- src/renderer/state.ts
Update versions known to `fiddle-core` when updating versions in the UI.
This is a bit of a hack until #1203 is complete.
Fixes #1241.
> fix: keep versions in-sync with fiddle-core

- src/ambient.d.ts
- src/preload/preload.ts
- src/renderer/components/commands.tsx
- src/renderer/npm.ts
- src/renderer/state.ts
- src/utils/disable-download.ts
- src/utils/electron-name.ts
- src/utils/position-for-rect.ts
- tests/mocks/electron-fiddle.ts
- tests/renderer/components/commands-spec.tsx
- tests/renderer/components/dialog-add-theme-spec.tsx
- tests/renderer/components/dialog-add-version-spec.tsx
- tests/renderer/components/dialog-generic-spec.tsx
- tests/renderer/components/dialog-token-spec.tsx
- tests/renderer/components/dialogs-spec.tsx
- tests/renderer/components/tour-spec.tsx
- tests/renderer/npm-spec.ts
- tests/renderer/state-spec.ts
- tests/utils.ts
- tests/utils/disable-download-spec.ts
- tests/utils/electron-name-spec.ts
- tests/utils/position-for-rect-spec.ts
Another step towards cleaning up the code in the renderer, moves usages of `process.arch` and `process.platform` to `window.ElectronFiddle`.
> refactor: don't use `process.arch`/`process.platform` in renderer

- src/renderer/remote-loader.ts
Closes https://github.com/electron/fiddle/issues/1281.
Fixes an issue where if a user tries to load a gist with a package.json using an Electron version too old for or incompatible with the current OS, it is loaded anyway.
After:
<details>
</details>
> fix: remote loader loading incompatible versions

- .gitattributes
Theme of the week is line endings. After #1269, linting on Windows out of the box doesn't work due to ESLint not liking the CRLF line endings. This PR normalizes and enforces LF line endings.
Did an initial commit to show that linting is broken on Windows out of the box: https://github.com/electron/fiddle/actions/runs/4560442995/jobs/8045390014?pr=1293
And the clean lint run on Windows with these changes: https://github.com/electron/fiddle/actions/runs/4560499302/jobs/8045508959?pr=1293
> chore: normalize line endings to LF

- src/renderer/components/version-select.tsx
Nothing major; this is a side-refactor I wrote while looking at something else in Fiddle.
- Add type awareness (IconName) to `getItemIcon()`
- Simplify the logic of `getItemLabel()` and `getItemIcon()` by making a const Record of the InstallState enum types.
> refactor: add type awareness to getItemIcon()

- src/ipc-events.ts
- src/less/main.less
- src/main/main.ts
- src/renderer/app.tsx
- tests/renderer/app-spec.tsx
Currently the main process never sets `nativeTheme.themeSource`, so setting Fiddle to use a dark or light theme, rather than syncing with the system, ends up being out of sync with itself. If your system is set to dark mode, and you set light mode in Fiddle, on Windows 10 the titlebar will stay dark, for example. On macOS things like the background color of context menus will follow the system theme rather than the set theme in Fiddle.
Pretty straight forward fix. Tested on macOS and Windows 10.
> fix: use nativeTheme module

- package.json
This PR bumps Fiddle to v0.32.2. 
This is the first release done on CircleCI, rather than GH Actions.
> chore: release v0.32.2

- package.json
- yarn.lock
Tested on macOS 13.1.
Notable breaking changes in the jump from v22 to v24:
* [Behavior Changed: Draggable Regions on macOS](https://github.com/electron/electron/blob/main/docs/breaking-changes.md#behavior-changed-draggable-regions-on-macos)
* I tested the drag behavior and it seems fine still in Fiddle, but something to watch out for
* [Removed: Windows 7 / 8 / 8.1 support](https://github.com/electron/electron/blob/main/docs/breaking-changes.md#removed-windows-7--8--81-support)
* So we'll be dropping support for those in the next Fiddle release
> chore: update to Electron 24.1.1

- src/ambient.d.ts
- src/ipc-events.ts
- src/main/main.ts
- src/main/templates.ts
- src/preload/preload.ts
- src/renderer/file-manager.ts
- tests/main/templates-spec.ts
- tests/mocks/electron-fiddle.ts
- tests/renderer/file-manager-spec.ts
This is a small transitional PR to make future refactors have smaller diffs.
Can be tested with the "Show Me" menu.
> refactor: move getTemplateValues to main process

- src/renderer/app.tsx
- tests/renderer/app-spec.tsx
Fixes [#1287](https://github.com/electron/fiddle/issues/1287)
This addresses the issue raised [here](https://github.com/electron/fiddle/issues/1287), where closing the last window quits the app after a quit is cancelled. I just added logic that resets the state's isQuitting flag to false when confirmExitUnsaved returns false. Before this, the isQuitting flag remained true whenever a quit with unsaved data was prompted, regardless of whether it was cancelled or not -- this meant that closing the window afterwards would quit the app. 
I added a line to the end of the 'does nothing if user cancels the dialog' test that checks if the flag is reset.
> fix: resets isQuitting flag to false when user cancels dialog

- tests/renderer/app-spec.tsx
- tests/renderer/components/editors-spec.tsx
- tests/renderer/content-spec.ts
- tests/renderer/electron-types-spec.ts
- tests/renderer/file-manager-spec.ts
- tests/renderer/npm-spec.ts
- tests/renderer/state-spec.ts
- tests/renderer/themes-spec.tsx
- tests/utils.ts
- tests/utils/read-fiddle-spec.ts
Most every usage of `Promise.resolve`/`Promise.reject` can be refactored away using Jest's handy helpers, and this simplifies the test code.
> test: refactor usage of Promise.resolve/Promise.reject

- src/renderer/file-manager.ts
- src/renderer/remote-loader.ts
- tests/renderer/remote-loader-spec.ts
In local development, some of us have our testing versions configured to invalid versions of Electron, like `9999.2.1-main` etc. Loading shouldn't totally fail if I try to load a gist made in this scenario - it should just throw up a dialog and fall back.
> fix: fall back on invalid fiddle gist version

- .circleci/config.yml
I believe `load-gh-token` is only needed for the `publish-to-github` job since the others do dry runs and store to the workspace for the `publish-to-github` job.
> ci: simplify release jobs

- .circleci/config.yml
* Adds a CircleCI job to create releases
* Will upload source maps
* Will associate releases with the correct commit
Needs @electron/wg-infra to add a "Sentry Internal Integration" and add the token to the CircleCI environment as `SENTRY_AUTH_TOKEN`.
Refs https://docs.sentry.io/product/releases/setup/release-automation/circleci/
> chore: improve Sentry integration

- src/renderer/components/dialog-add-theme.tsx
- src/renderer/components/settings-general-appearance.tsx
- src/renderer/themes.ts
- tests/mocks/state.ts
- tests/renderer/components/dialog-add-theme-spec.tsx
- tests/renderer/components/settings-general-appearance-spec.tsx
- tests/renderer/themes-spec.tsx
Fixes adding Monaco themes, which currently don't take effect (and logs warnings). Can be tested using a theme from https://github.com/brijeshb42/monaco-themes/tree/master/themes.
Also fixes a couple of other small bugs around themes in general, refactors out common code, and expands test coverage.
> fix: add Monaco theme

- .circleci/config.yml
CircleCI doesn't like having multiple jobs persist the same file: "Concurrent upstream jobs persisted the same file(s) into the workspace". Refs https://app.circleci.com/pipelines/github/electron/fiddle/621/workflows/2f63652c-9b9c-4efd-a870-7b2fb9b3f08c/jobs/1664.
> ci: only persist .webpack on one job

- .circleci/config.yml
Another attempt at fixing the issue in #1329. That solution didn't work because I forgot the jobs are a matrix on architecture, so multiple jobs were still persisting `.webpack`. New solution is to delete the contents of `.webpack` (but have to leave the empty directory or there's a different error) on any non-x64 Linux job.
> ci: another fix for persisting .webpack

- src/ambient.d.ts
`this` slipped into these typings on accident, so cleaning it up.
> chore: cleanup ElectronFiddle.addEventListener types

- src/main/constants.ts
- src/main/content.ts
- src/main/templates.ts
- tests/main/content-spec.ts
- tests/main/templates-spec.ts
Discovered when testing release artifacts for v0.32.3. Tested in both dev mode and production. Since this code was moved to the main process there no longer needs to be a distinction, `__dirname` can be used unconditionally and it will be the right path.
> fix: always use __dirname for STATIC_DIR in main process

- src/main/main.ts
- src/main/templates.ts
No need for the distinction, and gets to drop some `// eslint-disable-next-line` comments.
> chore: don't import from electron/main

- package.json
v0.32.3 failed to launch due to a blocker bug in production mode, trying again with the fix.
> chore: release v0.32.4

- src/ambient.d.ts
- src/interfaces.ts
- src/preload/preload.ts
- src/renderer/app.tsx
- src/renderer/components/commands-action-button.tsx
- src/renderer/components/commands.tsx
- src/renderer/components/settings-general-font.tsx
- src/renderer/file-manager.ts
- src/renderer/state.ts
- src/renderer/task-runner.ts
- tests/mocks/electron-fiddle.ts
- tests/renderer/app-spec.tsx
- tests/renderer/components/__snapshots__/settings-general-font-spec.tsx.snap
- tests/renderer/components/commands-publish-button-spec.tsx
- tests/renderer/components/commands-spec.tsx
- tests/renderer/file-manager-spec.ts
- tests/renderer/remote-loader-spec.ts
- tests/renderer/task-runner-spec.tsx
Final PR in the `ipcRenderer` series. All usage of `ipcRenderer` is now in the preload script, ready for context isolation (still blocked on usage of Node.js APIs).
> refactor: move remaining IPC to preload script

- rtl-spec/commands-bisect.spec.tsx
- src/interfaces.ts
- src/renderer/components/commands-bisect.tsx
- src/renderer/components/commands-runner.tsx
- src/renderer/components/settings-electron.tsx
- src/renderer/components/version-select.tsx
- src/renderer/remote-loader.ts
- src/renderer/runner.ts
- src/renderer/state.ts
- src/renderer/versions.ts
- tests/install-state-spec.ts
- tests/mocks/electron-versions.ts
- tests/mocks/fiddle-core.ts
- tests/renderer/bisect-spec.ts
- tests/renderer/components/commands-runner-spec.tsx
- tests/renderer/components/commands-version-chooser-spec.tsx
- tests/renderer/components/dialog-bisect-spec.tsx
- tests/renderer/components/settings-electron-spec.tsx
- tests/renderer/components/version-select-spec.tsx
- tests/renderer/electron-types-spec.ts
- tests/renderer/remote-loader-spec.ts
- tests/renderer/runner-spec.tsx
- tests/renderer/state-spec.ts
- tests/renderer/task-runner-spec.tsx
- tests/utils/sort-versions-spec.ts
Extracted from #1204, with a test added to ensure it doesn't diverge from `@electron/fiddle-core` - although in most cases usage would cause a TypeScript error if something did change.
There may be more elegant ways to accomplish this, but this was the quickest/simplest. For full context, `@electron/fiddle-core` can't imported in the renderer process because it uses Node.js APIs.
> refactor: mirror InstallState from @electron/fiddle-core

- src/main/npm.ts
- src/renderer/runner.ts
- tests/main/npm-spec.ts
`yarn add` run by itself causes an error, if there are no specific modules to add, you need to use `yarn install`.
> fix: use yarn install if no modules to add

- package.json
- tools/fetch-releases.js
- yarn.lock
Simplifies this script and ensures `static/releases.json` is in-sync with what `@electron/fiddle-core` expects since it is the consumer. To that end it now populates the full release info (effectively just `releases.json` unmodified) so that it can be used in future PRs to pull Node.js versions and ABI info.
> build: use @electron/fiddle-core to fetch releases

- src/renderer/state.ts
Should fix this issue reported on Sentry.
---
Sentry Issue: [ELECTRON-FIDDLE-70G](https://electronjs.sentry.io/issues/4134810710/?referrer=github_integration)
```
Error: Currently installing "24.1.3"
at Installer.install (./node_modules/@electron/fiddle-core/dist/installer.js:283:19)
at t.AppState.downloadVersion (./src/renderer/state.ts:647:26)
at executeAction (./node_modules/mobx/dist/mobx.esm.js:1255:15)
at res (./node_modules/mobx/dist/mobx.esm.js:1239:12)
at t.AppState.setVersion (./src/renderer/state.ts:740:16)
```
> fix: check if already installing version

- tools/fetch-releases.js
Better handles things like doing a build with no network access after previously having done a build (clobbers `static/releases.json` at the moment) and allows for builds in a clean environment with no network access to patch `static/releases.json` and not have it clobbered.
> build: don't clobber existing releases.json on fetch failure

- package.json
Improves the DX by ensuring that `static/releases.json` will be populated. In the current state without this change, a developer could clone the repo, run `yarn install`, and then later without network access run `yarn start` and find things wouldn't work due to the empty `static/releases.json`. Populating it in `postinstall` should prevent that since they'll likely have network access when they run `yarn install`.
> build: do initial fetch of releases in postinstall script

- .circleci/config.yml
Did some testing over the last couple of releases and this seems necessary to get proper source mapping on Sentry.
> ci: use --url-prefix when uploading source maps

- src/ambient.d.ts
- src/interfaces.ts
- src/main/versions.ts
- src/preload/preload.ts
- src/renderer/electron-types.ts
- tests/mocks/electron-fiddle.ts
- tests/renderer/electron-types-spec.ts
> fix: get Node.js typings for newly released versions

- src/renderer/transforms/forge.ts
- tests/transforms/forge-spec.ts
Don't need to run the nightly Electron executable just to get the ABI, that's available from `@electron/fiddle-core` now.
> refactor: pull nightly ABI from release info

- src/renderer/npm-search.tsx
- tests/renderer/npm-search-spec.ts
The npm search functionality added in https://github.com/electron/fiddle/pull/959 only shows the top 5 results, and you can't force a package name, only select from that list of packages. For whatever reason, the boosting exact matches to the top doesn't occur (upstream issue) if the package is deprecated. The end result is you're unable to add deprecated packages since there will be 5 search results ahead of them in the list.
Tried various incantations to improve the situation, and this is the one that was effective. For unknown reasons filtering on `name` yields zero results, but filtering on `objectID` bumps the package to the top. Since `objectID === name` is (somewhat of) an implementation detail of `algolia/npm-search`, add a test to ensure it doesn't regress.
> fix: show exact match deprecated npm packages in search

- src/renderer/electron-types.ts
Cleans up logging when switching Node.js versions to reduce console clutter:
<details><summary>Before</summary>
</details>
<details><summary>After</summary>
</details>
> chore: only one console log for monaco Node.js lib update

- src/renderer/components/commands-runner.tsx
- src/renderer/components/settings-electron.tsx
- src/renderer/state.ts
- tests/renderer/state-spec.ts
Refs #1366.
Don't do the install step for a version until the user tries to run a fiddle. Doing so avoids collision on disk from multiple versions being installed at once (see reference issue). Also provides a nicer UX by not showing the unzipping spinner every time on start. Trade off is slightly longer initial run for a version since it needs to be unzipped and installed, but subsequent runs with the same version skip that step.
Should hopefully clear up a number of the disk errors being seen on Sentry around version management.
This partially reverts #1242 since that behavior becomes the only behavior.
> fix: don't install version until run

- src/main/main.ts
- tests/main/main-spec.ts
Fixes #1371
Maybe, probably. I believe the root cause is that the IPC listener was not setup yet when the window tries to grab the list of released versions. We use `ipcRenderer.sendSync` for that (for minimal refactoring reasons), and if the channel listener isn't set up that will fail and return `{error: 'reply was never sent'}`, which leads to the pictured error on that issue.
> fix: race condition when creating main window

- package.json
- yarn.lock
To avoid any quirkiness creeping in, ensure all of our `@electron-forge/*` packages are locked at the same version. The addition of `resolutions` ensures that third-party makers (like that added in #1379) also use the expected version.
> build: lock @electron-forge/* versions at 6.1.1

- src/interfaces.ts
- src/renderer/components/settings-execution.tsx
- src/renderer/state.ts
- src/renderer/versions.ts
- tests/renderer/versions-spec.ts
Here's my stab at #1352. I mostly followed the approach suggested in that issue, except that I'm listening for updates in the settings using the [`storage`](https://developer.mozilla.org/en-US/docs/Web/API/Window/storage_event) event instead of using IPC, so we can get the same result for free without touching the main process.
Just a consideration: any open windows (except the one in which the setting was changed) updates its `AppState` object in response to a setting being changed. However, this PR doesn't (directly) change anything related to the UI state. As you can see in the video below, if I have two windows with the Settings modal opened and I make changes in one of them, checkboxes are checked/unchecked in both windows, while text inputs don't change in the other window (unless I …
> fix: update settings in all open windows

- src/renderer/app.tsx
There's currently a flash of light mode UI on window load if you're using dark mode, this fixes that by awaiting `loadTheme` so that the theme is correctly set before the UI is loaded.
> fix: await loadTheme in app setup

- .circleci/config.yml
- forge.config.js
- package.json
- yarn.lock
using @reforged/maker-appimage
Closes: https://github.com/electron/fiddle/issues/405
Signed-off-by: Robert Günzler <r@gnzler.io>
> feat: support AppImage releases

- package.json
- yarn.lock
Should have no effect other than cleaning up `package.json` and `yarn.lock`.
* Removes unused `@octokit/action` dev dependency
* Adds `webpack`, `@octokit/core`, and `@testing-library/dom` dev dependencies to clear warnings about unmet peer dependencies
> build: cleanup package.json dependencies

- src/renderer/app.tsx
In theory this should result in better performance, in practice when trying to do some quick and dirty profiling the results were inconclusive. Doing these with `Promise.all` may smooth overall timings by ensuring one call taking a bit longer than usual for whatever reason doesn't slow all calls.
Since this is low risk, going to YOLO it under the assumption that at best it'll help things, at worse it's a no-op.
> perf: import modules in parallel during app setup

- .circleci/config.yml
CircleCI lets you require just the job name and it'll require the fully expanded matrix.
> ci: simplify publish job requires

- src/interfaces.ts
- src/renderer/components/settings-execution.tsx
- src/renderer/state.ts
Follow-up to #1376 which fixes a few bugs:
* Don't warn when `WindowSpecificSetting` settings are touched
* Fix cases where the enum value does not match the enum key
* Better handle several keys which do not exist on `AppState`
* Sync local versions properly between windows
* Update some JSDoc types which were changed in #1376
cc @erikian
> fix: improve behavior of setting sync between windows

- package.json
- src/main/windows.ts
- src/renderer/app.tsx
- src/renderer/components/commands-action-button.tsx
- src/renderer/components/output-editors-wrapper.tsx
- src/renderer/components/settings-execution.tsx
- src/renderer/components/sidebar.tsx
- src/renderer/file-manager.ts
- src/renderer/remote-loader.ts
- src/renderer/themes.ts
- src/utils/editor-utils.ts
- src/utils/read-fiddle.ts
- tests/mocks/electron-versions.ts
- tests/mocks/state.ts
- tests/renderer/bisect-spec.ts
- tests/renderer/editor-mosaic-spec.ts
- tests/renderer/remote-loader-spec.ts
- tests/utils.ts
- tests/utils/read-fiddle-spec.ts
- tsconfig.json
- yarn.lock
Most of the changes needed were to drop `suppressImplicitAnyIndexErrors`, which is deprecated. There may be more clever ways to type some of these, but this builds clean.
Needs #1386 to land first.
> build(deps): upgrade to TypeScript 5.1

- yarn.lock
`uuaw semver`
Clears security advisories that Dependabot is flagging.
> build(deps): deep update semver package versions

- .stylelintrc
- src/less/blueprint.less
- src/less/main.less
Reverts the changes to use `rgb(...)` with modern color syntax in #1393, and disables the lint rules. The change wasn't playing nice with the CSS output from the LESS files, and I tried updating a few relevant dependencies but wasn't able to fix it. I'm thinking it might have to do with `@blueprintjs/*`, which we're not going to upgrade any time soon.
> chore: revert rgba style change

- src/renderer/components/settings-electron.tsx
- src/renderer/state.ts
- tests/mocks/state.ts
- tests/renderer/components/settings-electron-spec.tsx
- tests/renderer/state-spec.ts
Currently, if we click "Download All Versions" there's no way to cancel that, which is pretty bad since that can be hundreds of downloads. The only way to cancel is to quit the app.
Introduced a `Stop Downloads` button in place of the `Download All Versions` button during download. Moved `isDownloadingAll` & `isDeletingAll` inside `AppState`. Did all of these according to the #1402 description. Some tests were failing because of these updates. Fixed the tests & also added new tests to cater to the changes.
Please let me know if I need any updates to the code. 
Closes #1402
> feat: cancel download all versions option

- forge.config.js
- package.json
* Adds `homepage` to `package.json` so that a website is displayed when installing the `.deb` on Ubuntu
* Adds software categories
* Adds the PNG icon as well as the SVG (not sure it actually gets used anywhere yet, but intend to do follow-up)
> build: add more metadata to Linux packages

- src/ambient.d.ts
- src/interfaces.ts
- src/renderer/state.ts
- tests/renderer/state-spec.ts
- tests/setup.js
This allows the download status and progress to be shared between windows:
https://github.com/electron/fiddle/assets/19478575/6b666696-e298-4b4a-8236-ed2c8d238be7
I also tried to make the BroadcastChannel logic extensible so we can use it to sync other data in the future.
> feat: sync version download statuses between windows

- package.json
- yarn.lock
* `cross-fetch` is used in `src/`
* `@babel/core` isn't used directly
> build: clean up incorrect deps

- src/renderer/components/settings-execution.tsx
The execution settings panel broke as a result of #1389. Making `SettingItemType` a proper enum broke the code which iterates over the values, as TypeScript is now creating a reverse mapping as well, which means `Object.values` was returning keys as well.
Refactored so that iterating the enum values is not necessary, and probably a bit better implementation as a result. It's still kind of funky how this state is stored on both `AppState` and `ExecutionSettingsState`, but this fixes the immediate breakage.
> fix: better handle env variables and execution flags settings changes

- .circleci/config.yml
Clears TODO where we couldn't use Node.js v18.16.x due to an upstream bug with Docker containers.
> ci: use Node.js v18.17.0

- src/main/files.ts
- tests/main/files-spec.ts
This fell out of #1416, once this is merged that PR will go green.
> fix: don't overwrite files if user clicks cancel

- .circleci/config.yml
- forge.config.ts
- tools/add-windows-cert.ts
There were a couple of issues preventing code signing on Windows from working properly, and it was silently failing. Fix those up and try to fail loudly if something isn't right.
> ci: fix code signing on Windows

- src/ambient.d.ts
- src/ipc-events.ts
- src/main/files.ts
- src/preload/preload.ts
- src/renderer/state.ts
- tests/main/files-spec.ts
A minimal refactor to remove a usage of `fs-extra` in the renderer.
> refactor: move local path exists check to main process

- .circleci/config.yml
- forge.config.ts
- tools/add-windows-cert.ts
The first attempt here in #1419 had some problems that this sorts out, namely:
* Environment variables on CircleCI changed names
* Wasn't properly getting and using the output of `tools/add-windows-cert.ts`
> ci: another Windows code signing fix

- src/renderer/electron-types.ts
- tests/renderer/electron-types-spec.ts
Follow-up to #1221. Since the types for local Electron versions can be updated, we should dispose any existing Electron types before adding the new ones.
> fix: dispose previous local types when they change

- package.json
- yarn.lock
Picks up a fix for dark mode title bar on Windows 10.
> chore: update to Electron 25.4.0

- jest.config.ts
I moved RTL tests to a subfolder in #1432 and failed to update the regex to actually run these tests.
Should we have a coverage report in-PR to make it easier to spot any coverage drops?
> test: update `testMatch` for RTL tests

- src/ambient.d.ts
- src/interfaces.ts
- src/ipc-events.ts
- src/main/electron-types.ts
- src/main/main.ts
- src/preload/preload.ts
- src/renderer/app.tsx
- src/renderer/electron-types.ts
- tests/main/electron-types-spec.ts
- tests/mocks/electron-fiddle.ts
- tests/mocks/electron-types.ts
- tests/mocks/fiddle-core.ts
- tests/renderer/electron-types-spec.ts
First PR to shift the file operations around Node.js types to the main process.
> refactor: move getting Node.js types to main process

- src/renderer/remote-loader.ts
- tests/renderer/remote-loader-spec.ts
Closes #1438 
Fixes an issue where loading gists over 1mb would throw an error due to the file being truncated. Per [Gist Docs](https://docs.github.com/en/rest/gists/gists?apiVersion=2022-11-28#truncation), when the file is truncated, the full contents can be obtained by fetching the raw url. This adds error handling for that issue.
Tested w/ https://gist.github.com/codebytere/e06a6d4e650ee581f90d0159b701aaa2
> fix: error loading big gists

- .circleci/config.yml
Was blocked on the token for a while but now we're good to go.
> ci: re-enable Coveralls

- src/renderer/components/commands-action-button.tsx
Closes https://github.com/electron/fiddle/issues/1457.
The previous logic appears to have been based on a misconception:
> Gist files are deleted by setting content to an empty string.
Per [docs](https://docs.github.com/en/rest/gists/gists?apiVersion=2022-11-28#update-a-gist):
> To delete a file, set the whole file to null. For example: `hello.py : null`. The file will also be deleted if the specified object does not contain at least one of content or filename.
> fix: deleting gist files

- .circleci/config.yml
We're seeing OOM occasionally on Linux builds due to over parallelization during packaging (due to running in a Docker container and getting the number of system CPUs, not how many vCPUs are available). Since it's right on the cusp (doesn't OOM every time), let's just bump the resource class as that's simplest and this job only runs on release builds.
> ci: use larger resource class for Linux builds

- src/less/components/version-select.less
- src/renderer/components/commands-action-button.tsx
- src/renderer/components/commands-runner.tsx
- src/renderer/components/tour-welcome.tsx
- src/renderer/components/version-select.tsx
- src/renderer/utils/position-for-rect.ts
- tests/renderer/components/__snapshots__/commands-publish-button-spec.tsx.snap
- tests/renderer/components/__snapshots__/commands-runner-spec.tsx.snap
- tests/renderer/components/__snapshots__/tour-welcome-spec.tsx.snap
- tests/renderer/components/__snapshots__/version-select-spec.tsx.snap
- tools/webpack/webpack.renderer.config.ts
The "Show Tour" feature is failing to highlight correct elements as the selectors are no longer valid. Change some of the selectors to ID rather than class, as that seems more correct. The editor selectors have to remain as-is as they're also used in CSS, but because they have dots in the class name (eek) they need to be escaped to be used as selectors.
> fix: update element selectors for tour

- .circleci/config.yml
Shifting more usage to the secret service.
> ci: load macOS release secrets from secret service

- .circleci/config.yml
- .github/workflows/coveralls.yml
If you use Coveralls from anything other than GitHub actions you need to provide a repo token, which doesn't work with forks because we don't want to expose secrets to them. It works on GitHub actions though, so bring it back there.
> ci: use GitHub actions for Coveralls

- src/interfaces.ts
- src/main/fiddle-core.ts
- src/renderer/runner.ts
- tests/main/fiddle-core-spec.ts
- tests/mocks/fiddle-core.ts
- tests/renderer/runner-spec.tsx
> fix: use process.env when running fiddle

- src/renderer/editor-mosaic.ts
- tests/renderer/editor-mosaic-spec.ts
Currently adding or deleting a file doesn't count as editing a fiddle which can lead to non-ideal behavior like adding a file without content and then switching selected versions and having the file disappear, or deleting a file and then closing the window and not being prompted to save.
> fix: mark fiddle as edited if files added/deleted

- package.json
- yarn.lock
Fixes #1468
Potentially some other issues related to versions getting stuck in a state when an error occurs.
> build(deps): bump @electron/fiddle-core to 1.3.2

- tools/add-macos-cert.sh
This is missing on CircleCI machines and causes the new certificate for macOS code signing to not be seen as valid.
> ci: download Apple Developer ID Intermediate certificate

- .circleci/config.yml
This was removed to work around an issue that has now been resolved in the secrets service.
> ci: restore usage of `load-release-secrets`

- src/interfaces.ts
- src/main/utils/read-fiddle.ts
- src/renderer/components/sidebar-file-tree.tsx
- src/renderer/editor-mosaic.ts
- src/renderer/remote-loader.ts
- src/renderer/utils/editor-utils.ts
- src/utils/editor-utils.ts
- tests/main/utils/read-fiddle-spec.ts
- tests/renderer/components/sidebar-file-tree-spec.tsx
- tests/renderer/remote-loader-spec.ts
- tests/utils/editor-utils-spec.ts
This PR adds support for JSON files. These can be used in Fiddle for data storage amongst other things - the impetus for this specifically is the ability to add `manifest.json` files for Chrome extensions.
> feat: add support for JSON files in editors

- package.json
- src/renderer/runner.ts
- tests/renderer/runner-spec.tsx
- yarn.lock
Closes https://github.com/electron/fiddle/issues/1504.
Fixes an issue where complex environment variables with multiple equal signs would be incorrectly parsed. This was happening because our env var parsing was [very simplistic](https://github.com/electron/fiddle/blob/main/src/renderer/runner.ts#L333-L343) and always split at equals signs.
We should use an existing env var parser instead, written and maintained by a Node.js maintainer. It has no dependencies.
> chore: fix environment variable parsing

- forge.config.ts
- tools/certs/requirements.txt
This enables us to build with intermediate designated requirements to move the codesigning certificate on macOS from me to OpenJS. 
Major downside: This will break CI as written, since CI currently only has the OpenJS certificate.
> build: Temporarily build with intermediate requirements

- src/renderer/components/commands-runner.tsx
- src/renderer/components/version-select.tsx
- tests/renderer/components/version-select-spec.tsx
Closes https://github.com/electron/fiddle/issues/1529
Handles the case where a local Electron executable has moved or been deleted.
Before:
After:
> fix: handle missing local Electron.app

- forge.config.ts
This should be good to go now. 🤞
> build: switch to OpenJS identity for macOS releasees

- .circleci/config.yml
#1435 pointed out that `mac-test-x64` is running on Apple Silicon now, so use Rosetta to run the tests under an x86_64 Node.js. In the case of that PR it would have made more clear that the tests were only failing on Apple Silicon, not Intel macOS, and been quicker to debug.
> ci: use x86_64 Node.js for some macOS jobs

- yarn.lock
Ensuring we're on the latest versions of `@electron/*` packages for dogfooding purposes, and to pick up some useful fixes for the release process.
> build: update @electron/* deps

- tests/main/electron-types-spec.ts
Noticing this test started flaking after #1533, I think the filesystem operations in that test is delayed when it's running under Rosetta, causing the flaky timeout. Doing a quick and dirty bump of the timeout to mitigate the flake for now.
> test: increase timeout in ElectronTypes watch test

- .github/workflows/check-download-links.yml
We've broken the download links on the website a few times and not noticed, so let's add some lightweight automation to confirm the links aren't 404ing after a new release.
Refs:
* electron/website/issues/467
* #1503
* #1539
> ci: check download links daily

- src/less/components/settings.less
- src/renderer/app.tsx
- src/renderer/components/commands.tsx
- src/renderer/components/header.tsx
- tests/renderer/app-spec.tsx
This PR fixes an issue where the app is not draggable when a user is on the Settings page. This is because the `tabbing-hidden` style applied to the header also nullifies the header's `-webkit-app-region: drag;` style.
This PR:
1. Moves the `tabbing-hidden` style to the `commands` component. This ensures that tabbing on the settings page does not focus these hidden elements.
2. Moves the `Dialogs` component to be rendered after `Header` and `OutputEditorsWrapper`. This ensures that when elements in the Settings page scroll over the header area, the header's `-webkit-app-region: drag;` doesn't swallow click events. I think this also makes sense from a `z-index` perspective as dialogs are usually rendered over main content.
3. Adds the `-webkit-app-region: no-drag;` style to all focusable …
> fix: allows users to drag app when settings are open

- src/renderer/file-manager.ts
- src/renderer/remote-loader.ts
- tests/renderer/file-manager-spec.ts
- tests/renderer/remote-loader-spec.ts
Closes https://github.com/electron/fiddle/issues/1546.
Fixes an issue I noticed whereby if a user tried to load a Gist containing invalid JSON in their package.json, a confusing error would be thrown.
<details><summary>Before</summary>
<p>
</p>
</details> 
<details><summary>After</summary>
<p>
</p>
</details>
> fix: better error message for bad `package.json`

- static/electron-quick-start/preload.js
Simple text change to the comment at the top of the the default `preload.js` file. Clarifies what the preload script runs before.
> chore: improve preload comment

- src/renderer/state.ts
- tests/renderer/state-spec.ts
Closes https://github.com/electron/fiddle/issues/1553.
Gracefully handle download failures and fall back to last usable version.
> fix: gracefully handle version download failure

- src/renderer/components/settings-general-font.tsx
- tests/renderer/components/__snapshots__/settings-general-font-spec.tsx.snap
When clicking the reload window button, nothing happened. The console reported the error
I just changed one line and it works fine.
```
- onClick={window.ElectronFiddle.reloadWindows}
+ onClick={() => window.ElectronFiddle.reloadWindows()}
```
> fix: reload window button not working

- src/renderer/components/sidebar-file-tree.tsx
- tests/renderer/components/sidebar-file-tree-spec.tsx
**Before**
```
appState.editorMosaic.remove(editorId);
appState.editorMosaic.addNewFile(id, contents);
if (visible) appState.editorMosaic.show(id);
```
If the new file name already existed or was another main entry point file, addNewFile() would throw error. Then, remove() would be executed but addNewFile() not, which means *renaming file failure would lead to the deletion of the file*.
**Now**
```
try {
appState.editorMosaic.addNewFile(id, contents);
appState.editorMosaic.remove(editorId);
if (visible) appState.editorMosaic.show(id);
} catch (err) {
appState.showErrorDialog(err.message);
}
```
> fix: uncaught error when renaming file failed

- src/renderer/state.ts
#1554 accidentally caused the download spinner to stop working when downloading a version. Swapping `this.version = version;` back to before the download begins fixes this, and still retains the fix in #1554 regarding download failures.
> fix: downloading spinner

- package.json
v0.36.1 had a show stopper which was fixed in #1568, so going again.
> chore: release v0.36.2

- package.json
- src/renderer/components/commands-action-button.tsx
- src/renderer/remote-loader.ts
- tests/renderer/components/commands-publish-button-spec.tsx
- yarn.lock
Clears a security alert. A few minor changes to make existing code work with updated types, but I've tested and there's no functional change.
> chore: update @octokit/rest

- src/main/files.ts
- tests/main/files-spec.ts
- tests/mocks/electron.ts
The original issue behind using `showOpenDialogSync`, #553, no longer repros. `showOpenDialogSync` doesn't play nice with multiple Fiddle windows as it will block the UI on other windows.
> fix: use async showOpenDialog

- src/renderer/components/settings-general-github.tsx
Just some rogue backticks that snuck into this comment somehow.
> chore: remove rogue backticks in comment

- static/show-me/dialog/main.js
Current example doesn't handle the edge case where the filename has a `#` as it needs to be encoded, which the naive construction of `file://${file}` does not handle. Just pass the path directly to `loadFile` instead as it will do the right thing.
> fix(show-me): use BrowserWindow.loadFile in dialog example

- tests/renderer/components/editors-spec.tsx
- tests/renderer/components/settings-general-appearance-spec.tsx
- tests/renderer/runner-spec.tsx
Noticed these when trying out converting to Vitest locally; them not actually awaiting the next tick was a problem there. Some of these may not be necessary but I'm just making them do what they intended to do.
> test: fix awaiting process.nextTick

- src/main/windows.ts
- tests/main/windows-spec.ts
Follow [our own security guidelines](https://www.electronjs.org/docs/latest/tutorial/security#15-do-not-use-shellopenexternal-with-untrusted-content) here and limit what we pass through to `shell.openExternal`.
> fix: limit usage of shell.openExternal to web URLs

- package.json
- src/main/update.ts
- tests/main/update-spec.ts
- yarn.lock
Just keeping this update-to-date.
> chore: bump update-electron-app from 2.0.1 to 3.0.0

- package.json
Only using `jest-junit` reporter can make some failures difficult to debug as the output doesn't capture them.
> test: include default reporter in CI

- .circleci/config.yml
- .github/workflows/coveralls.yml
- package.json
- tests/main/electron-types-spec.ts
- yarn.lock
Follow-up to #1537. Re-ran the workflow 5 times to confirm it didn't flake.
> test: fix flake under Rosetta

- package.json
- yarn.lock
Clears some audit warnings regarding `cookie` and `@sentry/browser`.
I also ran `npx uuaw express` to clear the one remaining usage of the vulnerable `cookie` version.
> build(deps): update @sentry/electron to 5.7.0

- src/templates.ts
- static/show-me/utilityprocess/child.js
- static/show-me/utilityprocess/main.js
Closes https://github.com/electron/fiddle/issues/1649.
> chore: add show-me for `utilityProcess`

- yarn.lock
Used `npx uuaw cross-spawn` to bump these.
> build(deps): bump cross-spawn to partially clear audit

- package.json
- yarn.lock
`npm-run-all` is unmaintained and hasn't had a publish in 6 years, `npm-run-all2` is a maintained fork. Also threw in an `npx uuaw minimatch` to consolidate those for good measure.
> build(dev-deps): switch to npm-run-all2

- src/renderer/app.tsx
- tests/renderer/app-spec.tsx
- tests/setup.ts
With better mocking we can remove `if (!!window.matchMedia)` in the code, which was only there because the mock wasn't defined for all tests.
> test: improve matchMedia mocking

- rtl-spec/components/commands-address-bar.spec.tsx
- rtl-spec/components/commands-bisect.spec.tsx
- rtl-spec/components/commands-version-chooser.spec.tsx
- rtl-spec/components/editors-non-ideal-state.spec.tsx
- rtl-spec/components/editors-toolbar-button.spec.tsx
- rtl-spec/components/tour-welcome.spec.tsx
- rtl-spec/components/tour.spec.tsx
- rtl-spec/components/version-select.spec.tsx
Clears these lint warnings on `yarn lint`:
```text
warning  Using exported name 'userEvent' as identifier for default export  import/no-named-as-default
```
> build: clear lint warnings regarding test import

- src/ambient.d.ts
- src/main/themes.ts
- src/renderer/app.tsx
- src/renderer/components/dialog-add-theme.tsx
- src/renderer/components/settings-general-appearance.tsx
- src/renderer/constants.ts
- src/renderer/state.ts
- src/renderer/themes.ts
- tests/main/themes-spec.ts
- tests/renderer/app-spec.tsx
- tests/renderer/state-spec.ts
- tests/renderer/themes-spec.tsx
Fixes #1658
Fixes #1657
This fixes a couple of issues, cleans up the relevant code, and improves the UX. See issues above for specifics of what is fixed here.
We had logic distributed in multiple places to fall back to `defaultDark` if no theme was set (like on initial install) so this PR refactors that to be at a higher level and avoids an unnecessary IPC call to the main process on initial install.
Improves UX by retaining the user's selected theme regardless of what state the "Sync theme with system setting" checkbox is in. Previously the theme selection dropdown would snap to whatever the system theme at the time was. Now the theme selection remains static and checking/unchecking the checkbox merely updates the theme to match the system, which is more intuitive than the theme …
> fix: improve behavior with regard to sync with system theme

- package.json
- tests/main/protocol-spec.ts
- yarn.lock
Required fixing the types in a test, I believe due to the change upstream in https://github.com/electron/typescript-definitions/pull/273. Since `app.on` is overloaded, TypeScript ends up choosing the last signature, which used to be `Function` before that change (fully permissive when invoking), after which it became `() => void`. Unfortunately it appears there's no way to extract the callback signature of just the events we want, so I manually rolled the types to get this building cleanly again.
> [When inferring from a type with multiple call signatures (such as the type of an overloaded function), inferences are made from the _last_ signature (which, presumably, is the most permissive catch-all case). It is not possible to perform overload resolution based on a list of argument …
> chore: update to Electron 33.3.0

- yarn.lock
We need to pick up the improved error handling.
> build: update @electron/notarize to 2.5.0

- .circleci/config.yml
It's the return of #1463. Kicking the can again instead of finding a proper solution.
> ci: use large resource class for Linux builds

- package.json
- yarn.lock
As in title, bumps `@sentry/electron` to clear audit warnings regarding GHSA-r5w7-f542-q2j4.
> build(deps): bump @sentry/electron to partially clear audit

- src/renderer/components/sidebar-file-tree.tsx
- src/renderer/editor-mosaic.ts
- tests/renderer/components/sidebar-file-tree-spec.tsx
- tests/renderer/editor-mosaic-spec.ts
Fixes a regression introduced in #1563 that somewhat broke #1474 since you can't rename `main.js` to `main.mjs`.
> fix: allow renaming between main entrypoint files

- src/renderer/components/output.tsx
- tests/mocks/monaco.ts
Fixes #1557 
Add CTRL/CMD+k keyboard shortcut to clear the console.
> feat: add keyboard shortcut (ctrl/cmd-k) to clear console

- src/templates.ts
- static/show-me/webcontentsview/main.js
Related #1648 
- Add `WebContentsView` API example to show-me examples.
> chore: Add WebContentsView API example

- src/less/blueprint.less
Fix #1085  by ensuring consistent focus outlines for input fields and buttons in dark mode.
Previously, input fields and buttons had inconsistent focus outlines, leading to a poor user experience.
**All elements are focused in the images below:**
Added `outline: @blue3 solid 2px;` to following classes in dark mode:
_.bp3-control input:focus ~ .bp3-control-indicator_
_.bp3-button:focus_
> fix: inconsistent outline color on focus when navigating using tab key

- src/less/components/commands.less
- src/renderer/components/version-select.tsx
Fixes #1274 : The titlebar was not responsive and did not adjust properly when resized horizontally.  
- Made the titlebar responsive using `@media` queries.
- Added `text-overflow: ellipsis` to handle long titles.
- Adjusted `address-bar` width based on viewport width for dynamic resizing and improved responsiveness.
- Hide button text on smaller screens, showing only icons.
https://github.com/user-attachments/assets/11c8faff-cb94-4392-b626-fba1e2c1b1a1
https://github.com/user-attachments/assets/873916c0-6150-435d-bb6d-94f35f411efc
> fix: make titlebar fully responsive

- src/less/blueprint.less
- src/less/components/commands.less
- src/less/components/settings.less
- src/renderer/components/version-select.tsx
Fixes some regressions introduced in #1667 which we didn't catch. I made the CSS changes target both `.bp3-popover2-*` and `.bp3-popover-*` since the `.bp3-popover2-*` name will go away again when we finally upgrade Blueprint.
> fix: some regressions in tooltip styling

- src/interfaces.ts
- src/renderer/file-manager.ts
- src/renderer/transforms/forge.ts
Allow packaging an app using forge with a local build of Electron using `@electron-forge/plugin-local-electron`.
> feat: allow packaging a local electron version

- package.json
- yarn.lock
As in title. Adds `markdownlint-cli2` to replace the removed `electron-markdownlint`.
> build(dev-deps): update @electron/lint-roller to 3.0.0

- package.json
- yarn.lock
Picks up the fix for 429s from GitHub when linting links.
> build(dev-deps): update @electron/lint-roller to 3.1.2

- package.json
- src/main/versions.ts
- tools/fetch-releases.ts
- yarn.lock
Now that all the prerequisite work has been done in #1717 and #1718, this is nice and straightforward. 🙂
> build(deps): bump @electron/fiddle-core to 2.0.1

- package.json
As of https://github.com/electron/fiddle/issues/1718 test failures don't show up due to redirection to output file:
it's important that CI shows actual test failures, so this tweaks that to both show the failures in CI and also generate a report.
> build: fix yarn:ci to show failures

- .circleci/config.yml
- src/main/about-panel.ts
- src/renderer/components/dialog-token.tsx
This slipped in during #1722 but wasn't caught until the release jobs ran because our CI was never running `tsc`, and the error was just being logged as a warning during tests rather than a fatal error. This PR updates our CI to ensure we run `tsc`, and then fixes the error that slipped in.
> chore: fix TS compilation

- package.json
v0.37.0 didn't go out because of a blocker fixed by #1731, so let's try again.
> chore: release 0.37.1

- package.json
- yarn.lock
The old version is no longer working during release builds (unclear why, haven't dug into it) so bump to the latest, which I've confirmed works for release builds.
> build(dev-deps): bump @reforged/maker-appimage to 5.0.0

- .circleci/config.yml
- .github/workflows/coveralls.yml
- tools/contributors.ts
This has been intermittently biting us in CI and now manifests in a TypeScript error after recent changes that are doing better typing for the imported JSON file.
The existing script wasn't checking if the fetch response was good before using it, which led to a situation where the initial fetch of contributors would succeed, but then fetching further details on each contributor would get rate limited and silently fail causing partial data.
I took the opportunity to clean up the script in general, and made some tweaks to the CI workflows to minimize the odds of being rate limited by GitHub. The CircleCI jobs are still at risk since it's non-trivial to give them a token to avoid it, but when we one day migrate to GHA that should go away.
> build: fix contributors fetch script silently failing

- src/renderer/components/sidebar-file-tree.tsx
- tests/renderer/components/__snapshots__/sidebar-file-tree-spec.tsx.snap
This PR resolves a minor UI issue where the buttons in the sidebar panel lack spacing and appear merged, which is particularly noticeable in dark mode.
Before:
After:
> fix: sidebar panel button sticking

- package.json
- yarn.lock
This was missed in #1718 - we no longer need `jest-environment-jsdom`, just `jsdom` itself.
> build(dev-deps): replace jest-environment-jsdom with jsdom

- forge.config.ts
- package.json
- yarn.lock
This reverts #1728. We found various issues in the latest major of `@electron/windows-sign` and got fixes published, but in the end this still isn't working in our CI for some reason, but neither is the old v1.2.2 version of `@electron/windows-sign` that we know works for others. I suspect it might be some weirdness with CircleCI, but I don't have the cycles to keep digging into it currently so rolling this back for now so we can actually get a release out.
> build: rollback change to use @electron/windows-sign

- .circleci/config.yml
- .github/workflows/test.yml
Start of the migration from CircleCI to GHA. For now switch tests to running on GHA (where we should be able to avoid the GH rate limiting that's plaguing us currently) and leave CircleCI just for releases. Next release we'll migrate the release workflow and validate it with an actual release.
> ci: add workflow to run tests on GHA

- src/main/content.ts
- tests/main/content-spec.ts
`electron/electron-quick-start` was renamed to `electron/minimal-repro` which has had an unintended consequence in how we handle templates for major versions. If you select an older version that we have a branch for on that repo (e.g. `v30.x.y`), you'll end up with a blank fiddle because Fiddle will download and extract a ZIP of that branch, which now unzips to `minimal-repro-N-x-y` when we are expecting `electron-quick-start-N-x-y`.
> fix: rename references to electron-quick-start repo
